### ISSUE TITLE
org.litepal.exceptions.DataSupportException: getİnt [int]

### ISSUE THREAD

**Issue by ihollysee** [LitePalFramework/LitePal#10]
Caused by: org.litepal.exceptions.DataSupportException: getİnt [int]
org.litepal.crud.DataHandler.query(DataHandler.java:141)
org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:122)
org.litepal.crud.DataSupport.findAll(DataSupport.java:628)
org.litepal.crud.DataSupport.findAll(DataSupport.java:609)

**Comment by Reacoder** [comment]
这个问题在下面设备上也有
SM-G900F
5.0
04 Feb 2015, 21:53	
SM-G900F
5.0
04 Feb 2015, 21:54	
SM-G900F
5.0
04 Feb 2015, 23:22	
SM-N7500Q
4.4.2
05 Feb 2015, 04:56	
Nexus 5
5.0.1
05 Feb 2015, 07:10	
Nexus 5
5.0.1
05 Feb 2015, 07:32	
Nexus 5
5.0.1
05 Feb 2015, 07:32	
SM-G900F
5.0
05 Feb 2015, 09:28

**Comment by Reacoder** [comment]
public static String capitalize(String string) {
		if (!TextUtils.isEmpty(string)) {
			return string.substring(0, 1).toUpperCase(Locale.getDefault()) + string.substring(1);
		}
		return string == null ? null : "";
	}

改成下面
	public static String capitalize(String string) {
		if (!TextUtils.isEmpty(string)) {
			return string.substring(0, 1).toUpperCase(Locale.US) + string.substring(1);
		}
		return string == null ? null : "";
	}

土耳其语言的I 长得不一样
