### ISSUE TITLE
在同级的多个Fragment存对象，只有第一个Fragment的对象能存取，这个是什么原因呢请问

### ISSUE THREAD

**Issue by sun1594732** [LitePalFramework/LitePal#103]

**Comment by sinyu890807** [comment]
有没有更仔细一点的描述，讲一下具体的操作过程可以吗

**Comment by sun1594732** [comment]
我在4个Fragment当中做了相同的存储对象集合的操作
（代码几乎都一样），但是只有第一个Fragment里的存储操作实现了，存储的对象是同样的

**Comment by sinyu890807** [comment]
有具体的代码吗？贴出来看一下

**Comment by sun1594732** [comment]
`@Override
    public void onDestroy() {
        int size;
        if (test.size()>10) {
            size = 10;
        }else size = test.size();
        for (int i = 0; i < size; i++) {
            NewsBeanToSaveBean(test.get(i)).save();
        }
        super.onDestroy();
    }

    public HeadSaveBean NewsBeanToSaveBean(HeadBean.DataBean.NewsBean bean){
        HeadSaveBean headSaveBean = new HeadSaveBean();
        headSaveBean.setType(1);
        headSaveBean.setTitle(bean.getTitle());
        headSaveBean.setIsVideo(bean.getIsVideo());
        headSaveBean.setNews_id(bean.getNews_id());
        headSaveBean.setNumberOfImage(bean.getNumberOfImage());
        headSaveBean.setPublishTime(bean.getPublishTime());
        headSaveBean.setSource(bean.getSource());
        if (bean.getImageURL().size()==1) {
            headSaveBean.setImageURL1(bean.getImageURL().get(0));
        }else if (bean.getImageURL().size()==3) {
            headSaveBean.setImageURL1(bean.getImageURL().get(0));
            headSaveBean.setImageURL2(bean.getImageURL().get(1));
            headSaveBean.setImageURL3(bean.getImageURL().get(2));
        }
        headSaveBean.setVideoImageURL(bean.getVideoImageURL());
        return headSaveBean;
    }`我在fragment的ondestory方法中逐个保存对象，那个NewsBeanToSaveBean方法是把每个Fragment不同的对象转换成统一对象进行保存，一开始以为是写在destory方法的问题，后来在其它地方写也是只有第一个Fragment的10条对象保存了，其它三个Fragment的对象没有保存

**Comment by sinyu890807** [comment]
你的Fragment是怎么用的，放在ViewPager里面的吗？

**Comment by sun1594732** [comment]
是的，viewpager嵌套4个Fragment

**Comment by sinyu890807** [comment]
我做了下测试，viewpager里面放了3个fragment，每个fragment里面都放了一个button，当点击各fragment里的button时分别执行下面的代码：
```java
Song song = new Song();
song.setName("song in fragmentg1");
song.setDuration(123);
song.saveThrows();

Song song = new Song();
song.setName("song in fragmentg2");
song.setDuration(123);
song.saveThrows();

Song song = new Song();
song.setName("song in fragmentg3");
song.setDuration(123);
song.saveThrows();
```

最后结果都是正确的，可以点下面的链接查看结果截图。
[http://img.blog.csdn.net/20160927163346783](http://img.blog.csdn.net/20160927163346783)

估计还是你哪里的用法出了问题吧，建议可以先把逻辑尽量简化，无关的代码都先删掉，把问题的原因确定出来，然后再想办法解决。
