### ISSUE TITLE
 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference

### ISSUE THREAD

**Issue by xingruyu** [LitePalFramework/LitePal#106]
Android Studio版本更新到2.2，gradle更新到2.14.1后，读取本地数据库时报如下错误：

 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference

LitePal版本1.3.1和1.3.2均报错。

**Comment by guolindev** [comment]
问题找到了，是因为Android Studio的Instant Run会向Model里面注入一个带有两个参数的构建函数，而LitePal在用反射进行对象创建的时候会寻找参数最少的那个构造函数，如果你的Model中是一个三个参数的构造函数，那LitePal就会找错创建对象的方法，从而报出上面的错误。这个bug在1.4.0版本中已修复。
