### ISSUE TITLE
使用过程中发现应用无响应，这是发生死锁了吗？demo如下

### ISSUE THREAD

**Issue by FJCDrome** [LitePalFramework/LitePal#115]
new Thread(new Runnable() {
            @Override
            public void run() {
                SQLiteDatabase database = Connector.getDatabase();
                database.beginTransaction();
                Log.e("sql","in thread");
                List l= DataSupport.findAll(RetailItem.class);
                Log.e("sql",l.size()+" in");
                database.endTransaction();
            }
        }).start();
Log.e("sql","out thread");
List l= DataSupport.findAll(RetailItem.class);
Log.e("sql",l.size()+" out");

日志：
11-14 12:01:37.020 3042-3042  out thread
11-14 12:01:37.020 3042-3057   in thread

**Comment by guolindev** [comment]
是的，这种用法还是挺危险的，因为虽然你是在不同线程里面操作的数据库，但litepal内部用的都是同一份SQLiteDatabase实例，现在你在主线程里面查询数据，但在子线程里面添加事务，看上去好像它们俩是在不同线程的，没啥关系，其实你在子线程里的事务操作让主线程的查询进行不下去了，而主线程的查询是有锁的，查询不结束锁就不会释放，这样子线程里的代码也永远执行不下去，就出现死锁了。你可以把事务的代码去掉，一切就正常了，关于litepal事务的功能，我后面会开发专门的api，尽量不要使用这种写法。

**Comment by FJCDrome** [comment]
感谢解答😁目前我把事务操作都放ui线程了，看上去暂时没什么问题

**Comment by FJCDrome** [comment]
@guolindev 感谢解答，不过我现在的项目是比较依赖事务操作的，非常看中数据的一致性，如果必须要多线程并且用到事务操作，有什么临时的解决办法吗？

**Comment by FJCDrome** [comment]
@guolindev 感谢解答，我现在不在事务以外使用DataSupport的静态同步的查询方法，应该可以避免死锁吧（事务操作对我的项目比较重要，无法舍弃）
