### ISSUE TITLE
在1.4.0版本中，DateSupport.count()报错

### ISSUE THREAD

**Issue by ycuwq** [LitePalFramework/LitePal#116]
在1.4.0 中 使用`DataSupport.count()`会出`org.litepal.exceptions.InvalidAttributesException: dbname is empty or not defined in litepal.xml file` 的错误。
在之前先调用一次`DataSupport.findAll()` 就会正常运行，在1.3.2就不会出现这个问题

**Comment by zenochan** [comment]
我也遇到这个问题了

**Comment by Alex-Linrk** [comment]
我也遇到这个问题，check了下代码，发现调用的时候数据库根本还没建立。

**Comment by guolindev** [comment]
1.4.1版本中已修复此问题，升级即可解决。

**Comment by Alex-Linrk** [comment]
辛苦了，郭大 这就去升级
