### ISSUE TITLE
数据库version升级后，byte[]丢失

### ISSUE THREAD

**Issue by CarpOrange** [LitePalFramework/LitePal#117]
一张表中存入bye[]，在升级Litepal.xml中的version,和给表增加一个字段之后，byte[]的字段所有数据丢失，别的类型的数据还在

**Comment by CarpOrange** [comment]
好像是因为你的获取表结构的sql语句执行之后，cursor查询出的的blob字段的数据类型不是blob,而是null。暂时不知道怎么解决 - -

**Comment by CarpOrange** [comment]
?????????????????

**Comment by guolindev** [comment]
别急，已经解决掉了，我还在看别的bug，一起解决了我再发个新版本

**Comment by CarpOrange** [comment]
好的。如果能加入sqlcipher加密就更好了。我现在是自己替换的。

**Comment by guolindev** [comment]
1.4.1版本中已修复此问题，升级即可。
