### ISSUE TITLE
我的API里面的id和表中的id自增冲突

### ISSUE THREAD

**Issue by coder-luhao** [LitePalFramework/LitePal#119]
如题，我想保存id这个字段，但是数据库会默认id自增，有没有映射时自定义列名的方法？或者有其他解决方案？

**Comment by guolindev** [comment]
id和_id这两个字段是litepal要使用的关键字，litepal里面的很多功能都要和id进行关联，这个没办法，只能你全名一个别的字段。如何是服务器那边返回的json数据里面有id这个字段，gson和fastjson都是有办法将json里面id映射成另外一个字段名的。
