### ISSUE TITLE
可以出中文版的doc和readme

### ISSUE THREAD

**Issue by zengcanxiang** [LitePalFramework/LitePal#122]
很多项目都有许多人在翻译他的doc或者是双语readme，不能咋自己人写的项目没有吧.(英语学渣飘过~)，这样也不需要写很多文章来一一解释API了。大家可以自己看，如果项目更新的比较大，我们也可以通过API来知道如何适配最新的项目.

**Comment by laksg2009** [comment]
哎这个支持

**Comment by guolindev** [comment]
中文版的可以去看我的博客，比这个guide文档详细得多了 http://blog.csdn.net/column/details/android-database-pro.html

**Comment by zengcanxiang** [comment]
呀，最新的api不知道郭神更新到博客里面了么。因为我是通过第2行代码然后在看博客，在看Github项目的。
