### ISSUE TITLE
不支持List<String>

### ISSUE THREAD

**Issue by longqiankun** [LitePalFramework/LitePal#123]
1.Module中定义了List<String>,数据库不支持。报错。出现 表不存在

**Comment by CarpOrange** [comment]
List类型存储的类需要继承自DataSupport,好像是这样。你可以写个类继承自DataSupport，里面有String类型的字段。把这个类存起来先。然后再在List中存这个类

**Comment by csbz17027** [comment]
在定义基础数据类型数组字段时必须进行对象初始化，例如private List<String> list = new ArrayList();

**Comment by guolindev** [comment]
List<String>类型从1.4.0版本开始支持，具体用法你可以参考一下这篇文章
http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650237709&idx=1&sn=1e9ee99617b2cb8f00af9b35eb83a637&chksm=88639a62bf14137450f5c98ec245362a0fef36e1bae1eaf12081d52d8b0e60a2c299e1699593#rd
