### ISSUE TITLE
假如我要保存一些数据，但是这些数据中有些可能是已经存在的，我如何区分它

### ISSUE THREAD

**Issue by zengcanxiang** [LitePalFramework/LitePal#125]
业务场景：  
例如用户本地搜索记录，可能重复搜索某一个商品，但是我保存的时候，我想通过商品名，或者业务字段来区分。  
如果数据库中某一条记录的该字段或者多个字段相等，那么就更新，否则就新建保存。  
这样我如何来实现？现在是手动查询数据库里面所有符合条件的记录，如果有，然后改变对象的值，在进行保存。

**Comment by guolindev** [comment]
你的做法是可以的，因为这本来就属于业务逻辑，去进行业务逻辑校验是很正常的做法。当然，litepal也有提供更加方便的api，1.3.2版本里面加入了一个saveIfNotExist方法，具体用法可以参考下面这篇文章。
http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650236130&idx=1&sn=e4b5bb20ce0938a2db5b9b1007c54907#rd
