### ISSUE TITLE
1.4.0的版本偶尔会报错，原因未知

### ISSUE THREAD

**Issue by fishboil** [LitePalFramework/LitePal#126]
Caused by: org.litepal.exceptions.InvalidAttributesException: dbname is empty or not defined in litepal.xml file

数据库的名称在xml里边以及配置了
    <dbname value="heater" ></dbname>

**Comment by mgracy** [comment]
I follow the instruction, and I always get this issue 'dbname is empty or not defined in litepal.xml file', my version of litepal is 1.4.1。I check the configuration several times, and still failed.

**Comment by mgracy** [comment]
After test with other version, and search from internet, I found that my path  of assets folder is not right, and I move the assets folder path to  'xxx\xxx\app\src\main\', and it worked.  
![ephgvr8](https://cloud.githubusercontent.com/assets/765889/21374668/43b92728-c763-11e6-949f-80d3b233ebc4.png)

**Comment by guolindev** [comment]
这个问题应该是1.4.0版本中的bug，1.4.1版本中已经修复掉这个问题了，具体可以参考一下这条bug https://github.com/LitePalFramework/LitePal/issues/116
