### ISSUE TITLE
Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by csbz17027** [LitePalFramework/LitePal#127]
郭神，在使用DataSupport.where方式进行查询时报出这个错误。
org.litepal.crud.DataHandler.query(DataHandler.java:150)
org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
org.litepal.crud.ClusterQuery.find(ClusterQuery.java:212)
org.litepal.crud.ClusterQuery.find(ClusterQuery.java:188)

**Comment by csbz17027** [comment]
因为是在第三方平台的崩溃日志里看到的，自己调试也无法重现，只知道调用的方法是
DataSupport.where("activity_id = ? and status = ?", uploadFile.getActivity_id(), UploadFile.UPLOADING).find(UploadFile.class);
而且这个错误报告仅仅出现过一次，所以信息比较匮乏。抱歉。

**Comment by guolindev** [comment]
那我先把问题关了，等你有更详细的信息的时候再提个新bug。
