### ISSUE TITLE
关于多个.db文件的问题

### ISSUE THREAD

**Issue by act64** [LitePalFramework/LitePal#128]
app里面有两个.db文件，一个是存储用户无关的数据 a.db，另一个存着用户相关的数据 b.db，感觉每次要将数据存到 a.db的表里 另外再存到 b.db的表里 每次都要 调用LitePal.use()方法很是蛋疼。请问 能否支持下这种情况

**Comment by guolindev** [comment]
使用use方法来切换数据库是我能想到的最方便的方式，如果你又想使用多个数据库，又嫌使用use方法来切换麻烦，那我暂时也想不出什么更好的办法了。当然如果你有好的想法也可以提出来，我觉得合理的话会加入到LitePal当中。
