### ISSUE TITLE
创建boolean列时遇到的疑惑

### ISSUE THREAD

**Issue by laksg2009** [LitePalFramework/LitePal#130]
1.4.1版
实体
public class PatientData extends DataSupport implements Serializable {
    ......................
    private String diagnose = "";// 诊断(病例中的内容)
    // 备份资料时会出现的字段
    private boolean is_backups = false;// 是否备份
    private boolean is_diagnose = false;// 是否已诊断
    private int backups_time;// 备份时间
保存数据库
 PatientData patientData = new PatientData();
        ................
        patientData.setOutpatient_number(numberTwo);
        patientData.setIs_backups(false);
        patientData.setIs_diagnose(true);
        if (patientData.save()) {
结果
is_backups 数据库显示为0
is_diagnose 数据库显示为1

查找是这样写
patientDatas = DataSupport.where("doctor_name = ? and is_diagnose = ?", login_name, "0").find(PatientData.class);

我个人理想结果是
数据库显示为is_backups 数据库显示为false
                     is_diagnose 数据库显示为ture
查找是这样写
patientDatas = DataSupport.where("doctor_name = ? and is_diagnose = ?", login_name,false(或"false")).find(PatientData.class);

**Comment by guolindev** [comment]
思考了很久，这个问题还是不能很好地解决，因为我没办法准确判断出来开发者的意图，到底是想传的布尔的true false，还是字符串的true false。如果我统一都把true和false在内部转换成1和0，那如果开发者的意图本来就是想查询某个一列的内容等于字符串的true或false呢？所以这个还是只能靠开发者自己来传入1或0才行。

**Comment by lu-xu** [comment]
所以现在已经把boolean默认都变成1和0了吗？我新建的数据库字段，外面定义是boolean，save的时候也是存的boolean。去数据库查看的时候，就变成1和0了

**Comment by RUANHAOANDROID** [comment]
true和false 作为关键字 直接存储是很不理智的
