### ISSUE TITLE
请问，现在表的id是内部控制自增的，而且是int型的，假如数据过大导致int自增到了最大值，会发生什么情况呢？是从0开始自增，还是无法存储数据？

### ISSUE THREAD

**Issue by wblyuyang** [LitePalFramework/LitePal#131]

**Comment by guolindev** [comment]
不可能从0开始的，应该会是后者，无法存储数据。不过这种情况基本上是不可能的，除非你的一张表中会存储几十亿条数据，这个数据量在客户端而言是不可想象的，即使你每天向表里面存100万条数据，要达到整型上限的话也需要5年多的时间，因此基本可以不用考虑这种情况。即使是服务器框架，也大多数都是用这种自增长的方式来做主键的。
