### ISSUE TITLE
下一版本能否扩展saveIfNotExist方法

### ISSUE THREAD

**Issue by longqiankun** [LitePalFramework/LitePal#132]
能否在重载一个方法
1.一种是如果根据条件判断当前数据库存在就不新增，否则就新增。目前已支持
2.另一种是如果根据条件判断当前数据库存在就更新，否则就新增。

就是扩展为，存在就更新数据，不存在就新增数据。

**Comment by gundumw100** [comment]
我还建议新增一个bean.update()，不带参数的update方法；
目前版本中有一个bean.update(long id)，带参数有点拖沓，对于一个已经持久化了的对象，可以直接bean.update()，而不需要bean.update(bean.getId())这样吧？因为bean已经持久化过了，也就id确定了，所以可以直接update()。

**Comment by guolindev** [comment]
一楼说的我在设计saveIfNotExist()方法的时候就想过了，但是限于因素不好实现，不然我肯定加上这个功能了。二楼说的这个功能现在就有，只不过你不需要调用update()方法，再调一次save()方法就能实现你想要的功能了。

**Comment by guolindev** [comment]
现在1.5.1版本已经支持一楼说的这个功能了，调用saveOrUpdate()方法就可以实现。

**Comment by guolindev** [comment]
现在1.5.1版本已经支持一楼说的这个功能了，调用saveOrUpdate()方法就可以实现。
