### ISSUE TITLE
实体1保存-> 清空表 -> 实体1保存： 最后一步保存返回true，但是保存失败

### ISSUE THREAD

**Issue by zenochan** [LitePalFramework/LitePal#133]
```java
Product product = new Product();
product.setCount(1);
product.save();
Product.deleteAll(Product.class);
product.setCount(2); 
product.save()// return true but save failed；
```

**Comment by guolindev** [comment]
这是因为，你调用了deleteAll()方法虽然删除了数据库中的数据，但是对象里面的存储状态却没有改变。
你把代码改成这样就可以了：
Product product = new Product();
product.setCount(1);
product.save();
Product.deleteAll(Product.class);
product.clearSavedState();
product.setCount(2); 
product.save();
