### ISSUE TITLE
创建多个数据库

### ISSUE THREAD

**Issue by hanshengjian** [LitePalFramework/LitePal#134]
郭神，除了目前在assets中litePal.xml定义的数据库之外，我还想创建另外一个数据库，应该怎么办

**Comment by guolindev** [comment]
仔细看看文档，从1.4.0版本开始就支持多数据库功能了。或者你可以参考这篇文章 http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&tempkey=8aIQFDjnJLAr2jkSc97iIe0WSlpRdEeTLZzePi%2FsD1uFQ%2FjLHEsRK1rk4jXDmExiYUympi9nW5cAHv2J%2Bjz4mwxR2HUpX9kCtHhTYwEskwsIpZM1YBlRZY0pqxUpAZkhgrF4kUHxqt7EdCplMr3mLg%3D%3D&chksm=08639b863f141290ffa6f33caf6be4ae5d0d1bc30f2dfe7864adae08a25a8ca3d8568702a777#rd

**Comment by ZmjDns** [comment]
我在用kotlin创建多个数据库的时候按照ReadMe中例之，创建后找不到第二个数据库
 val recotdDB = LitePalDB(“namenew”,1)
recotdDB.addClassName(Song::class.java.name)
LitePal.use(recotdDB)
当我看上面的连接时，已经失效了，可否请大佬出来指点一下
