### ISSUE TITLE
表关联出现问题

### ISSUE THREAD

**Issue by Xanthuim** [LitePalFramework/LitePal#135]
我有个资源表和分类表，是n对1的情况，并且已经做了关联。现在当我第一次插入一条资源信息，并且把分类设置到资源信息中，两个表保存成功了。但是当第二条资源信息再插入的时候，我的分类信息不用再插入吧？但是不插入的话就会发现资源表的外键是null。请问这个如何处理？还是说我需要再次更新一下呢？

**Comment by qht1003077897** [comment]
请问怎么解决的呢？
