### ISSUE TITLE
一次性保存10万条数据报OutOfMemoryError

### ISSUE THREAD

**Issue by gundumw100** [LitePalFramework/LitePal#138]
业务需要将10万条数据保存在本地，于是我想到使用litepal简单快捷的导入这些数据，结果报了OutOfMemoryError，保存的时候是异步的AsyncTask。

List<Product> products=new ArrayList<Product>();//10万条数据
DataSupport.saveAll(products);

我用saveFast()一条一条存，存了半天，但没报错。

我将10w+条数（实际137461条数据）据分拆成1000组数据，然后for循环分批保存，使用DataSupport.saveAll(subProducts)总会碰到OutOfMemoryError的情况，是否保存完数据list没释放或其他什么原因？
看异常似乎是StringBuilder.append()的原因。

我不知道是litepal还是google的问题，完整的异常：
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): java.lang.RuntimeException: An error occured while executing doInBackground()
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.lang.Thread.run(Thread.java:838)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): Caused by: **_java.lang.OutOfMemoryError_**
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.lang.StringBuilder.append(StringBuilder.java:216)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1458)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at org.litepal.crud.SaveHandler.saving(SaveHandler.java:232)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at org.litepal.crud.SaveHandler.doSaveAction(SaveHandler.java:191)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at org.litepal.crud.SaveHandler.onSaveAll(SaveHandler.java:154)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at org.litepal.crud.DataSupport.saveAll(DataSupport.java:885)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at com.app.pandian.MainActivity$ReadToDatabaseTask.doInBackground(MainActivity.java:94)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at com.app.pandian.MainActivity$ReadToDatabaseTask.doInBackground(MainActivity.java:1)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
01-03 09:25:01.876: E/CustomActivityOnCrash(2725): 	... 4 more

**Comment by Shyky** [comment]
悲剧了

**Comment by gundumw100** [comment]
还有，我记得你优化过的，我现在保存1万条数据，居然需要25秒？我记得只要4，5秒就够了的。
我用的 版本litepal1.4.0
新建的实体类model有什么诀窍吗？
public class Product extends DataSupport implements Parcelable {

        private String accountingCode;// 核算码 varchar(10)
	private String patternCode;// 款号 varchar(10)
	private String barCode;// 条码 varchar(13)
	private String color;// 颜色 varchar(20)
	private String size;// 码数 varchar(20)
	private String name;// 名称 varchar(60)
	private float price;// 标签价 numeric(9,2)
	private String cup;// 罩杯 varchar(20)
	private int quantity;// 包装含量 int

//setter getter

}

**Comment by Shyky** [comment]
这个库都一个月没有更新了，郭逼

**Comment by gundumw100** [comment]
不要骂人好哇........

**Comment by Shyky** [comment]
郭逼是作者自称，我没骂人

**Comment by gundumw100** [comment]
还是效率问题。
我将10w条数据分拆成10组数据分批保存，每批数据至少要消耗25秒以上。
什么个情况？？

**Comment by gundumw100** [comment]
我将10w条数据分拆成1000组数据，然后for循环分批保存，使用DataSupport.saveAll(subProducts)总会碰到OutOfMemoryError的情况，是否保存完数据list没释放或其他什么原因？

**Comment by RUANHAOANDROID** [comment]
麻烦看看你AsyncTask里面代码怎么写的

**Comment by gundumw100** [comment]
`
protected Boolean doInBackground(String... params) {
.......
//分段保存数据，本想避免OutOfMemoryError，可还是OutOfMemoryError
	            double delta=10.0;//每段的大小
	            int size=products.size();//137461
	            //取最优的delta
	            if(size>=10000){
	            	delta=10000.0;
	            }else if(size>=1000){
	            	delta=1000.0;
	            }else if(size>=100){
	            	delta=100.0;
	            }
	            
	            double times=Math.ceil(size/delta);//分几段
	            for(int j=0;j<times;j++){
	            	if (isCancelled()) {
						return false;
					}
	            	List<Product> sub=null;
	            	if(j==times-1){//最后一段
	            		sub=products.subList(j*(int)delta, products.size());
	            	}else{
	            		sub=products.subList(j*(int)delta, (j+1)*(int)delta);
	            	}
	            	publishProgress(j,(int)times);
//	            	long startTime=System.currentTimeMillis();
	            	DataSupport.saveAll(sub);
//	            	long endTime=System.currentTimeMillis();
//	            	Log.i("tag", "第"+j+"段耗时"+(endTime-startTime));
	            }
........
}`

**Comment by gundumw100** [comment]
得，我整个类都贴给你吧。
`
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;

import org.litepal.crud.DataSupport;

import android.app.ProgressDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.os.AsyncTask;
import android.os.Environment;
import android.util.Log;

import com.app.zstore.App;
import com.app.zstore.BaseActivity;
import com.base.util.D;
import com.base.util.comm.SPUtils;

/**
 * 
 * @author Ni Guijun
 *
 */
public class ReadToDatabaseTask extends AsyncTask<String, Integer, Boolean> { 
	
	private Context context;
	private ProgressDialog dialog;
	private int strategy=0;//写入策略
	
	public ReadToDatabaseTask(Context context){
		this.context=context;
	}
	
    @Override  
    protected void onPreExecute() {  
        super.onPreExecute();  
        showDialog();
    }  
    @Override  
    protected Boolean doInBackground(String... params) {
    	String fileName="DSLR"+File.separator+"T_GOODSBASE.TXT";
    	try {
    		//AssetManager-->addDefaultAssets CIP path not exsit!
    		publishProgress(100);
    		long start=System.currentTimeMillis();
    		DataSupport.deleteAll(Product.class);
    		long end=System.currentTimeMillis();
    		Log.i("tag", "清空数据消耗时间:"+(end-start));
    		publishProgress(101);
        	String encoding="GBK";
        	File file = new File(Environment.getExternalStorageDirectory(),fileName);
        	Log.i("tag", file.getAbsolutePath());
        	if(!file.exists()){
    			Log.i("tag", "缺少"+fileName+"文件");
    			publishProgress(-1);
    			return false;
    		}
//        	InputStreamReader reader = new InputStreamReader(getResources().getAssets().open(params[0]),encoding); 
        	FileInputStream fis = new FileInputStream(file);
            InputStreamReader reader = new InputStreamReader(fis,encoding); 
            BufferedReader br = new BufferedReader(reader);
            String line="";
            start=System.currentTimeMillis();
            List<Product> products=new ArrayList<Product>(10000);
            while((line = br.readLine()) != null){
            	if(isCancelled()){
            		break;
            	}
            	String[] split=line.split("\t");
            	if(split!=null&&split.length==9){
            		Product p=new Product();
            		p.setAccountingCode(split[0]);
            		p.setPatternCode(split[1]);
            		p.setBarCode(split[2]);
            		p.setColor(split[3]);
            		p.setSize(split[4]);
            		p.setName(split[5]);
            		p.setPrice(Float.parseFloat(split[6]));
            		p.setCup(split[7]);
            		p.setQuantity(Integer.parseInt(split[8]));
            		products.add(p);
//            		if(products.size()==10000){
//            			break;
//            		}
            	}
            }
            br.close();
            reader.close();
            fis.close();
            
            end=System.currentTimeMillis();
            Log.i("tag", "加载到内存消耗时间:"+(end-start)+";总共"+products.size()+"条数据");//36986
            if(products.size()==0){
            	return false;
            }
            publishProgress(102);
            start=System.currentTimeMillis();
            if(strategy==0){
				int i = 0;
				for (Product p : products) {
					if (isCancelled()) {
						return false;
					}
					p.saveFast();
					publishProgress(i, products.size());
					i++;
					// Log.i("tag", "i="+i);
				}
            }else if(strategy==1){
            	DataSupport.saveAll(products);//一次性保存OutOfMemoryError
            }else if(strategy==2){
	            //分段保存数据，本想避免OutOfMemoryError，可还是OutOfMemoryError
	            double delta=10.0;//每段的大小
	            int size=products.size();//137461
	            //取最优的delta
	            if(size>=10000){
	            	delta=10000.0;
	            }else if(size>=1000){
	            	delta=1000.0;
	            }else if(size>=100){
	            	delta=100.0;
	            }
	            
	            double times=Math.ceil(size/delta);//分几段
	            for(int j=0;j<times;j++){
	            	if (isCancelled()) {
						return false;
					}
	            	List<Product> sub=null;
	            	if(j==times-1){//最后一段
	            		sub=products.subList(j*(int)delta, products.size());
	            	}else{
	            		sub=products.subList(j*(int)delta, (j+1)*(int)delta);
	            	}
	            	publishProgress(j,(int)times);
//	            	long startTime=System.currentTimeMillis();
	            	DataSupport.saveAll(sub);
//	            	long endTime=System.currentTimeMillis();
//	            	Log.i("tag", "第"+j+"段耗时"+(endTime-startTime));
	            }
            	
            }
            end=System.currentTimeMillis();
            Log.i("tag", "写入到数据库消耗时间:"+(end-start));
            return true;
    	} catch (Exception e) {
            e.printStackTrace();
        }
    	return false;
    }  
    @Override  
    protected void onPostExecute(Boolean result) {  
        super.onPostExecute(result);
        if(result){
        	int count=DataSupport.count(Product.class);
        	Log.i("tag", "写入数据完成，总共"+count+"条数据");
        	SPUtils.put(context, App.KEY_HAS_DATA, true);
        }else{
        	Log.i("tag", "写入数据失败");
        }
        if(dialog!=null){
        	dialog.cancel();
        }
    }  
    @Override  
    protected void onProgressUpdate(Integer... values) {  
        super.onProgressUpdate(values); 
        switch (values[0]) {
        case -1:
        	((BaseActivity)context).showToast("缺少基础文件");
        	break;
		case 100:
			if(dialog!=null)
			dialog.setTitle("正在删除旧数据...");
			break;
		case 101:
			if(dialog!=null)
			dialog.setTitle("正在加载文件...");
			break;
		case 102:
			if(dialog!=null)
			dialog.setTitle("正在将TXT写入数据库...");
			break;

		default:
			dialog.setMessage("正在初始化数据，此操作比较耗时，请等待...("+(values[0]+1)+"/"+values[1]+")");
			break;
		}
        
    }

	@Override
	protected void onCancelled() {
		// TODO Auto-generated method stub
		super.onCancelled();
		D.showDialog((BaseActivity)context, "操作被中断，如需恢复，请点击‘初始化数据’", "确定");
	}
    
    private void showDialog(){
    	dialog = new ProgressDialog(context);
        dialog.setProgressStyle(ProgressDialog.STYLE_SPINNER);
        dialog.setTitle("准备数据中...");
        dialog.setMessage("正在初始化数据，此操作比较耗时，请等待...");
        dialog.setCancelable(false);
        dialog.setCanceledOnTouchOutside(false);
        dialog.setButton(DialogInterface.BUTTON_POSITIVE, "强行终止", new DialogInterface.OnClickListener() {  
        	  
            @Override  
            public void onClick(DialogInterface d, int which) {  
            	showForceDialog();
            }  
        });
        dialog.show();
    }
    
    private void showForceDialog(){
    	D.showDialog((BaseActivity)context, "强行终止会影响数据的完整性，需要中断操作吗？", "确定", "取消", new D.OnPositiveListener() {
			
			@Override
			public void onPositive() {
				// TODO Auto-generated method stub
				cancel(true);
			}
    	},new D.OnNegativeListener() {
			
			@Override
			public void onNegative() {
				// TODO Auto-generated method stub
				if(dialog!=null){
					dialog.show();
				}
			}
		});
    }
}
`

**Comment by gundumw100** [comment]
我使用策略strategy==1报OutOfMemoryError，使用strategy==2也报OutOfMemoryError
所以暂时只能使用strategy==0

**Comment by guolindev** [comment]
使用strategy==0就不报OutOfMemoryError了吗？也是存储的10w条数据？

**Comment by guolindev** [comment]
还有，你的Product类里面只有上面定义的那些字段吗？有没有关联关系？

**Comment by gundumw100** [comment]
strategy==0使用saveFast()没问题的。
使用DataSupport.saveAll(products)不管是一次性还是分批保存都会OutOfMemoryError。

Product类就这么点字段，没多余的。

**Comment by gundumw100** [comment]
for(int i=0;i<n;i++){
DataSupport.saveAll(products)
}
只要n足够大，总会发生OutOfMemoryError的情况

**Comment by guolindev** [comment]
for(int i=0;i<n;i++){
DataSupport.saveAll(products)
}
这种用法肯定是错的，不过我估计你是笔误，我来看看下面那种用法为什么会OOM吧
for(int i=0;i<n;i++){
}
DataSupport.saveAll(products)

**Comment by gundumw100** [comment]
我是分了1000组数据，所以需要这样写
double times=Math.ceil(size/delta);//分几段
            for(int j=0;j<times;j++){
            	List<Product> sub=null;
            	if(j==times-1){//最后一段
            		sub=products.subList(j*(int)delta, products.size());
            	}else{
            		sub=products.subList(j*(int)delta, (j+1)*(int)delta);
            	}
DataSupport.saveAll(subProducts)
}

**Comment by guolindev** [comment]
我做了几次测试，感觉可能真的和你的手机有关，另外和你们的项目应该也有关系。
先说一下我做的测试吧，我是把你的Product类完整复制过来的。然后调用的下面的代码进行存储：

```java
for (int i = 0; i < 100000; i++) {
    Product product = new Product();
    product.setName("a");
    product.setAccountingCode("b");
    product.setBarCode("c");
    product.setColor("d");
    product.setCup("e");
    product.setPatternCode("f");
    product.setPrice(i);
    product.setQuantity(i);
    product.setSize("g");
    products.add(product);
}
DataSupport.saveAll(products);
```

我用了两台手机测试，一台小米5，一台nexus 5，都是可以正常存储的，不会OOM。
另外我在每台手机上都操作了15次，也就是一共各存储了150w条数据，都正常，两台手机都没有OOM。

另外我用监控工具看了一下内存占用的情况，刚进入测试程序的时候内存占用是14M，点击存储之后内存最高会升到50M，存储完了点击一下GC，内存又会降到14M，也就是没有内存泄漏的情况。

所以根据我的分析，应该是你的手机配置以及你的应用程序本身会占用比较高的内存导致的。

手机配置的问题我就不说了，建议换个好点的手机试试，毕竟你是在进行大数据操作。然后是你的应用程序本身的问题，因为我是拿的一个demo测的，这个程序本身没什么东西，所以占用内存很低，我进行了10w条数据的存储也没有OOM，但是你的应用程序可能本身就会占用不少内存，这个时候再一次性开辟很大的内存，可能就超出系统的限制了。为什么在for循环中一直调用saveFast()不会崩溃？因为一次saveFast()所占用的内存并不高，而每次saveFast()执行完之后都会自动释放所占用的内存。但saveAll()不一样，saveAll()是在内部进行循环的，也就是要执行完10w次存储操作之后才会释放内存，这样就会把10w条数据全部一次性读到内存中，再加上你本来应用程序所占用的内存，就很容易OOM了。

建议解决方案：
1. 分段。你的分段方式就是对的，如果分成1000组的话，每组也就只有100条数据左右，这种情况不太可能还会OOM了。
2.给你的应用程序申请largeHeap，在AndroidManifest.xml里面加上下面的属性：
```xml
<application
    android:name="org.litepal.litepalsample.MyApplication"
    android:icon="@drawable/logo"
    android:label="@string/app_name"
    android:theme="@style/AppTheme"
    android:largeHeap="true">
</application>
```
这可以增大你的应用程序的可用内存。

另外，尽量换个好点的手机来操作一下，10w条数据在手机端操作确实不是一件轻量的工作。

**Comment by gundumw100** [comment]
正在考虑优化List<Product> products=new ArrayList<Product>();不让数据一次性加载到内存。

**Comment by gundumw100** [comment]
楼上正解！：）
