### ISSUE TITLE
Integer fields errors

### ISSUE THREAD

**Issue by PPPan** [LitePalFramework/LitePal#14]
When model has Integer fields,   "DataSupport.find()" will got this error:
E/AndroidRuntime(24722): Caused by: org.litepal.exceptions.DataSupportException: getInteger

**Comment by PPPan** [comment]
Solved !  I've modified the "DataHandler.java" , in the method "genGetColumnMethod" , added this codes:  

} else if ("getInteger".equals(methodName)) {
		    methodName = "getInt";
}

**Comment by sinyu890807** [comment]
Thanks for that. It's obviously a bug of LitePal. I will fix it in the next version. Good of that you fix it by yourself.

**Comment by sinyu890807** [comment]
Fixed in 1.2.0 version.
