### ISSUE TITLE
关于“多对一”关系的创建？

### ISSUE THREAD

**Issue by animus198656** [LitePalFramework/LitePal#144]
在示例Demo中，为了建立Song和Album的“多对一”关系，在Album中声明了变量“private List<Song> songs”，同时，在Song中声明了变量“private Album album”。
但是，我尝试把Song中的“private Album album”删除掉，在数据库的song表中同样生成了album_id外键列，这是不是表示，不用在Song中声明“private Album album”，也可以建立Song和Album的多对一关系？

**Comment by guolindev** [comment]
是的，Album声明了变量“private List songs”，不就已经表示Album中包含了多个songs了么，这就是多对一的关系，双向声明只是为了让你在Song中可以得到Album，你即使删掉了这句声明，也不会影响他们之间多对一的关系，只不过这样就只能知道Album中有哪些songs，但是无法知道这个Song是属于哪个Albums的了。
