### ISSUE TITLE
其他数据操作正常，外键为null

### ISSUE THREAD

**Issue by coder-luhao** [LitePalFramework/LitePal#147]
A表更新表后删除B表数据，然后把新数据写入B表，a_id为外键。现在在for循环中打印外键值a.getId()为空，请问改如何解决这个问题？代码步骤如下：
> A a = new A(str);
a.update(id);
DataSupport.deleteAll(B.class, "a_id = ?", String.valueOf(id));
List<B> bs=...;
for (int i = 0; i < bs .size(); i++){
    B b = bs.get(i);
    b.setA(a);
    b.save();
}

**Comment by guolindev** [comment]
你这伪代码写得有点太抽象，而且和你的描述对不上。你在for循环里面怎么打印外健值a.getId()的？，直接就调用a.getId()？你那个a对象从上面来看可是new出来的，只调用了一个update方法，没有经过save或者find，它怎么可能会有id值。至少我从你上面的描述只能这样理解，如果你表达的不是这个意思，请把描述补充清楚一些。
