### ISSUE TITLE
删除数据库后执行CRUD操作发现数据库又重新创建了

### ISSUE THREAD

**Issue by DysaniazzZ** [LitePalFramework/LitePal#149]
Rt，使用`LitePal.deleteDatabase(DB_NAME);`删除数据库后，进入目录发现数据库的确是被删除掉了，整个文件都没了。但是下次再执行CRUD操作，比如查找操作：`Album album = DataSupport.find(Album.class, 1);`，
发现数据库又重新重建了，只是里面没有数据。看了下源码，发现里面是调用了`Connector.getDatabase()`，间接地创建了数据库。不知道这算不算一个问题。

**Comment by guolindev** [comment]
不是问题，数据库本来就会在你进行任意一个数据库操作的时候自动创建，你去调用了find方法，内部就会自动帮你创建数据库，里面没有数据也是正常的，因为你并没有存储数据进去。

**Comment by SJLBenjamin** [comment]
老哥  我删除数据库的时候提示数据库删除失败  请问有什么好的解决办法吗
        Log.d("123","删除结果==="+LitePal.deleteDatabase("1"));
2019-12-30 10:35:01.360 18765-18765/com.edc.litepaldemo D/123: 删除结果===false
