### ISSUE TITLE
在android 6.0的系统上出现了很多anr问题（线程死锁)）

### ISSUE THREAD

**Issue by ningxz** [LitePalFramework/LitePal#151]
"main" prio=5 tid=1 Blocked | group="main" sCount=1 dsCount=0 obj=0x75dc15c0 self=0x7fa597c400 | sysTid=8023 nice=0 cgrp=default sched=0/0 handle=0x7fa97e72c0 | state=S schedstat=( 660543004 37048770 576 ) utm=54 stm=12 core=4 HZ=100 | stack=0x7fd9b55000-0x7fd9b57000 stackSize=8MB | held mutexes= at java.lang.Class.classForName!(Native method) - waiting to lock <0x0867bb3c> (a java.lang.Class<com.ningxz.feedback.entity.DataSupportBase>) held by thread 29 at java.lang.Class.forName(Class.java:324) at java.lang.Class.forName(Class.java:285) at org.litepal.LitePalBase.getSupportedFields(SourceFile:170) at org.litepal.crud.DataHandler.query(SourceFile:121) at org.litepal.crud.QueryHandler.onFindAll(SourceFile:122) at org.litepal.crud.DataSupport.findAll(SourceFile:629) - locked <0x0b9f30c5> (a java.lang.Class<org.litepal.crud.DataSupport>) at org.litepal.crud.DataSupport.findAll(SourceFile:610) - locked <0x0b9f30c5> (a java.lang.Class<org.litepal.crud.DataSupport>)

"RxNewThreadScheduler-2" daemon prio=5 tid=29 Blocked | group="main" sCount=1 dsCount=0 obj=0x12ef4460 self=0x7f9e65ca00 | sysTid=8103 nice=0 cgrp=default sched=0/0 handle=0x7f8c15f440 | state=S schedstat=( 40992455 717000 56 ) utm=4 stm=0 core=4 HZ=100 | stack=0x7f8c05d000-0x7f8c05f000 stackSize=1037KB | held mutexes= at java.lang.reflect.Constructor.newInstance!(Native method) - waiting to lock <0x0b9f30c5> (a java.lang.Class<org.litepal.crud.DataSupport>) held by thread 1 at com.google.gson.internal.ConstructorConstructor$3.construct(SourceFile:108) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:210) at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(SourceFile:41) at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(SourceFile:82) at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(SourceFile:61) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(SourceFile:129) at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:220) at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:37) at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:25) at retrofit2.ServiceMethod.toResponse(SourceFile:117) at retrofit2.OkHttpCall.parseResponse(SourceFile:211) at retrofit2.OkHttpCall.execute(SourceFile:174) at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(SourceFile:171) at c.j.setProducer(SourceFile:211) at c.d.a.i$a.setProducer(SourceFile:102) at c.d.a.f$a.setProducer(SourceFile:104) at c.j.setProducer(SourceFile:205) at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(SourceFile:152) at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(SourceFile:138) at c.d.a.h.a(SourceFile:48) at c.d.a.h.call(SourceFile:30) at c.d.a(SourceFile:10142) at c.d.a.f.a(SourceFile:45) at c.d.a.f.call(SourceFile:30) at c.d.a(SourceFile:10142) at c.d.a.i.a(SourceFile:48) at c.d.a.i.call(SourceFile:33) at c.d.a.h.a(SourceFile:48) at c.d.a.h.call(SourceFile:30) at c.d.a(SourceFile:10142) at c.d.a.e.a(SourceFile:41) at c.d.a.e.call(SourceFile:30) at c.d.a(SourceFile:10142) at c.d.a.p$1.call(SourceFile:94) at c.d.c.f.run(SourceFile:55) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) at java.util.concurrent.FutureTask.run(FutureTask.java:237) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) at java.lang.Thread.run(Thread.java:818)

**Comment by guolindev** [comment]
从这些日志看不太出来什么问题，但可以肯定的是，这和系统是无关的。从日志上看，你使用了retrofit，gson等库，然后因为什么操作导致线程被抢，然后litepal永远运行不了，我还没遇到过这种现象，建议你还是从代码上面分析一下原因。

**Comment by kmfish** [comment]
#101 都是一个问题
