### ISSUE TITLE
父类的int型成员变量 在update时会被忽略

### ISSUE THREAD

**Issue by aiguanglin** [LitePalFramework/LitePal#153]
![image](https://cloud.githubusercontent.com/assets/5866676/22682024/772e98d2-ed4b-11e6-8990-4d6ade4dd822.png)
![image](https://cloud.githubusercontent.com/assets/5866676/22682036/8e099098-ed4b-11e6-8db7-135d538a14d1.png)

**Comment by aiguanglin** [comment]
看了下代码是int类型的 更新为0时被判定为默认值会被忽略
![image](https://cloud.githubusercontent.com/assets/5866676/22684674/544c89c0-ed58-11e6-9f3d-b25a4b2919e1.png)

**Comment by guolindev** [comment]
重复问题，参考这里 https://github.com/LitePalFramework/LitePal/issues/32
