### ISSUE TITLE
关于存储集合对象，为什么插入不了数据，

### ISSUE THREAD

**Issue by flyjiang2014** [LitePalFramework/LitePal#155]
public class SignalReturnData extends DataSupport {
    private int more;
    private int page;
    private List < ProductBean > items = new ArrayList < ProductBean > ();
    private List<  String  > list = new ArrayList<>();

我这样定义类， 为什么more，page,list 都能插进数据库，items 却插入不了（items 是有数据的）。

是我哪里理解的不对吗，望帮忙看下，多谢！

查询方法我是这样写的。

 SignalReturnData signalReturnData = DataSupport.findFirst(SignalReturnData.class);

                                Log.e("jiang","size="+signalReturnData.getList().size());
                                Log.e("jiang","size01="+signalReturnData.getItems().size());

第一条打印size=3;
第二条打印size=0;

用的是1.41版本，litepal.xml文件相关类已配置好，ProductBean也继承了DataSupport

**Comment by guolindev** [comment]
你这种情况是表关联，表关联的用法参考这篇文章：http://blog.csdn.net/guolin_blog/article/details/39207945

另外，LitePal是没有级联存储的，如果你想把关联表的数据也进行存储，那么关联的model也要进行save才行。存储的用法参考这篇文章：http://blog.csdn.net/guolin_blog/article/details/39345833

查询的时候LitePal默认不会查询关联表中的数据，如果需要的话你要进行激进查询才行，查询的用法参考这篇文章：http://blog.csdn.net/guolin_blog/article/details/40153833
