### ISSUE TITLE
How can I create more than one database in an application?

### ISSUE THREAD

**Issue by Wu-Dongxia** [LitePalFramework/LitePal#156]
Since you definde XML format like this
![qq 20170217193104](https://cloud.githubusercontent.com/assets/19343193/23063857/b30a509a-f547-11e6-94fe-cce8bc710ee0.png)
So if I want to create more than one database in an application,how can I do that?

**Comment by guolindev** [comment]
You can only define one database in the litepal.xml. Multi databases is supported since LitePal 1.4.0. Not created in the configuration file, but in the codes. Read the doc for more details https://github.com/LitePalFramework/LitePal#7-multiple-databases
