### ISSUE TITLE
您好，请问LitePal能取出SQL Query吗？

### ISSUE THREAD

**Issue by VolpiS** [LitePalFramework/LitePal#159]
您好，
因目前有一功能，希望将SQL历程纪录下来，
但使用LitePal指令时好像不会看到该动作的Query，
会直接输出执行结果，
想请问有办法获得该指令的SQL Query吗？
谢谢您。

EX：

LitePal：
	DataSupport.where("c1=111").find(test.class);

Get SQL Query：
	SELETE * FROM test WHERE c1=111;

LitePal：
	test t = new test();
	t.setC1(111);
	t.setC2(222);
	t.setC3(333);
	t.save();

Get SQL Query：
	INSERT INTO test (c1,c2,c3) VALUES (111,222,333);

**Comment by guolindev** [comment]
这个功能暂时还不支持，因为litepal的底层也不是使用的SQL，而是在SQLitedatabase的基础之上进行的封装，所以LitePal实际上并没有通过SQL语句进行查询，也就不好打印SQL语句了。
