### ISSUE TITLE
bollen field set(false) then updateAll() seems does not work.

### ISSUE THREAD

**Issue by likaci** [LitePalFramework/LitePal#16]
A class User has a **private field bollen isLastUse** and two method **setLastUse() isLastUse()**
----------------------------------------
User user = new User();
user.setLastUse(**true**);
user.updateAll();
-----this above codes effect-----

user.setLastUes(**false**);
user.upadteAll();
-------has no effect-------

**Comment by sinyu890807** [comment]
Well. It is not a bug. Using instance method of update() could not change the value into default, and ´false´ is the default value of boolean. You can do it by calling user.setToDefault(¨isLastUser¨)

**Comment by likaci** [comment]
thanks, problem solved.
