### ISSUE TITLE
支持内部类嘛？

### ISSUE THREAD

**Issue by Longalei** [LitePalFramework/LitePal#160]
研究了一下LitePal,貌似不支持内部类的定义。而是需要通过几个单一类进行关联。这样的话数据解析类与数据库定义模型类就会相互冗余。有人也遇到过这样的问题嘛？

**Comment by guolindev** [comment]
LitePal是完全支持内部类的，你可以试一下。

**Comment by huhuang03** [comment]
请问内部类的写法是com.xx.A$B吗。目前测试好像不行。
