### ISSUE TITLE
Can't save relationship's changes while updating a model

### ISSUE THREAD

**Issue by rieonke** [LitePalFramework/LitePal#162]
Hello,
Recently I got a problem while updating a model with LitePal;
Such as a simple On-To-Many relationship , a Person has many Dogs.
While calling `person.save()` , It went well , the `person.dogs` were saved;
but while updating  person with `person.update()` after the `person.dogs` have been changed,
but the `Dog` 's table got NOTHING changed!
Is't my mistake or a bug?
Thanks~

**Comment by guolindev** [comment]
You misunderstanding the usage of update() method. In your situation, just use person.save() again will get everything correct. 
Check the document here for update records. First instance.
https://github.com/LitePalFramework/LitePal#4-update-data

**Comment by rieonke** [comment]
Thanks！
