### ISSUE TITLE
多线程使用多数据库会与问题吗

### ISSUE THREAD

**Issue by luxy25** [LitePalFramework/LitePal#163]
比如：线程一：
LitePalDB singerlDB = new LitePalDB("singer", 1);
singerlDB.addClassName(Singer.class.getName());
LitePal.use(singerlDB);
//一些耗时操作
Singer singer = DataSupport.find(Singer.class, id);

线程二：
LitePalDB songDB = new LitePalDB("song", 1);
songDB.addClassName(Song.class.getName());
LitePal.use(songDB);

Song song = DataSupport.find(Song.class, id);

如果有这两个异步线程，线程一执行到指定了LitePal用singerDB，然后耗时，结果线程二执行指定了LitePal用songDB，这时候线程一再去查Singer.class实体能查的到吗

**Comment by guolindev** [comment]
不能，数据库是不支持并发的，你一个线程在操作数据库时，数据库就被上锁了，另外一个线程就只能等待。开多线程可以让你的数据库操作不影响UI界面，但是不支持让两个线程同时去操作数据库。

**Comment by luxy25** [comment]
我是想让两个线程操作两个数据库，
