### ISSUE TITLE
利用注解指定主键

### ISSUE THREAD

**Issue by hanshengjian** [LitePalFramework/LitePal#165]
郭婶，我觉得可以用注解来指定主键或者一些唯一或者非空的约束

**Comment by guolindev** [comment]
现在支持使用注解来指定 唯一，非空，默认值这些约束，还支持使用注解忽略映射某一列，具体参考这里 https://github.com/LitePalFramework/LitePal/blob/master/litepal/src/main/java/org/litepal/annotation/Column.java。
但是不支持指定主键，因为主键这个太特殊了，litepal整个工作的机制都依赖在主键上，这个不能随便改。
