### ISSUE TITLE
how to set grouped privatekey

### ISSUE THREAD

**Issue by SwiftyWang** [LitePalFramework/LitePal#169]
such as there are two field are privatekey, how to create the DataClass? thank you.

**Comment by guolindev** [comment]
Sorry. Don't understand what you mean. Can you give some more descriptions?

**Comment by huangying812** [comment]
private access class field?

**Comment by SwiftyWang** [comment]
such as I have a table named student_couse_score has (student_id, couse_id, score) three columns and I want to set primary is (student_id,couse_id); how to create the student_couse_score class.
