### ISSUE TITLE
LitePalApplication 这个必须继承有点难为人啊

### ISSUE THREAD

**Issue by ownwell** [LitePalFramework/LitePal#17]
LitePalApplication中
  
'''public static Context getContext() {
		if (mContext == null) {
			throw new GlobalException(GlobalException.APPLICATION_CONTEXT_IS_NULL);
		}
		return mContext;
	}

	@Override
	public void onLowMemory() {
		super.onLowMemory();
		mContext = getApplicationContext();
	}'''
就这一个功能还要用一个Application，太浪费了。
为嘛不要自己去set呢

**Comment by ownwell** [comment]
public class LitePalContext {
    
    private static LitePalContext mInstance = null;
    
    private Context mContext;
    
    public static LitePalContext getInstance() {
        if (mInstance == null) {
            synchronized (LitePalContext.class) {
                if (mInstance == null) {
                    mInstance = new LitePalContext();
                }
            }
        }
        return mInstance;
    }

    public Context getContext() {
        return mContext;
    }

    public void setContext(Context _context) {
        mContext = _context;
    }
}

**Comment by ownwell** [comment]
这个要求使用者必须去se在Application的oncreate和onlowMermory下调用 why not？？

**Comment by zhounanzhao** [comment]
由于操作数据库时需要用到Context，而我们显然不希望在每个接口中都去传一遍这个参数，那样操作数据库就显得太繁琐了。因此，LitePal使用了一个方法来简化掉Context这个参数，只需要在AndroidManifest.xml中配置一下LitePalApplication，所有的数据库操作就都不用再传Context了。
内容来自http://blog.csdn.net/luohai859/article/details/39292607
这个应该可以解释吧。

**Comment by ownwell** [comment]
@zhounanzhao  那也必要你占用Application这个重要的类吧。
我刚才写的那个类 set一个application的context不就可以么

**Comment by ownwell** [comment]
hope the owner will respone。

**Comment by song314** [comment]
@ownwell 那谈谈你觉得占用了application会带来什么问题和影响？

**Comment by sinyu890807** [comment]
Fixed in 1.2.1
