### ISSUE TITLE
查询findFirst（）方法 报错 boolean  .java.util.collection.add(java.lang.object) : on a  null object  refrence 错误

### ISSUE THREAD

**Issue by Knowledgeables** [LitePalFramework/LitePal#170]
litepal 1.5.0中 ：查询findFirst（）方法 报错 boolean  .java.util.collection.add(java.lang.object) : on a  null object  refrence 错误

数据格式 ：对象 中嵌套list   @guolindev

**Comment by guolindev** [comment]
此bug已在1.5.1版本中修复，升级即可解决。
