### ISSUE TITLE
表中只有一条数据，我想更新掉，发现数据不变

### ISSUE THREAD

**Issue by gydhy8** [LitePalFramework/LitePal#172]
数据model 如下
class Community extends DataSupport{
      private int     CommunityID;   //社区ID
    private String  CommunityName; //社区名称
    private int     CityID;        //城市ID
    private String  CityName;      //城市名称
    private int     DistrictID;    //县/区ID
    private String  DistrictName;  //县/区名称
    private int     SupplierID;    //供应商ID
    private String  SupplierName;  //供应商名称
    private int     DCID;          //配送中心ID
    private String  DCName;        //配送中心名称
    private String  Address;       //社区地址
    private boolean IsEnable;      //是否启用
    private String  Memo;          //备注
}

获取Community的一个实例community后，调用community.update(0)，表中存的内容没有发生变化，不知何故

**Comment by guolindev** [comment]
你调用update(0)干啥呀，这个是更新对应id的记录的，数据库里面不会有id是0的记录。
你还是看一下文档里面关于更新那部分的用法吧。

**Comment by gydhy8** [comment]
哦了，当成id从0开始的了，现在有个业务需求：表中只存一条数据，根据情况更新这条数据，类似切换城市，DataSupport.isExist()方法和saveOrUpdate方法似乎无法满足，因为不用关心满足条件，只要有记录存在就更新掉，没记录存在就save，我目前的解决方法：
Community newCommunity;//新的实例已经获取
Community oldCommunity = DataSupport.findFirst(Community.class);
if( oldCommunity != null){
    newCommunity.update(1);
}else{
   newCommunity.save();
}

不知是否有更好的方式实现该逻辑需求

**Comment by guolindev** [comment]
你这个就是最标准的方法了，不过上面的update语句不要那么写，因为id不能保证一定是1的，而是要用查询出来的id，这种写法：newCommunity.getId()。
