### ISSUE TITLE
无法直接存储Bean类里面含有集合字段的

### ISSUE THREAD

**Issue by jianfeng318** [LitePalFramework/LitePal#176]
此版本无法直接存储bean类里面含有List集合字段的,需要进行多表关联后分别存储和查询,希望郭神封装一下

**Comment by guolindev** [comment]
不是很明白，你能再详细描述下吗

**Comment by jianfeng318** [comment]
![image](https://cloud.githubusercontent.com/assets/24287998/24087965/01284c48-0d60-11e7-95a1-0508125a6536.png)
这是一个bean,里面还有List集合,这样的存储是需要关联外键,而且三个集合bean是需要单独存储的

**Comment by liuyuttkx** [comment]
能添加这种功能吗?
在一个bean里面,有其它表的数据, 在保存的时候,需要从这个bean数据中取到其它Bean的数据,先保存它们的值,再执行bean.save();这样才能保存所有数据.
如上图,保存该bean的数据, 需要取到ima, link, rel 字段的值,保存后, 再保存bean.
DataSuport.saveAll(bean.getIma());
DataSuport.saveAll(bean.getLink());
DataSuport.saveAll(bean.getRel());
bean.save();

请问: 是否可以添加这种功能, 仅执行bean.save()就将它里面所有的数据全部保存;
在取数据时同理, 现在为了取到该bean的全部数据,需要通过bean_id = ? 的条件来查询, 是否可以增加功能, 
DataSuport.findAll(bean.getClass()); 就能查到对应的所有数据;
谢谢!!!

**Comment by liuyuttkx** [comment]
郭神: 
      请问是否可以 先拿到bean中的所有字段, 凡是DadaSuoprt子类,且是private修饰, 然后通过反射,拿到对应字段的值,将它会先进行保存, 最后保存该bean的值. 这样实现 bean.save(); 就保存了bean中所有数据;

**Comment by guolindev** [comment]
这个功能LitePal本身就是支持的，数据库层的实现就是使用关联表，而关联表的就是使用外键来实现的。
然后是级联存储的问题，我在设计litepal的时候就摒弃了级联存储这个功能，因为我觉得这会增加使用者的理解成本，有时候没有想存的对象就莫名其妙自动被存进去了。现在litepal的机制就是你想存什么东西，都要自己去save才会保存，如果它们之间有关联关系，litepal在这些数据保存之后会自动建议关联，但是litepal不会去做级连存储。
