### ISSUE TITLE
数据保存不了

### ISSUE THREAD

**Issue by jameschou51** [LitePalFramework/LitePal#177]
举例，表中含有1.2.3，三个元素，list中包含了1.2.3.4.5.6，在deleteAll后，saveAll这个list，表中只有4.5.6，又没有遇到相同情况的？？？

**Comment by gydhy8** [comment]
我遇到了类似的情况，deleteAll后再添加会添加不进去了，重启应用后有时候可以添加了，有时候还是无法添加，希望郭神重视下这个问题，我用的是最新版1.5.0

**Comment by guolindev** [comment]
重复问题，参考一下这两个close的issue。https://github.com/LitePalFramework/LitePal/issues/133 https://github.com/LitePalFramework/LitePal/issues/178
clearSavedState()是清除单个对象的存储状态，markAsDeleted()是清除对象集合的存储状态。
