### ISSUE TITLE
deleteAll后数据无法添加

### ISSUE THREAD

**Issue by gydhy8** [LitePalFramework/LitePal#178]
业务场景：
购物车有数据清空，调用deleteAll，此时调用count，返回0，没问题，返回商品列表再添加，调用save方法，返回true，但是购物车页面findAll时，却没有数据

另外：
1.购物车有了某个商品，再次save时，我希望把数量加上去，现在的情况是，再次save时返回true，但是购物车列表数量没有变，并没有再次生成一条新纪录，litepal 同一条数据多次save时是怎么区别是不是同一条数据的？
2.litepal 对Date 字段比较时，比如返回某天之后的数据，condition参数怎么写呢？

我使用的是1.5.0版

**Comment by jameschou51** [comment]
我遇到与你相同的问题，deleteAll再saveAll时，之前delete的数据不会保存进去，但是issave返回的是teue，你有没有解决啊？？？？

**Comment by androidZhai** [comment]
同样遇到这个问题，deleteAll之后就不能再save了

**Comment by guolindev** [comment]
楼上正解，这个问题关掉了。
