### ISSUE TITLE
Android Studio debug模式下NoClassDefFoundError异常

### ISSUE THREAD

**Issue by Yieron** [LitePalFramework/LitePal#179]
Android Studio在升级到2.3.0后debug模式下NoClassDefFoundError，在没升级之前一切正常，近期在debug模式下java.lang.NoClassDefFoundError: org.litepal.crud.ClusterQuery

    public static synchronized Account getCurrentAccount() {
        List<Account> accountList = DataSupport.where("current_login = ? ", "1").find(Account.class);  //这行代码报错，at org.litepal.crud.DataSupport.where(DataSupport.java:159) 报NoClassDefFoundError
        if (accountList != null && accountList.size() > 0) {
            return accountList.get(0);
        } else {
            return null;
        }
    }

**Comment by DDstar** [comment]
同求~在OPPO手机下一只是这个错

**Comment by guolindev** [comment]
这个问题我也不知道，我还没有遇到过呢，但是这个应该还是项目环境的问题，不是litepal代码的问题，这个issue我先关掉了。

**Comment by zhuanghm** [comment]
问题描述：
我在编译的环境下也出现了java.lang.NoClassDefFoundError: org.litepal.LitePalDB异常，不过该类异常只在Android 5.0以下和虚拟机中会报出（亲测靠谱助手虚拟机和OPPO R829T必现），后来发现可能是Android4.4以下没有直接支持(multidex)方法数超出的问题导致;
解决方案：
1.再build.gradle 中添加依赖 compile 'com.android.support:multidex:1.0.1'；
2.并在BaseApplication中添加    MultiDex.install(this);初始化；
即解决了该问题.
