### ISSUE TITLE
数据库的名必须固定

### ISSUE THREAD

**Issue by ownwell** [LitePalFramework/LitePal#18]
数据库的名是固定的，这个有点坑吧。
建议：
  像QQ那种，不同用户应该有对应的user信息 、friends、groups。

  QQ-steven.DB 
      user    ------mapping class ----- user
     friends ------mapping class ----- friends
     groups------mapping class ----- groups
QQ-cyning.DB
     user    ------mapping class ----- user
     friends ------mapping class ----- friends
     groups------mapping class ----- groups

**Comment by song314** [comment]
好建议，你可以改进然后发一个pull request

**Comment by zeng1990java** [comment]
yahoo最新开源的数据库框架squidb就可以很好的实现根据不同的登陆用户使用不同的数据库名称

**Comment by 328629033** [comment]
同感

**Comment by ybADMIN** [comment]
那个建议很不错

**Comment by AnyLifeZLB** [comment]
我也更倾向于使用不同用户的账号来保存一个数据库，以前用过ＯＲＭＬＩＴＥ的时候是这样做的，但那个的升级不好做。

**Comment by guolindev** [comment]
从1.4.0版本开始已经支持创建多数据库了，具体用法请参考文档。
