### ISSUE TITLE
华为P8 open database failed 

### ISSUE THREAD

**Issue by shuimuqinghua** [LitePalFramework/LitePal#180]
项目中使用到了LitePal，version1.3.2（试过1.5.2也不行）。
litepal.xml中，存储配置<storage value="external" />，其他配置跟demo一致，运行后，其他手机正常，就华为P8会出现 open database failed 的错，在对应路径下，也找不到db文件。
然后修改为<storage value="internal"/>,华为P8能正常运行。
请问下，有没有仙友道友遇到过这个问题？

**Comment by guolindev** [comment]
我没有华为p8手机，这个问题还真没办法测试，你现在那边有解决这个问题吗？解决了可以回来反馈一下。

**Comment by shuimuqinghua** [comment]
我试过将storage改为internal后，就没发现有这个问题了。

**Comment by guolindev** [comment]
我之前是发现有些华为手机的sd卡有问题，它的路径使用Environment.getExternalStorageDirectory()的方式获取不到，使用/sdcard这种硬编码的方式却可以获取到。不过这是属于手机bug，应该由华为去解决。而且数据库不要创建在sd卡，这个只供你调试的时候使用。
