### ISSUE TITLE
整型的bug，int的值无法改为0，但可以改为其他

### ISSUE THREAD

**Issue by wenboLee** [LitePalFramework/LitePal#181]
**贼奇怪，以下是日志输出，是不是我姿势不对。**
查询 song Song{id=10, age=59}
song 变零 Song{id=10, age=0} update 0
查询 size 1
查询 song Song{id=10, age=59}
song 变99 Song{id=10, age=99} update 1
变 99 后查询 song1 Song{id=10, age=99}
查询 size 1
查询 song Song{id=10, age=99}
**不要跟我说，你也很绝望。**

**Comment by FJCDrome** [comment]
我也遇到了类似的问题，Integer和String等类型不能从非空改成null，我也很绝望。

**Comment by guolindev** [comment]
重复问题 https://github.com/LitePalFramework/LitePal/issues/32
