### ISSUE TITLE
数据库数据丢失

### ISSUE THREAD

**Issue by yaogoodgoodde** [LitePalFramework/LitePal#182]
我录制视频前，保存了一条数据库记录，已经可以查询保存上了，但是接下来如果遇到了录制崩溃或者立马adb reboot机器，再次打开机器，会发现刚保存的这条数据库记录没有了

**Comment by yaogoodgoodde** [comment]
解决了，后来发现我的一个同事默默在角落里写的删除数据库的代码。

**Comment by moshangqianye** [comment]
我把数据库从assert目录下复制一份到手机的目录里，其他手机都是能正常读取数据库，但是荣耀10手机却读取不到，读的条数是0条，Android系统是9.0的系统
