### ISSUE TITLE
 Caused by: org.litepal.exceptions.DataSupportException: id type is not supported. Only int or long is acceptable for id

### ISSUE THREAD

**Issue by androidVHappy** [LitePalFramework/LitePal#184]
id类型只能是int和long类型？  不支持String类型吗  ？郭神

**Comment by guolindev** [comment]
是的，不支持的，你不要尝试去定义string类型的id，如果这个id是服务器返回给你的，那你可以把它重命名成另一个字段名，比如说serverId，这个serverId是专门给服务器使用的，和客户端的id没有关系。
