### ISSUE TITLE
LitePal会为类型为int，名为id的字段自动赋值autoincrement吗？

### ISSUE THREAD

**Issue by WindFromFarEast** [LitePalFramework/LitePal#188]
看书上发现郭老师并没有为id设置为autoincrement，但是在创建表后这个字段自动被赋与autoincrement了并且也被设置为主键了

**Comment by gxcgxc** [comment]
id integer primary key autoincrement,郭的sqlite 已经默认实现了

**Comment by sinyu890807** [comment]
楼上正解
