### ISSUE TITLE
多数据库的改进点

### ISSUE THREAD

**Issue by Ellio007** [LitePalFramework/LitePal#191]
郭神，你好！
我最近在使用Litepal的多数据库功能，感觉该功能非常的棒！
能帮我们解决多个用户登陆数据存储的问题。
但是我发现没有提供使用之前已经创建数据库的api：
比如我用A登陆了，生成了一个数据库命名为A，这个时候退出登陆，用B登陆成功后，再次用A登陆，这个时候我认为是切换回A创建的那个数据库。但是在Litepal这个类并没有提供根据数据库名称来使用数据库的相关方法。所以我建议下个版本郭神可以采纳我的建议，小的不胜感激！
或者如果有其他的api也请告知小的如何实现该功能

**Comment by sinyu890807** [comment]
我没太看明白你的意思，你的数据库名如果是A，那么切换到A数据库就是 LitePal.use("A")，切换到B就是LitePal.use("B")，再切回到A的话还是调用LitePal.use("A")就可以了，这不能实现你的需求吗？

**Comment by Ellio007** [comment]
然而并没有相关的方法，LitePal.use("B") 方法只有 LitePalDB这个参数的，而并没有提供根据数据库名切换的方法吧？

**Comment by guolindev** [comment]
哦，原来你是这个疑问，那就简单了，你只需要调用LitePalDB.fromDefault("数据库名") 这个方法来创建一个LitePalDB对象，再传到LitePal.use()方法里面就可以了。

**Comment by Ellio007** [comment]
这样可以实现切换回A并且A里的数据不会被删么？我看了下源码貌似LitePalDB.fromDefault("数据库名") 这个方法是重新创建一个数据库对象吧？
