### ISSUE TITLE
关于表的修改问题

### ISSUE THREAD

**Issue by dicallc** [LitePalFramework/LitePal#192]
订单表里面一对一的关系，如：下单地址(Point),节点地址(Point)  point也是一张表

之后快递员表与订单表建立多对一关系，修改快递员表中的数据后，订单表中的一对一数据全部为空。。。

也就是下单地址(Point),节点地址(Point)变成了空，求解这是为什么

补充：
SailManUser -->List<OrderModel> 
修改用的是save()，同时我觉得建立好多对一关系后，在快递员中订单列表中添加表订单应该是updata，没想到只能用save，才能成功。

辛苦作者的维护了。

**Comment by guolindev** [comment]
你的两个表怎么都叫Point，那实际上就是一张表了。现在litepal不支持建议自引用关联，主要是客户端其实也没这么复杂的逻辑。
