### ISSUE TITLE
默认数据库名后缀  .db怎么去除，怎么将表名修改成大写的，可以打开已有的数据库吗

### ISSUE THREAD

**Issue by zbldgit** [LitePalFramework/LitePal#197]

**Comment by guolindev** [comment]
1. 默认后缀没法去除。
2. 表名可以改成大写的，但没法单独改成大写的，你在litepal.xml里在配置一句<cases value="upper" ></cases>，那么表名、列名、还有SQL语句都会变成大写。
3. 不支持打开已有数据库，除非这个数据库本来就是用litepal创建的。
