### ISSUE TITLE
存储比较多的数据时，崩溃，然后log也不知道是哪行崩溃

### ISSUE THREAD

**Issue by kllkko** [LitePalFramework/LitePal#198]
(1) Expression tree is too large (maximum depth 1000)
04-24 19:28:42.047: E/AndroidRuntime(19356): FATAL EXCEPTION: main
04-24 19:28:42.047: E/AndroidRuntime(19356): Process: com.dmsys.nas, PID: 19356
04-24 19:28:42.047: E/AndroidRuntime(19356): java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:112)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at android.os.Handler.handleCallback(Handler.java:739)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at android.os.Looper.loop(Looper.java:148)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at android.app.ActivityThread.main(ActivityThread.java:5438)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at java.lang.reflect.Method.invoke(Native Method)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
04-24 19:28:42.047: E/AndroidRuntime(19356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
04-24 19:28:42.047: E/AndroidRuntime(19356): Caused by: rx.exceptions.OnErrorNotImplementedException: Expression tree is too large (maximum depth 1000) (code 1): , while compiling: UPDATE dmsubtask SET dmtask_id=? WHERE id = 18217 or id = 18412 or id = 18743 or id = 18057 or id = 17398 or id = 18303 or id = 18723 or id = 18121 or id = 18594 or id = 17926 or id = 18467 or id = 18488 or id = 17868 or id = 18422 or id = 17603 or id = 17380 or id = 18124 or id = 17849 or id = 18010 or id = 17547 or id = 18699 or id = 17785 or id = 18486 or id = 18232 or id = 17580 or id = 17283 or id = 17545 or id = 17698 or id = 18733 or id = 18231 or id = 18037 or id = 17639 or id = 17579 or id = 18333 or id = 18029 or id = 18447 or id = 18721 or id = 17572 or id = 18116 or id = 18316 or id = 17345 or id = 17883 or id = 18567 or id = 18414 or id = 18797 or id = 18012 or id = 18563 or id = 17640 or id = 18225 or id = 17813 or id = 18726 or id = 18697 or id = 18260 or id = 17853 or id = 17818 or id = 18050 or id = 18199 or id = 17377 or id = 18814 or id = 18203 or id = 18066 or id = 17925 or id = 17738 or id = 17425 or id = 17611 or id = 18490 or id = 17878 or id = 17537 or id = 17811 or id = 17511 or id = 17992 or id = 18577 or id = 17314 or id = 17475 or id = 18607 or id = 18420 or id = 18129 or id = 18241 or id = 17751 or id = 18581 or id = 17505 or id = 18757 or id = 18696 or id = 17399 or id = 18625 or id = 18218 or id = 18365 or id = 17606 or id = 18747 or id = 17363 or id = 18548 or id = 18342 or id = 17884 or id = 17899 or id = 17786 or id = 18009 or id = 17287 or id = 18390 or id = 18028 or id = 17745 or id = 17555 or id = 18249 or id = 17885 or id = 18580 or id = 18299 or id = 18449 or id = 17693 or id = 17438 or id = 17500 or id = 18056 or id = 17975 or id = 17781 or id = 18392 or id = 18085 or id = 18279 or id = 17774 or id = 18269 or id = 18018 or id = 17865 or id = 17772 or id = 17417 or id = 17860 or id = 17808 or id = 18227 or id = 17408 or id = 17478 or id = 17985 or id = 17990 or id = 17533 or id = 17913 or id = 18250 or id = 18011 or id = 17830 or id = 17799 or id = 17357 or id = 18650 or id = 18462 or id = 18079 or id = 17288 or id = 18181 or id = 17800 or id = 17510 or id = 17339 or id = 18257 or id = 18356 or id = 18132 or id = 17769 or id = 18601 or id = 17855 or id = 18830 or id = 18639 or id = 17331 or id = 17449 or id = 18024 or id = 17896 or id = 18439 or id = 17750 or id = 18705 or id = 17797 or id = 17428 or id = 18452 or id = 17790 or id = 17442 or id = 17414 or id = 18823 or id = 17405 or id = 18766 or id = 18633 or id = 18329 or id = 18460 or id = 17898 or id = 18619 or id = 17955 or id = 17783 or id = 17509 or id = 18136 or id = 18596 or id = 17997 or id = 18800 or id = 18361 or id = 17632 or id = 18730 or id = 17952 or id = 17347 or id = 17566 or id = 17317 or id = 17715 or id = 18052 or id = 18351 or id = 18141 or id = 18391 or id = 17957 or id = 17700 or id = 17953 or id = 18658 or id = 17514 or id = 17446 or id = 18531 or id = 18741 or id = 17940 or id = 17834 or id = 17319 or id = 17315 or id = 17530 or id = 18746 or id = 17328 or id = 17801 or id = 17733 or id = 17512 or id = 17356 or id = 18751 or id = 18702 or id = 17308 or id = 18457 or id = 18445 or id = 18514 or id = 18064 or id = 17396 or id = 17757 or id = 18637 or id = 17387 or id = 18522 or id = 17586 or id = 18113 or id = 17767 or id = 18044 or id = 17358 or id = 18586 or id = 18664 or id = 18576 or
04-24 19:28:42.054: D/Error(19356): ERR: exClass=android.database.sqlite.SQLiteException
04-24 19:28:42.055: D/Error(19356): ERR: exMsg=Expression tree is too large (maximum depth 1000) (code 1): , while compiling: UPDATE dmsubtask SET dmtask_id=? WHERE id = 18217 or id = 18412 or id = 18743 or id = 18057 or id = 17398 or id = 18303 or id = 18723 or id = 18121 or id = 18594 or id = 17926 or id = 18467 or id = 18488 or id = 17868 or id = 18422 or id = 17603 or id = 17380 or id = 18124 or id = 17849 or id = 18010 or id = 17547 or id = 18699 or id = 17785 or id = 18486 or id = 18232 or id = 17580 or id = 17283 or id = 17545 or id = 17698 or id = 18733 or id = 18231 or id = 18037 or id = 17639 or id = 17579 or id = 18333 or id = 18029 or id = 18447 or id = 18721 or id = 17572 or id = 18116 or id = 18316 or id = 17345 or id = 17883 or id = 18567 or id = 18414 or id = 18797 or id = 18012 or id = 18563 or id = 17640 or id = 18225 or id = 17813 or id = 18726 or id = 18697 or id = 18260 or id = 17853 or id = 17818 or id = 18050 or id = 18199 or id = 17377 or id = 18814 or id = 18203 or id = 18066 or id = 17925 or id = 17738 or id = 17425 or id = 17611 or id = 18490 or id = 17878 or id = 17537 or id = 17811 or id = 17511 or id = 17992 or id = 18577 or id = 17314 or id = 17475 or id = 18607 or id = 18420 or id = 18129 or id = 18241 or id = 17751 or id = 18581 or id = 17505 or id = 18757 or id = 18696 or id = 17399 or id = 18625 or id = 18218 or id = 18365 or id = 17606 or id = 18747 or id = 17363 or id = 18548 or id = 18342 or id = 17884 or id = 17899 or id = 17786 or id = 18009 or id = 17287 or id = 18390 or id = 18028 or id = 17745 or id = 17555 or id = 18249 or id = 17885 or id = 18580 or id = 18299 or id = 18449 or id = 17693 or id = 17438 or id = 17500 or id = 18056 or id = 17975 or id = 17781 or id = 18392 or id = 18085 or id = 18279 or id = 17774 or id = 18269 or id = 18018 or id = 17865 or id = 17772 or id = 17417 or id = 17860 or id = 17808 or id = 18227 or id = 17408 or id = 17478 or id = 17985 or id = 17990 or id = 17533 or id = 17913 or id = 18250 or id = 18011 or id = 17830 or id = 17799 or id = 17357 or id = 18650 or id = 18462 or id = 18079 or id = 17288 or id = 18181 or id = 17800 or id = 17510 or id = 17339 or id = 18257 or id = 18356 or id = 18132 or id = 17769 or id = 18601 or id = 17855 or id = 18830 or id = 18639 or id = 17331 or id = 17449 or id = 18024 or id = 17896 or id = 18439 or id = 17750 or id = 18705 or id = 17797 or id = 17428 or id = 18452 or id = 17790 or id = 17442 or id = 17414 or id = 18823 or id = 17405 or id = 18766 or id = 18633 or id = 18329 or id = 18460 or id = 17898 or id = 18619 or id = 17955 or id = 17783 or id = 17509 or id = 18136 or id = 18596 or id = 17997 or id = 18800 or id = 18361 or id = 17632 or id = 18730 or id = 17952 or id = 17347 or id = 17566 or id = 17317 or id = 17715 or id = 18052 or id = 18351 or id = 18141 or id = 18391 or id = 17957 or id = 17700 or id = 17953 or id = 18658 or id = 17514 or id = 17446 or id = 18531 or id = 18741 or id = 17940 or id = 17834 or id = 17319 or id = 17315 or id = 17530 or id = 18746 or id = 17328 or id = 17801 or id = 17733 or id = 17512 or id = 17356 or id = 18751 or id = 18702 or id = 17308 or id = 18457 or id = 18445 or id = 18514 or id = 18064 or id = 17396 or id = 17757 or id = 18637 or id = 17387 or id = 18522 or id = 17586 or id = 18113 or id = 17767 or id = 18044 or id = 17358 or id = 18586 or id = 18664 or id = 18576 or id = 18574 or id = 17966 or id = 18383 or id = 18154 or id = 17582 or id = 17451 or id = 17282 or id = 18805 or id = 18331 or id = 17570 or id = 18590 or id = 17934 or id = 17822 or id = 17823 or id = 18831 or id = 17828 or id = 17281 or id = 18438 or id = 17873 or id = 18789 or id = 18070 or id = 18150 or id = 17887 or id = 17943 or id = 18782 or id = 18609 or id = 18799 or id = 17624 or id = 18127 or id = 18771 or id = 17858 or id = 17677 or id = 18540 or id = 18185 or id = 17465 or id = 18727 or id = 18689 or id = 18725 or id = 17334 or id = 18458 or id = 17316 or id = 18598 or id = 18166 or id = 18046 or id = 17613 or id = 18578 or id = 17893 or id = 18527 or id = 18411 or id = 17647 or id = 17880 or id = 
04-24 19:28:42.055: D/Error(19356): ERR: file=SQLiteConnection.java
04-24 19:28:42.055: D/Error(19356): ERR: class=android.database.sqlite.SQLiteConnection
04-24 19:28:42.055: D/Error(19356): ERR: method=nativePrepareStatement line=-2
04-24 19:28:42.057: D/Error(19356): ERR: stack=java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
04-24 19:28:42.057: D/Error(19356): 	at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:112)
04-24 19:28:42.057: D/Error(19356): 	at android.os.Handler.handleCallback(Handler.java:739)
04-24 19:28:42.057: D/Error(19356): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-24 19:28:42.057: D/Error(19356): 	at android.os.Looper.loop(Looper.java:148)
04-24 19:28:42.057: D/Error(19356): 	at android.app.ActivityThread.main(ActivityThread.java:5438)
04-24 19:28:42.057: D/Error(19356): 	at java.lang.reflect.Method.invoke(Native Method)
04-24 19:28:42.057: D/Error(19356): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
04-24 19:28:42.057: D/Error(19356): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
04-24 19:28:42.057: D/Error(19356): Caused by: rx.exceptions.OnErrorNotImplementedException: Expression tree is too large (maximum depth 1000) (code 1): , while compiling: UPDATE dmsubtask SET dmtask_id=? WHERE id = 18217 or id = 18412 or id = 18743 or id = 18057 or id = 17398 or id = 18303 or id = 18723 or id = 18121 or id = 18594 or id = 17926 or id = 18467 or id = 18488 or id = 17868 or id = 18422 or id = 17603 or id = 17380 or id = 18124 or id = 17849 or id = 18010 or id = 17547 or id = 18699 or id = 17785 or id = 18486 or id = 18232 or id = 17580 or id = 17283 or id = 17545 or id = 17698 or id = 18733 or id = 18231 or id = 18037 or id = 17639 or id = 17579 or id = 18333 or id = 18029 or id = 18447 or id = 18721 or id = 17572 or id = 18116 or id = 18316 or id = 17345 or id = 17883 or id = 18567 or id = 18414 or id = 18797 or id = 18012 or id = 18563 or id = 17640 or id = 18225 or id = 17813 or id = 18726 or id = 18697 or id = 18260 or id = 17853 or id = 17818 or id = 18050 or id = 18199 or id = 17377 or id = 18814 or id = 18203 or id = 18066 or id = 17925 or id = 17738 or id = 17425 or id = 17611 or id = 18490 or id = 17878 or id = 17537 or id = 17811 or id = 17511 or id = 17992 or id = 18577 or id = 17314 or id = 17475 or id = 18607 or id = 18420 or id = 18129 or id = 18241 or id = 17751 or id = 18581 or id = 17505 or id = 18757 or id = 18696 or id = 17399 or id = 18625 or id = 18218 or id = 18365 or id = 17606 or id = 18747 or id = 17363 or id = 18548 or id = 18342 or id = 17884 or id = 17899 or id = 17786 or id = 18009 or id = 17287 or id = 18390 or id = 18028 or id = 17745 or id = 17555 or id = 18249 or id = 17885 or id = 18580 or id = 18299 or id = 18449 or id = 17693 or id = 17438 or id = 17500 or id = 18056 or id = 17975 or id = 17781 or id = 18392 or id = 18085 or id = 18279 or id = 17774 or id = 18269 or id = 18018 or id = 17865 or id = 17772 or id = 17417 or id = 17860 or id = 17808 or id = 18227 or id = 17408 or id = 17478 or id = 17985 or id = 17990 or id = 17533 or id = 17913 or id = 18250 or id = 18011 or id = 17830 or id = 17799 or id = 17357 or id = 18650 or id = 18462 or id = 18079 or id = 17288 or id = 18181 or id = 17800 or id = 17510 or id = 17339 or id = 18257 or id = 18356 or id = 18132 or id = 17769 or id = 18601 or id = 17855 or id = 18830 or id = 18639 or id = 17331 or id = 17449 or id = 18024 or id = 17896 or id = 18439 or id = 17750 or id = 18705 or id = 17797 or id = 17428 or id = 18452 or id = 17790 or id = 17442 or id = 17414 or id = 18823 or id = 17405 or id = 18766 or id = 18633 or id = 18329 or id = 18460 or id = 17898 or id = 18619 or id = 17955 or id = 17783 or id = 17509 or id = 18136 or id = 18596 or id = 17997 or id = 18800 or id = 18361 or id = 17632 or id = 18730 or id = 17952 or id = 17347 or id = 17566 or id = 17317 or id = 17715 or id = 18052 or id = 18351 or id = 18141 or id = 18391 or id = 17957 or id = 17700 or id = 17953 or id = 18658 or id = 17514 or id = 17446 or id = 18531 or id = 18741 or id = 17940 or id = 17834 or id = 17319 or id = 17315 or id = 17530 or id = 18746 or id = 17328 or id = 17801 or id = 17733 or id = 17512 or id = 17356 or id = 18751 or id = 18702 or id = 17308 or id = 18457 or id = 18445 or id = 18514 or id = 18064 or id = 17396 or id = 17757 or id = 18637 or id = 17387 or id = 18522 or id = 17586 or id = 18113 or id = 17767 or id = 18044 or id = 17358 or id = 18586 or id = 18664 or id = 18576 or id = 18574 or id = 17966 or id = 18383 or id = 18154 o
04-24 19:28:42.057: D/Error(19356): ERR: TOTAL BYTES WRITTEN: 182912
04-24 19:28:42.059: I/octvm_klo(5405): klo lock
04-24 19:28:42.060: W/ActivityManager(1856):   Force finishing activity com.dmsys.nas/.ui.activity.MainActivity
04-24 19:28:42.065: E/ActivityManager(1856): Invalid thumbnail dimensions: 0x0
04-24 19:28:42.066: D/WtProcessController(3823): onAMPauseActivity callback
04-24 19:28:42.066: I/Process(19356): Sending signal. PID: 19356 SIG: 9

**Comment by guolindev** [comment]
你的sql表达式过长，SQLite不支持这么长的表达式，这不是LitePal的问题。建议你可以把这些表达式的集合拆分开，分成多条SQL执行。或者考虑使用SQL的in语句，不要用这种无限or的写法。
