### ISSUE TITLE
当实体中有一个字段就叫“id”的时候 它本来的值会被覆盖掉

### ISSUE THREAD

**Issue by RevengeGP** [LitePalFramework/LitePal#199]
建表的时候会自动生成一个自增的integer字段 叫 id 但是如果我的实体里本身就有一个叫id的字段 这个字段本来的值就会被覆盖掉

**Comment by guolindev** [comment]
这个是litepal的大忌讳，如果是你自己有用的逻辑字段，不要把它命名成id，id是litepal内部要用的唯一标识的字段。
