### ISSUE TITLE
异步性能问题

### ISSUE THREAD

**Issue by JakeHao** [LitePalFramework/LitePal#205]
void execute() {
        if (pendingTask != null) {
            new Thread(pendingTask).start();
        }
    }
每个异步都需要去创建一个线程，对性能上会不会有影响呢，是不是考虑一下，用线程池呢

**Comment by maplee** [comment]
打算把这个地方改造成线程池，并加上优先级

**Comment by guolindev** [comment]
这个设计很简单啊，异步操作数据库本来就是一个避免阻塞UI的功能，你觉得还有必要设计成支持高并发吗，又不是网络请求。当时你要加上线程池这也是你的自由，不过在我看来这就是属于过度设计了。

**Comment by maplee** [comment]
这里是否使用线程池主要还是数据库是否高并发访问，按需吧
