### ISSUE TITLE
调用save()方法时抛出异常org.litepal.exceptions.DataSupportException: Save current model failed.

### ISSUE THREAD

**Issue by RUANHAOANDROID** [LitePalFramework/LitePal#206]
具体字段：
	int id;
	String username;
	int msg_id;
	int dir_type;
	String other_username;
	String other_name;
	int status;
	int is_read;
还请郭大大指点

**Comment by guolindev** [comment]
你可以把具体的堆栈贴出来看看吗。 或者可以调用saveThrows()方法，直接让程序崩溃，这样可以看到崩溃信息。

**Comment by RUANHAOANDROID** [comment]
问题已经解决了，是我操作的问题，谢谢郭大大

**Comment by guolindev** [comment]
解决就好

**Comment by dlxu1** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.Activity.PreviewTraceActivity}: org.litepal.exceptions.LitePalSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference

存储数据没问题，读取数据时程序崩溃，然后报异常，求解决
