### ISSUE TITLE
Could not open the database in read/write mode.

### ISSUE THREAD

**Issue by GeorgeBin** [LitePalFramework/LitePal#207]
error:
Caused by: android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.

condition:
1. install my app on device
2. I use LitePal in my app and  use storage value="external"
3. create db and write data
4. reset my device by "factory data reset erases all data on phone"
5. install same app agagin and start it

And then it shows the error I mentioned before.

my solution:
set LitePal as <storage value="internal"/>, then on device reset, old db will be deleted.

my question:
how to avoid this problem even use storage value="external"?

*
*
*
*
*

错误信息：
Caused by: android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.

触发条件：
1. 安装我的app
2. app内使用LitePal，并且设置为外部存储
3. app能正常使用LitePal 读写数据
4. 使用“恢复出厂设置”重置手机
5. 重新安装此app，启动

然后就会报上面提到的错误。

我找到的解决办法：
将LitePal设置为内部存储，因为恢复出厂设置时，会清除内部存储空间，而外部的不会主动清除。

问题：
如何可以在使用外部存储时，避免这个问题？

**Comment by GeorgeBin** [comment]
found the reason, it's not about LitePal, it's my mistake.
找到原因，是我自己的错误。

**Comment by xujianlafeng** [comment]
> found the reason, it's not about LitePal, it's my mistake.
> 找到原因，是我自己的错误。

请问一下你的是什么原因呢？
