### ISSUE TITLE
can not find a class named org.litepal.model.Table_Schema ?

### ISSUE THREAD

**Issue by LikeQuite** [LitePalFramework/LitePal#209]
调试的时候没有问题，预发布的时候报错。

**Comment by guolindev** [comment]
这个表是在内部自动生成的，理论上不会报错的。我这边现在也没办法重现，如果你那边能重现的话，麻烦你帮忙调试一下，在开始建表之前，调用一下LitePalAttr.getInstance().getClassNames()，看看里面有没有org.litepal.model.Table_Schema这个类？

**Comment by nb312** [comment]
可能是assets 文件没有编译进去

**Comment by LinChSh** [comment]
我也遇到这个问题 加了 LitePalAttr.getInstance().getClassNames()  打出来是有这个类的 但是确实报这个错
UploadDataBase: **************[org.litepal.model.Table_Schema,

**Comment by nb312** [comment]
会不会是没有加混淆 -keep啥的

**Comment by LinChSh** [comment]
调试了下 确实是混淆导致 
proguard.flags里加入
-libraryjars libs/litepal-1.5.1.jar
-dontwarn org.litepal.**
-keep class org.litepal.** {*; }
就没这个问题了  

感谢

**Comment by nb312** [comment]
哈哈 那就好
