### ISSUE TITLE
使用findAll方法时报错

### ISSUE THREAD

**Issue by BobCN2017** [LitePalFramework/LitePal#210]
如题，错误信息为：Caused by: org.litepal.exceptions.DataSupportException: no such column: id (code 1): , while compiling: SELECT * FROM chatmessage ORDER BY id
数据类定义如下：

`public class ChatMessage extends DataSupport implements Parcelable {
	public static final int TYPE_RECEIVED=0x001;
	public static final int TYPE_SENT=0x002;
	private String name;
	private String message;
	private String url;
	private int type;
	private Date date;

	public ChatMessage() {
		super();
	}

	public ChatMessage(String message, int type, Date date) {
		super();
		this.message = message;
		this.type = type;
		this.date = date;
	}

	protected ChatMessage(Parcel in) {
		name = in.readString();
		message = in.readString();
		url = in.readString();
		type = in.readInt();
		date.setTime(in.readLong());
	}

	public static final Creator<ChatMessage> CREATOR = new Creator<ChatMessage>() {
		@Override
		public ChatMessage createFromParcel(Parcel in) {
			return new ChatMessage(in);
		}

		@Override
		public ChatMessage[] newArray(int size) {
			return new ChatMessage[size];
		}
	};

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Override
	public int describeContents() {

		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {

		dest.writeString(name);
		dest.writeString(message);
		dest.writeString(url);
		dest.writeInt(type);
		dest.writeLong(date.getTime());
	}

}`

数据库里确实自动增加了一列_id，但没有id这一列，这是怎么回事呢？怎么解决！谢谢！

**Comment by guolindev** [comment]
这个确实比较奇怪，litepal会自动增加一个id列，但是不会自动增加_id这个列。你试试看在你的ChatMessage里面增加一个private int id字段，把应用删除掉，再重新运行一次，看看能不能正常了。

**Comment by BobCN2017** [comment]
把应用删除，重新编译安装，运行就好了。困扰了好久，看来还是有点笨笨。
回顾我为解决这个问题做的事，确实没有删除应用，但是我当时通过android device monitor将数据库完全删除，重新运行还是不行，那时app再次建立的数据库中的列名还是_id，而不是现在正常的id列名。
为什么会这样，这确实是个奇怪的问题。但好在现在正常了，感谢！！
