### ISSUE TITLE
关于国际化问题

### ISSUE THREAD

**Issue by maplee** [LitePalFramework/LitePal#211]
创建表名或者根据列名查询时，会遇到字符识别不了的问题，建议增加国际化，例如org.litepal.tablemanager.AssociationCreator中有关下面的修改

protected boolean isForeignKeyColumnFormat(String columnName) {
		if (!TextUtils.isEmpty(columnName)) {
			return columnName.toLowerCase(Locale.US).endsWith("_id") && !columnName.equalsIgnoreCase("_id");
		}
		return false;
	}

**Comment by guolindev** [comment]
我不太明白这里国际化的意思，因为litepal是不需要你自己指定表名和列名的，它会自动使用类名来作为表名，字段名来作为列名，而类和字段都是英文的，你不至于会把类名或者字段名定义成中文吧？

**Comment by maplee** [comment]
在葡萄牙余下有些字母如果只是单纯columnName.toLowerCase()不指定locale，会出现你不认识的字母，会导致数据库字段与查询语句的不一致

**Comment by guolindev** [comment]
原来如此，还真没考虑过这种情况，我这边没办法模拟葡萄牙语的环境，是只需要在指定Locale的地方使用Locale.US就能解决问题了吗？

**Comment by guolindev** [comment]
1.6.0版本已修复此问题，谢谢支持。
