### ISSUE TITLE
What is id?

### ISSUE THREAD

**Issue by Dhrupal** [LitePalFramework/LitePal#212]
I want to delete a record, what is id?

DataSupport.delete(Song.class, **id**);

Thank you.

**Comment by maplee** [comment]
DataSupport.getBaseObjId()

**Comment by Dhrupal** [comment]
Means i need to create local variable in my pojo named id?

**Comment by Dhrupal** [comment]
DataSupport.getBaseObjId() has protected access.

**Comment by Dhrupal** [comment]
Got the ans, just create id in model class, never set  id. its automatically incremented and unique. 

So using that is to delete.
