### ISSUE TITLE
update(id)的效率实在是太低

### ISSUE THREAD

**Issue by gundumw100** [LitePalFramework/LitePal#217]
这个update(id)的效率实在是太低了，有没有update(List)，直接一次性更新这个列表的？？？
我有一批数据需要批量更新，for循环如下：
for(Product bean:list){
  bean.update(bean.getId());
}
效率实在是太低了，我现在就碰到这个坑了！求解决思路，使用的是Litepal1.4.1

**Comment by gundumw100** [comment]
list中也就100多条数据，就ANR了。

**Comment by gundumw100** [comment]
我现在想通过DataSuport获得SQLiteOpenHelper对象，然后自己写一个事务处理，来解决上面的问题，该怎么办？

**Comment by gundumw100** [comment]
SQLiteDatabase db = org.litepal.tablemanager.Connector.getDatabase();
						db.beginTransaction();  
						try{
//						String sql="update PanDianProduct set amount=amount-10 where personid=?";
							for(PanDianProduct bean:beans){
								Log.i("tag", "id======"+bean.getId());
	//							db.execSQL(sql);
								ContentValues values = new ContentValues();
								values.put("intlcode", bean.getIntlCode());
								values.put("prodnum", bean.getProdNum());
								values.put("prodname", bean.getProdName());
								values.put("ischeckout", bean.getIsCheckout());
								db.update("PanDianProduct", values, "id = ?", new String[]{String.valueOf(bean.getId())});
							}
							db.setTransactionSuccessful(); //设置事务处理成功，不设置会自动回滚不提交。
						}catch(Exception e){
							Log.i("tag", "更新数据出错了");
						}finally{
							db.endTransaction();
						}

**Comment by NicodeLee** [comment]
还是觉得麻烦，应该提供update(List);
