### ISSUE TITLE
关于删除，删除是会删除以这个数据作为外键的表中的数据，但是不会删除和这张表中多对多关系的中间表中的映射。

### ISSUE THREAD

**Issue by houxiaodong** [LitePalFramework/LitePal#218]

**Comment by guolindev** [comment]
删除是分方法的，如果你是使用的delete()方法，会触发级联删除，这个时候关联表里的数据是会删掉的。但是如果是使用的deleteAll()方法，那么不会触发级联删除，因为考虑到效率的原因。这个时候只能靠你自己去删除这些关联数据了，如果不删也没什么关系，因为它们的外键引用已经没了，其实就是废数据，稍微占点空间而已。
