### ISSUE TITLE
用7.0手机模糊查询直接崩溃（deleteAll，saveAll也同样异常，save正常）

### ISSUE THREAD

**Issue by sunnydlee** [LitePalFramework/LitePal#219]
用7.0手机模糊查询直接崩溃（deleteAll，saveAll也同样异常，save正常），发现是查询语句中 用了百分号造成的异常（例如："where name like %ming%"），上网查了下百分号转译，发现把 % 换成 %25 就可以了，但是只能末尾的%可以用，"ming%25"可以正常查询到，然后我用原生的sqlite在7.0上查询都很正常，异常信息如下： org.litepal.exceptions.DataSupportException: near "%": syntax error (Sqlite code 1): , while compiling: SELECT * FROM bookentity WHERE id like %8%, (OS error - 11:Try again)   
用的是1.5.1

**Comment by guolindev** [comment]
你只贴了异常，但是并没有贴代码，我估计还是你的用法有问题。我这边在7.0的手机上使用下面的代码测试，结果一切正常：

`List<Singer> list = DataSupport.where("name like ?", "%杰%").find(Singer.class);`

可以查出数据库中所有包含杰字的歌手，包括周杰伦，林俊杰这样的名字。

另外，我注意到你上面的异常信息里面，有id like %8%这样的内容，这点你需要注意，模糊查询是只针对字符串的，不能作用在id上，id这种整型数据只能使用= , !=, < , >这类符号，是不能使用%或_来模糊查询的。
