### ISSUE TITLE
当对象中有字段为数组时针对数组的增删改查

### ISSUE THREAD

**Issue by csbz17027** [LitePalFramework/LitePal#220]
郭神，发现个问题，例子如下：
public class Test extends DataSupport{
private List<String> strList = new ArrayList();
···
···
}
Test test = new Test();
test.getStrList().add("123");
test.getStrList().add("abc");
test.save();
这样生成了一个test对象，他的strList有两条数据。自此以后，如果改变strList，例如test.getStrList().remove("123"),再次进行test.update()操作，表面上来看，此时数据库中这个test关联的strlist应该只有一条了，但是我发现strlist这张表并没有进行任何操作，关联在test上的strlist依旧是两条。
现在我只能使用DataSupport.deleteAll("test_strlist","strlist =?","123");这样的操作才能使用test.getStrList()的结果符合我的操作。
想问问郭神是我没有找到正确的方法还是当前的litepal设计就是如此？

**Comment by guolindev** [comment]
应该是你没找到正确的方法，首先update()方法是没有这种无参方法的，要么你调用update(id)指定更新记录的id，要么调用updateAll(condition)传入更新的条件，所以不带参数的这种update()方法。

而你的意图就是更新当前数据对吧，这种情况其实标准的做法是再调用一次save()方法。我发现很多人都不知道修改数据之后重新再save()就是更新的意思，其实文档中更新数据的第一条就是这种用法。https://github.com/LitePalFramework/LitePal#4-update-data
