### ISSUE TITLE
表升级问题

### ISSUE THREAD

**Issue by jameschou51** [LitePalFramework/LitePal#221]
app升级版本增加表后，在有擦汗寻的地方报错org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. alter table profLabels add column id text

**Comment by jameschou51** [comment]
已解决。。。

**Comment by guolindev** [comment]
解决就好

**Comment by mosione70** [comment]
I have the same problem
How did you solve it?
