### ISSUE TITLE
更新的时候经常需要id

### ISSUE THREAD

**Issue by 793383996** [LitePalFramework/LitePal#223]
这个id是父类private的, 是否能在@interface Column 中添加一个自增的标签, 方便查询出的时候使用此id update 而不用又去查询一次

Scarecrow_wzy@163.com

**Comment by guolindev** [comment]
你不用再查询一次，父类private的id你可以提供get方法出来，就能获取到id了。

**Comment by 793383996** [comment]
应该是DataSupport的 objectid 数据save成功之后自增主键会生成id  此时需要获取到这个自增id需要重新查询一次 而调用update方法需要这个id 好像这自增主键id还是private的
