### ISSUE TITLE
android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000)

### ISSUE THREAD

**Issue by Alan-li** [LitePalFramework/LitePal#224]
android.database.sqlite.SQLiteException: Expression tree is too large (maximum depth 1000)

两个类，具有以下关联：
public class Track extends DataSupport {
private long id;
private double longitude;
private double latitude;

...
}

public class Journey extends DataSupport {
private long id;
private double distance;
private List trackList = new ArrayList();

...
}

当 Track 表数据较大时，进行以下操作会有异常：
journey.getTrackList.add(track);
journey.save

**Comment by guolindev** [comment]
这个真没办法，你的表达式太长了，超出了SQL语句的支持范围。估计你是通过一个for循环不断地拼接or 或者 and 这样的条件语句导致的。建议分段执行的吧。
