### ISSUE TITLE
我能设置自己的自增主键?

### ISSUE THREAD

**Issue by 793383996** [LitePalFramework/LitePal#225]
郭大侠
我能设置自己的自增主键吗
因为有baseObjId但是不能获取
需要添加主键int 自增 类型 
能加个自动增长的标签吗
在这加个标签???
![image](https://user-images.githubusercontent.com/9602218/27063209-e3ef2f1a-5022-11e7-9f91-be09fa33135e.png)
![image](https://user-images.githubusercontent.com/9602218/27063215-eda44734-5022-11e7-89e5-8a43fb0dd430.png)
![image](https://user-images.githubusercontent.com/9602218/27063222-f84d9ab4-5022-11e7-8bc4-beb7a537f19b.png)

**Comment by guolindev** [comment]
这个不支持的，主键不能自定义。

**Comment by 793383996** [comment]
我的意思是 原来的主键不变  我继承DataSupport的子类加一个自增的标签 对应一个自增列
