### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by zhangchaojiong** [LitePalFramework/LitePal#227]
`    throw new IllegalArgumentException("the bind value at index " + index + " is null");`
这句抛异常是什么意思？

**Comment by zhangchaojiong** [comment]
请问是 value 不能为 NULL  吗？ 可是我声明的是 String 类型，SQLITE 应该是支持的。或者这里表示是说 我的 key 不能为 NULL?  求大神解答一下。

**Comment by zhangchaojiong** [comment]
我知道了！！
我是用了`where `语句 ，查询条件：` uuid?= XX , `
可能我的 XX 是`NULL`，而导致这个问题。

**Comment by guolindev** [comment]
解决就好
