### ISSUE TITLE
DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution

### ISSUE THREAD

**Issue by nb312** [LitePalFramework/LitePal#229]
E/AndroidRuntime(30050): Caused by: org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. create table scorebean (id integer primary key autoincrement,color text, total text, firstgoal text, standard text, guestorder text, guestred text, guestyellow text, guesthalfscore text, guestscore text, guestteam text, guestteamid text, sort text, headname text, season text, homeorder text, homered text, homeyellow text, homehalfscore text, homescore text, hometeam text, hometeamid text, remark text, mid text, league text, leaguecolor text, leagueid text, matchtime2 text, letgoal text, location text, matchtime text, matchtime integer, matchstate integer, leaguesumcount integer, iscollcet integer, neutrality integer, recommand integer, info integer, homecorner integer, headid integer, guestcorner integer, datasize integer)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Generator.execute(Generator.java:117)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:54)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:49)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Generator.create(Generator.java:171)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Generator.create(Generator.java:209)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)

E/AndroidRuntime(30050): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)

E/AndroidRuntime(30050): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:58)

E/AndroidRuntime(30050): 	at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)

E/AndroidRuntime(30050): 	at org.litepal.LitePal.getDatabase(LitePal.java:66)

**Comment by guolindev** [comment]
从你的SQL语句上来看，添加了两个matchtime字段 matchtime text, matchtime integer 
，这在数据库里面是不允许的，所以报错。我估计你的scorebean类应该有继承结构，然后这两个字段一个是在父类里定义的一个是在子类里定义的，你把这两个字段的名字区分开就可以了。

**Comment by nb312** [comment]
谢谢 确实是这个问题 我已经解决了
