### ISSUE TITLE
deleteAll 使用  DataSupport.deleteAll(Tab.class, "pid in (?)","") 

### ISSUE THREAD

**Issue by chenhui3014** [LitePalFramework/LitePal#231]
项目中常见的需求 根据某个字段删除。例如 商品表中根据根据商品id（字符串）批量 删除。
用SQL 表达 应该是 delete  from tab  where  pid in (?)。 用 LitePal 怎么写。请大神帮忙看一下

**Comment by sinyu890807** [comment]
一样的，DataSupport.deleteAll(Tab.class, "pid in (?)")，取绝于你这个？是什么。LitePal本质上就是对SQLiteDatabase进行了一层封装，所以你用SQLiteDatabase.delete能写出来，用LitePal就也能写出来。

**Comment by chenhui3014** [comment]
public void deleteHistory(String... pIds){
        DataSupport.deleteAll(Tab.class, "pid in (?)", pIds);
    }
关键问题 传入的参数不固定 也就导致  in(?)  占位符 不确定

**Comment by guolindev** [comment]
那你就不能这样写了，既然你传入的pids是个可变长度参数数组，那么conditions怎么能直接写一个固定字符串呢？ 你应该通过一个循环来确定你传入的参数长度，来动态组成conditions条件。
