### ISSUE TITLE
不能设置自增从1开始的问题

### ISSUE THREAD

**Issue by lizij** [LitePalFramework/LitePal#233]
希望能提供一个方法可以重置id的自增，使用sqlitedatabase直接改sqlite_sequence表没有生效

**Comment by guolindev** [comment]
自增这个是由数据库自动控制的，并没有重置清零这种api。实际上建议使用id来作为主键就是因为这个和业务逻辑永远没有任何关系，id是1和id是10000，对于你的业务逻辑来说应该没有任何区别。
