### ISSUE TITLE
什么时候能支持打包发布的已有数据库呢?

### ISSUE THREAD

**Issue by zyw745293** [LitePalFramework/LitePal#235]
有时项目需要将db文件打包在raw目录下发布，因为此db文件必须要存储一定的数据。目前litepal还不行。

**Comment by lizij** [comment]
可以写一个函数，在Application里将做好的db文件拷贝到指定目录就行

**Comment by guolindev** [comment]
楼上的说法是一种做法。另外，你也可以在项目初始化的时候开个线程去存储这些数据，这样就不用把db放在raw目录下随包发布了。
