### ISSUE TITLE
使用exists关键字遇到点问题

### ISSUE THREAD

**Issue by FJCDrome** [LitePalFramework/LitePal#236]
这是我的查询条件：receiverMobile = ? or exists (select 1 from retailorderitem where retailorder.id = retailOrderItem.parentId and retailorderitem.sinr = ? ))
在DBUtility的convertWhereClauseToColumnName方法里，会取出"or exists ( "这个字符串，然后判断“or”是不是数据库关键字，是就加上“_lpcolumn”。
把sql改成receiverMobile = ? or (exists (select 1 from retailorderitem where retailorder.id = retailOrderItem.parentId and retailorderitem.sinr = ? )))就可以了。不过我觉得这里不是很合理，第一条sql语法上应该是正确的。

**Comment by guolindev** [comment]
你把你完整的代码贴出来看看，要不然我也看得云里雾里的，我都不知道你调用的是LitePal的什么方法。

**Comment by FJCDrome** [comment]
差不多类似DataSupport.where("receiverMobile = ? or exists (select 1 from retailorderitem where retailorder.id = retailOrderItem.parentId and retailorderitem.sinr = ? )").count()。然后我debug的结果就是“or”被处理成了“or _lpcolumn”，导致sql执行失败。

**Comment by Destiny-wzz** [comment]
郭神，请问我的表里面有个字段为Temp，为什么建的表里面变成  Temp_Ipcolumn  导致查询出错

**Comment by guolindev** [comment]
已经确实是个bug了，下个版本会中把这个bug给修复，谢谢反馈。

**Comment by FJCDrome** [comment]
@guolindev 应该的。话说之前反映过一个问题，事务导致死锁 #115 ，下个版本会有这方面的更新吗？

**Comment by guolindev** [comment]
此bug已经1.6.1版本中修复。
