### ISSUE TITLE
关于update Boolean 类型没有成功问题

### ISSUE THREAD

**Issue by lxz2014** [LitePalFramework/LitePal#238]
![image](https://user-images.githubusercontent.com/8327268/27893172-c1799530-6236-11e7-9b3c-624d6e6d2c60.png)

这段代码在更新 boolean字段时候会有问题。
如果boolean字段默认值是false， 之后被修改为true， 然后我又想更新为false时候，这些条件都不满足，直接跳过。

**Comment by guolindev** [comment]
重复问题，参考这条 https://github.com/LitePalFramework/LitePal/issues/32

**Comment by lxz2014** [comment]
谢谢你的回答，看了你提的问题，不过我觉得还是没必要，因为我觉得这种事应该是上层的事，这个框架没必要做这层判断，至于你提的这种还需要在set一遍原值，其实也不麻烦：可以根据id将原数据查找出来，在set需要修改的字段，再update，觉得没毛病。
