### ISSUE TITLE
表升级的问题

### ISSUE THREAD

**Issue by animus198656** [LitePalFramework/LitePal#239]
我已知晓要为int型数据赋默认值0，需要调用setToDefault()方法。
我的问题是：在升级表的时候，新增加一个int类型的数据列，应该在什么位置调用setToDefault()，将已有数据的这个新增列设为0？如果不能实现，应该怎么通过这个新增字段查询相关数据？
举例说明：比如在数据库1.0版本中，保存了一个book表，并且该表中已经存有一条书籍信息；在升级数据库时，在book表中新加"浏览量"字段，如何将这条已有的书籍信息的"浏览量"设为0？或者我如何能通过"浏览量"查询出这条书籍信息？
我试了这两种种方法：
1、 DataSupport.where("readnum =?", "").find(Book.class);
2、DataSupport.where("readnum <>?", "3").find(Book.class);（数字3是随意写的）
都查询不出数据

**Comment by guolindev** [comment]
你新增一个列，如果想把它的值默认设置成0，可以这样写：
@Column(defaultValue = "0")
private int readnum;

将已有书籍信息的浏览器都设置成0，可以这样写：
Book book = new Book();
book.setToDefault("readnum ");
book.updateAll();

通过浏览量查询书籍就是最标准的查询语句了：
DataSupport.where("readnum = ?", "0").find(Book.class);
DataSupport.where("readnum != ?", "3").find(Book.class);

**Comment by animus198656** [comment]
好的，多谢
