### ISSUE TITLE
CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 8 columns.

### ISSUE THREAD

**Issue by Daemon1993** [LitePalFramework/LitePal#240]
你好 不知道怎么就出现这个错误
情况出现很奇怪
DataSupport.where("uid=?", uid + "").find(TB_UserInfo.class);
只有uid为条件才出现 一直报错  换个字段就好了 以前没出现 突然出现的 已经整懵了

**Comment by Daemon1993** [comment]
Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

抓的异常

**Comment by guolindev** [comment]
我也并没有遇到过这个问题，不过我在stackoverflow上找到了一个和你一样的问题，看看对你有没有帮助吧 https://stackoverflow.com/questions/26755590/failed-to-read-row-0-column-0-from-a-cursorwindow-which-has-0-rows-64-columns
