### ISSUE TITLE
关于默认值问题

### ISSUE THREAD

**Issue by kllkko** [LitePalFramework/LitePal#241]
问题：把表中的某列数据设置成了默认值0，下次再update这个值（从0到非0）会失败
DMTask tas = new DMTask();
**tas.setToDefault("taskStatus");** --->status设置为0
tas.update(task.getId());

/*******************/

DMTask save = new DMTask();
**save.setTaskStatus(4);   ----->update失败**
save.setTaskErrorCode(-1);  ----->update成功
save.setTaskFinishDate(123);    ----->update成功
save.update(task.getId());

请问这是什么原因，谢谢

**Comment by guolindev** [comment]
不太清楚。我刚才模拟了和你一样的代码来进行测试，结果是正常的。

singer = new Singer();
singer.setName("周杰伦");
singer.setAge(30);
singer.save(); // 插入数据

Singer s = new Singer();
s.setToDefault("age");
s.update(singer.getId()); // age成功设置为0

Singer s1 = new Singer();
s1.setAge(35);
s1.update(singer.getId()); // age成功设置为35

我是加了3个按钮，分别点了一遍，每个按钮点击完执行的结果都是正常的。或许你那边有什么特殊的操作没有贴出来，能提供更多信息吗？
