### ISSUE TITLE
不能使用saveOrUpdate()？

### ISSUE THREAD

**Issue by 1510766316** [LitePalFramework/LitePal#242]
我的代码：public boolean saveAsFavorite(int type,String name){
                          BookInfo info = new BookInfo();
                          info.setType(type);
                          info.setName(name);
                          return info.saveOrUpdate("name=?",name);
                  }

错误提示：The method saveOrUpdate(String, String) is undefined for the type BookInfo

我用的是1.5.1版本。请教下，这是怎么回事？郭神，帮忙解决下。

**Comment by guolindev** [comment]
这个估计是项目工程问题，我也遇到过编译能过，但是运行一运行就报class not found或者method is undifined这种错误。 通常都是项目的缓存原因导致，最新的代码没有打到apk里面去。建议你clean一下项目再试试。
