### ISSUE TITLE
如何储存数据库到ExternalStorage，以及如何打开已经下载到ExternalStorage的数据库文件？

### ISSUE THREAD

**Issue by chiaroLi** [LitePalFramework/LitePal#243]
找了很久没找到对应方法。
各位大神求教！

**Comment by guolindev** [comment]
<storage value="external" />
数据库将会自动存放到sdcard的Android/data/包名/files/databases下面。 打开db文件的话可以借助很多工具，如Root Explorer的内置SQL浏览器，SQLite Expert。

**Comment by chiaroLi** [comment]
意思是如何把新建的数据库文件存储到指定位置哈。
以及如何在代码中连接数据库文件，并且进行修改呢？
