### ISSUE TITLE
部分手机litepal.xml missing 

### ISSUE THREAD

**Issue by 30sunling** [LitePalFramework/LitePal#244]
org.litepal.exceptions.InvalidAttributesException: dbname is empty or not defined in litepal.xml file, or your litepal.xml file is missing

部分手机会出这个问题

**Comment by guolindev** [comment]
这个情况要么是你的litepal.xml中没有配置dbname，要么是你在动态切换数据库的时候没有指定dbname。
如果你确保你的用法肯定没有出错的话，那么只有一种可能就是内存被回收掉了。因为dbname从配置文件读取之后就是保存在内存中的，之后直接从内存当中获取，如果获取不到的话就会抛出上面的那个异常。

在新版本里面我又做了一些优化，如果内存当中读取不到的话，会让LitePal再次从配置文件当中去读取，等1.6.0版本发布的时候你可以更新一下，这个问题有可能就好了。
