### ISSUE TITLE
多条件查询怎么写？？？

### ISSUE THREAD

**Issue by guanyueyun** [LitePalFramework/LitePal#245]
比如and   or   怎么使用

**Comment by guanyueyun** [comment]
`DataSupport.where("uid = ? and affixName = ?", String.valueOf(uid), fileName).find(AttachmentModel.class);`
这样写有问题吗？

**Comment by guolindev** [comment]
就是这么写的，关于LitePal查询的更多用法可以参考这篇文章 http://blog.csdn.net/guolin_blog/article/details/40153833

**Comment by YY030913** [comment]
org.litepal.exceptions.LitePalSupportException: near "and": syntax error (code 1): , while compiling: SELECT * FROM friend WHERE userId = ? and groupid = ? @guolindev 我用3.0.0报错了，1.5.0也报错
