### ISSUE TITLE
 java.lang.NoClassDefFoundError: org.litepal.crud.QueryHandler

### ISSUE THREAD

**Issue by chenhaoaijay** [LitePalFramework/LitePal#248]
在有个手机上启动会报错
 java.lang.NoClassDefFoundError: org.litepal.crud.QueryHandler
                                                                          at org.litepal.crud.DataSupport.findFirst(DataSupport.java:839)
                                                                          at org.litepal.crud.DataSupport.findFirst(DataSupport.java:811)
这个是什么情况？

**Comment by guolindev** [comment]
不好说，通常出现这种情况，有以下几种可能：

1. 包打的有问题，litepal的相关代码没有打进去。
2. 程序设置了混淆，导致litepal的代码无法正确找到。

不过你的情况上面两种都不太像。你说的是在有个手机上会出错，那么主要就是看这个手机是什么了。之前也有个朋友问了和你比较相似的问题，后面我让他多做几次实验，最后发现是所有5.0以下的手机都会出这个错。而5.0以下比较突出的一个特征就是默认是不支持multi dex的，当方法数超过64K的时候就可能出现代码打不进包里的情况。关于multi dex怎么使用，你可以参考这篇文章 https://developer.android.com/studio/build/multidex.html 。

如果你的问题确实和之前那位朋友一样的话，这应该就可以解决你的问题了。

**Comment by chenhaoaijay** [comment]
感谢回复，刚无意间发现问题了，是超过64K导致的，multi dex用了，但是在Application漏了一句MultiDex.install(this)
，加上就好了。这个问题低端手机比较容易出现，之前测试的手机内存大，一直没发现。
粗心大意啊。。。看来还是要仔细一点。。

**Comment by guolindev** [comment]
解决就好，那我把问题关掉了。

**Comment by chenhaoaijay** [comment]
嗯
