### ISSUE TITLE
android.database.CursorWindowAllocationException Cursor window allocation of 2048 kb failed. # Open Cursors=16 (# cursors opened by this proc=16)

### ISSUE THREAD

**Issue by madtcsa** [LitePalFramework/LitePal#249]
java.lang.RuntimeException:Unable to start service com.lzx.lock.service.LockService@8a173cc with Intent { cmp=mobi.infolife.ezweather.locker.dial_platey/com.lzx.lock.service.LockService }: org.litepal.exceptions.DataSupportException: Cursor window allocation of 2048 kb failed. # Open Cursors=16 (# cursors opened by this proc=16)
 android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2886)
 ......
 Caused by:
 android.database.CursorWindowAllocationException:Cursor window allocation of 2048 kb failed. # Open Cursors=16 (# cursors opened by this proc=16)
 android.database.CursorWindow.<init>(CursorWindow.java:108)
 android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
 android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
 android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
 android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
 org.litepal.crud.DataHandler.query(DataHandler.java:132)
 org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
 org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
 org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)
 com.lzx.lock.db.CommLockInfoManager.getAllLockedCommLockInfos(CommLockInfoManager.java:84)
 com.lzx.lock.service.LockService.onStartCommand(LockService.java:102)
 android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2869)
 android.app.ActivityThread.access$2100(ActivityThread.java:148)
 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
 android.os.Handler.dispatchMessage(Handler.java:102)
 android.os.Looper.loop(Looper.java:135)
 android.app.ActivityThread.main(ActivityThread.java:5272)
 java.lang.reflect.Method.invoke(Native Method)
 java.lang.reflect.Method.invoke(Method.java:372)
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)

**Comment by Daemon1993** [comment]
我前面也遇到过 感觉你可以先确定下 有没有字段存储的内容过大 比如2M

**Comment by guolindev** [comment]
这个问题和楼上碰到的应该是一样的，可以参考下他这个issue https://github.com/LitePalFramework/LitePal/issues/255
