### ISSUE TITLE
DatabaseGenerateException at .save() method

### ISSUE THREAD

**Issue by jubin-successive** [LitePalFramework/LitePal#250]
**Exception**

E/SQLiteLog: (1) duplicate column name: inspectionhistorybean_id
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err: org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. create table inspectionhistorybean_inspectionhistorybean (inspectionhistorybean_id integer, inspectionhistorybean_id integer)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.Generator.execute(Generator.java:117)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.AssociationCreator.createIntermediateTable(AssociationCreator.java:335)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.AssociationCreator.addAssociations(AssociationCreator.java:289)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.AssociationCreator.addOrUpdateAssociation(AssociationCreator.java:59)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.Generator.addAssociation(Generator.java:132)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.Generator.create(Generator.java:210)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:58)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1862)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at org.litepal.crud.DataSupport.save(DataSupport.java:1802)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at com.deep.fragments.QuestionsFragment$GenaratePDF.doInBackground(QuestionsFragment.java:1136)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at com.deep.fragments.QuestionsFragment$GenaratePDF.doInBackground(QuestionsFragment.java:1010)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-17 12:50:59.918 18257-18891/com.test.litepal W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-17 12:50:59.919 18257-18891/com.test.litepal W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-17 12:50:59.919 18257-18891/com.test.litepal W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-17 12:50:59.919 18257-18891/com.test.litepal W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Model Class**

    @Column(unique = true, defaultValue = "unknown")
    private String name;

    @Column(ignore = true)
    private String data;

    @Column(ignore = true)
    private String month;

    @Column(ignore = true)
    private String date;

    @Column(ignore = true)
    private List<InspectionHistoryBean> inspectionHistoryBeen = new ArrayList<InspectionHistoryBean>();

**Comment by guolindev** [comment]
Well. You may have a self many2many association of your model. You model class must be InspectionHistoryBean right? And in the InspectionHistoryBean, it has many InspectionHistoryBeans. Right now LitePal doesn't support this kind of association. But I notice you used an ignore annotation, so you might want to ignore this association, but it didn't work. It's a bug, and will be fixed in the next release. Right now you can remove the private part of your inspectionHistoryBeen field, and everything should work fine.
