### ISSUE TITLE
在创建数据库时报错

### ISSUE THREAD

**Issue by 2shiwenbin0522** [LitePalFramework/LitePal#252]
郭神您好, 我这有一个项目以前是用sqllite 直接操作数据库的,现在用litepal 操作数据库  每次创建数据库的时候总是报出 org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. drop table if exists update这个错误.但是我查我的表的时候没有用到系统的关键字 
附表:
private String userid;

    private String token;

    private String name;

    private String photo;

    private String sex;
我想知道这个具体是什么原因引起的

**Comment by guolindev** [comment]
是你的表名的问题，update是数据库的关键字，你不能使用这个字段来作为表名的，所以你的类不能命名成Update，换一个名字就可以了。
