### ISSUE TITLE
存储问题

### ISSUE THREAD

**Issue by we1272108979** [LitePalFramework/LitePal#253]
存储一个bean对象过程使用toast 显示存储成功 
为啥取得时候报 为空 ？很纳闷？

**Comment by guolindev** [comment]
你不贴上任何代码，我也没办法帮你查问题的。

**Comment by manuchen** [comment]
看到这个问题,我想你可以从以下这些方面进行排查:
1.litepal.xml里面+1,然后导出db文件,看看是否可以.
2.gradle 里面的versionCode +1.,然后导出db文件,看看是否可以.
3.卸载app,重新调用一遍.然后导出db文件,看看是否可以.
4.换个db打开工具,比如换个版本sqlite
5.当然我开始遇到这个问题的时候,以上操作都完成了,但是还是没有.
只好静下心来排查代码了.后来, 发现画蛇添足的加了这句db.beginTransaction();
瞬间懵逼.以后记得别复制错了.
