### ISSUE TITLE
关于存储外键的问题

### ISSUE THREAD

**Issue by maplee** [LitePalFramework/LitePal#254]
实体类Factory
String name;
ArrayList<Car> cars;
ArrayList<Bike> bikes;

实体类Machine
String name;
String model;

实体类Car
class Car extends Machine{
int engineType;
}

实体类Bike
class Bike extends Machine{

}

想请教为什么bike和car表中没有factory_id,需要什么特殊设置

**Comment by guolindev** [comment]
你的Factory类定义的有问题，没有指定具体的泛型，你不指定泛型LitePal没办法知道你想的cars和bikes具体关联的到底是哪个实体类。要改成这样才行：
```java
ArrayList<Car> cars;
ArrayList<Bike> bikes;
```
