### ISSUE TITLE
java.lang.RuntimeException: org.litepal.exceptions.InvalidAttributesException: dbname is empty or not defined in litepal.xml file, or your litepal.xml file is missing.

### ISSUE THREAD

**Issue by yangkun19921001** [LitePalFramework/LitePal#257]
郭霖大神，我在 1.5.0 版本中 调用 DataSupport.find xxx 查询方法，报找不大 xml 文件
![image](https://user-images.githubusercontent.com/20500834/28519074-cd15d948-709c-11e7-947a-51955e317a96.png)
![image](https://user-images.githubusercontent.com/20500834/28519089-dbefb952-709c-11e7-97e3-38a5f21bd326.png)
![image](https://user-images.githubusercontent.com/20500834/28519108-ece05bcc-709c-11e7-927c-6f3982b58a71.png)

**Comment by yangkun19921001** [comment]
我是在我自己 library model 中依赖你的 litepal 我在 app/src/main/asstes 下创建的 litepal.xml 这应该没有什么影响吧？

**Comment by yangkun19921001** [comment]
测试是用 Android 7.0 测试的。

**Comment by yangkun19921001** [comment]
找到原因了 我在 build.gradle 中写了一句这个  assets.srcDirs = ['assets']   导致在 assets 中找不到文件 这一句是什么意思 有人给我说下吗？谢谢！！！

**Comment by guolindev** [comment]
你加这一句更改了默认的assets文件夹路径了吧，改了路径之后，litepal.xml也要放到相应的文件夹里面的。
