### ISSUE TITLE
I think my configuration of litepal is correct. But when I save data in activity, it was crashed.

### ISSUE THREAD

**Issue by FerrandTian** [LitePalFramework/LitePal#26]
Here is the error:
W/System.err﹕ java.lang.NullPointerException
W/System.err﹕ at android.content.ContextWrapper.getAssets(ContextWrapper.java:83)
W/System.err﹕ at org.litepal.parser.LitePalParser.getConfigInputStream(LitePalParser.java:188)
W/System.err﹕ at org.litepal.parser.LitePalParser.useSAXParser(LitePalParser.java:116)
W/System.err﹕ at org.litepal.parser.LitePalParser.parseLitePalConfiguration(LitePalParser.java:97)
W/System.err﹕ at org.litepal.tablemanager.Connector.buildConnection(Connector.java:116)
W/System.err﹕ at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:62)
W/System.err﹕ at org.litepal.tablemanager.Connector.getDatabase(Connector.java:97)
W/System.err﹕ at org.litepal.crud.DataSupport.save(DataSupport.java:984)
W/System.err﹕ at com.hanyou.ulock.ui.RoomActivity.transform(RoomActivity.java:408)
W/System.err﹕ at com.hanyou.ulock.ui.RoomActivity$3.onReceive(RoomActivity.java:297)

Here is the litepal.xml:
<?xml version="1.0" encoding="utf-8"?>
<litepal>
    <dbname value="lock_log"></dbname>
    <version value="2"></version>
    <list>
        <mapping class="com.hanyou.ulock.entry.LockLog"></mapping>
    </list>
</litepal>

Here is the LockLog.java:
public class LockLog extends DataSupport {
    private String type_no;
    private String open_type;
    private String open_time;
    private String valid_time;
...

Here is the AppContext.java:
public class AppContext extends LitePalApplication {
...

And here is the code:
LockLog log = new LockLog();
log.setOpen_type(type);
log.setOpen_time(openTime);
log.setType_no(typeNo);
log.setValid_time(validTime);
PrintUtil.println("SAVE:" + log.save());
...

**Comment by sinyu890807** [comment]
I met this problem before. But i am not sure how to solve it. Need to checkout your codes and find out why. But my experiences tells do not try to new your AppContext or it will become a common object but a Application object. And if you use these codes in the fragment, do not execute them in the onCreateView() method or earlier, try to use them in the onActivityCreated() method. The above way works for me so far.
