### ISSUE TITLE
更新数据问题

### ISSUE THREAD

**Issue by zcychinese** [LitePalFramework/LitePal#260]
使用以下这种方式更新数据时，当更新的数据类型为整形时，不能更改为0.
例如：
        Student student = new Student();
        student.setSex("男");
        //此处整形数据，可以更改为其他数据，但是改为0失败，可以换其他方式进行更新。
        student.setAge(0);
        student.updateAll();

**Comment by guolindev** [comment]
重复问题，参考这一条 https://github.com/LitePalFramework/LitePal/issues/32

**Comment by zcychinese** [comment]
感谢郭神。一直在看您的博客，书也买了一些。可以说是跟着您的脚步走来的。感谢




发自网易邮箱大师
在2017年08月02日 10:52，郭霖 写道：

重复问题，参考这一条 #32
