### ISSUE TITLE
高并发操作发生小概率crash，database is locked

### ISSUE THREAD

**Issue by vinzoufeng** [LitePalFramework/LitePal#261]
1.  高并发调用DataSupport.saveAll等接口，小概率crash;
2.  发生crash原因，database is locked；
3.  不知道封装内部是否能在不影响读写性能的基础上做出避免？

**Comment by guolindev** [comment]
数据库是不能支持并发操作的，LitePal在所有的API当中都有加上锁，所以即使你是高并发调用LitePal的任何接口，同一时间也只会有一个线程访问数据库，其他的线程都会等待。

所以出现小概率crash这个可能还要看看你的具体代码，要不然我也没法分析是LitePal内部的代码导致的，还是外部调用的代码有误导致的。

最好可以把错误日志也发出来看看。
