### ISSUE TITLE
save过的对象，删除后，同一个对象无法再次save。

### ISSUE THREAD

**Issue by ordinaryX** [LitePalFramework/LitePal#262]
部分代码
类1
private void updateDB(Chapter chapter, Sections sections) {
	...
        sections.setParentName(chapter.getChapterName());
        sections.setBitrate(PolyvBitRate.liuChang.getNum());
        sections.save();//存储
	...
    }
类2
DataSupport.deleteAll(Sections.class, "sectionid=?", sections.getSectionId());//删除

在 类1 中调用存储的代码，在 类2 中删除了相应的一条数据。回到 类1 中再调用这个存储方法，save()返回依旧是true，但实际表里边是没有这条数据的。
我怀疑是对象持久化的问题，尝试回到 类1 页面时刷新了下整个页面，重新赋值数据，然后再save()，是可以成功存储并且表里有数据。
但是觉得这样太影响页面流畅度了，有没有其他办法，回到 类1 页面的时候直接可以调用save()。

**Comment by ordinaryX** [comment]
解决了，加了一个判断。就是不知道合适不影响效率不。
sections.setParentName(chapter.getChapterName());
        sections.setBitrate(PolyvBitRate.liuChang.getNum());
        if (sections.isSaved()) sections.delete();
        sections.save();

**Comment by guolindev** [comment]
因为你虽然在数据库中删除了这个对象的数据，但是对象自身还保留着存储状态，所以存不进去。这种情况你需要手动去把对象的存储状态清除掉。可以调用 sesions.clearSavedState()方法。

如果是要清除一个集合中所有对象的存储状态，可以调用DataSupport.markAsDeleted()方法
