### ISSUE TITLE
使用litepal看log出现异常

### ISSUE THREAD

**Issue by bigzhulove** [LitePalFramework/LitePal#263]
data store failed.
     android.database.sqlite.SQLiteDatabaseLockedException: database is locked (Sqlite code 5): , while compiling: PRAGMA journal_mode, (OS error - 11:Try again)

这个异常怎么解决

**Comment by bigzhulove** [comment]
算了，还是换个别的数据库

**Comment by guolindev** [comment]
有更完整的日志吗，还有你是怎么操作的也描述一下，调用的代码也可以贴一下。
