### ISSUE TITLE
myAdapter.swapCursor(someCursor) java.lang.IllegalArgumentException: column '_id' does not exist

### ISSUE THREAD

**Issue by shanksiscool** [LitePalFramework/LitePal#264]
我在用LitePal创建了一个db后，写入了一些数据，出于项目特殊要求导出db，到某个项目中使用，在一个Activity中，调用adapter.swapCursor(someCursor); 报java.lang.IllegalArgumentException: column '_id' does not exist，因为swapCursor()函数的源码中有一段是if (newCursor != null) {
            if (mChangeObserver != null) newCursor.registerContentObserver(mChangeObserver);
            if (mDataSetObserver != null) newCursor.registerDataSetObserver(mDataSetObserver);
            mRowIDColumn = newCursor.getColumnIndexOrThrow("_id");  // 主要看这行
            mDataValid = true;
            // notify the observers about the new cursor
            notifyDataSetChanged();
        } 
我回头去看下db里面的所有列名，发现用litepal创建的表格用的是'id'，而不是'_id'。
没什么意思，就是想告诉郭神有这么一回事。

**Comment by XuQK** [comment]
啊，我今天折腾了一天，也是这个问题，用CursorLoader监听数据库变化，没有这个“_id"不行。
我在模型类中定义了"_id"，实际出来的效果也是"id"，这样导致这个数据库就完全不能用CursorLoader了。
郭神能不能给个解决方法，litepal这么好用，实在不想放弃

**Comment by guolindev** [comment]
这个确实不好弄，因为CursorLoader读的主键就是_id，但是litepal的主键是id。这个问题长期存在，但是我一直没有去解决，一个是id这东西确实不好改，litepal所有的功能都依赖于这个id之上。第二是用litepal其实完全没必要使用CursorLoader，litepal在查询方面的API已经非常好用了，我个人现在使用litepal提供的查询API基本已经可以完成所有的工作，没有什么场景是非要用CursorLoader不可的。

**Comment by shanksiscool** [comment]
@guolindev litepal已经能async操作了，这算是几乎完美了，但我恨自己项目中不能用啊。我是一个android新手，项目中有个需求要查询数据库中的全国各县市，这时我的做法是自己动手写一个app，获取到全国的县市，到出db，到我的工作项目中，直接读取db，这时拿到的是cursor，结合cursor adapter完成读取和适配recyclerview。在此条件下我想过要用litepal的读取外部存储空间的db的方式，但是我担心不可用，虽然我在litepal 的github上看到，创建db之初是可以指定db存放internal或external的位置，但我没去测试行不行，郭哥，你觉得可以嘛？为了保险起见还是按照下面的方法做了。
@XuQK 说一下我的解决方法吧，我要用到cursor adapter中的changCursor(){swapCursor()也可以}方法来更新recycleView的item，因此，我创建了一个MyCursorAdapter继承自CursorAdapter，深入到要报错的地方，重写swapCursor()方法，将其中的"_id"改为"id"就暂时能用了，没准你可以借鉴下。

**Comment by XuQK** [comment]
我弄好了，是写的一个ContentObserver，监听可能会变动的Uri，变动了的话通知Adapter重新从数据库获取数据并刷新列表。

**Comment by shanksiscool** [comment]
@XuQK 参考下MyCursorAdapter
https://gist.github.com/shanksiscool/9daa010871278fa54e6a8c618d68aba6

**Comment by XuQK** [comment]
你这个挺好的，感觉比我那个效率高多了

**Comment by shanksiscool** [comment]
@XuQK 成功了。MyCursorAdapter还是abstract class，用于替换成你要用的CursorAdapter，我这边直接要用到swapCursor()来更新recycleView 的item。

**Comment by XuQK** [comment]
@shanksiscool 完全没思路怎么用呀，照你的那个抄下来，里面那些变量全是无法解析。求指点
