### ISSUE TITLE
设置存储路径

### ISSUE THREAD

**Issue by hopegiser** [LitePalFramework/LitePal#265]
通过  <storage value="external"  /> 可以将数据库保存到外部 
 
郭神，能不能提供设置具体路径的API

**Comment by dota2fans** [comment]
同求

**Comment by hope711** [comment]
<dbname value="/storage/sdcard0/360/Test.db"></dbname>
  <storage value="internal"/>

**Comment by hopegiser** [comment]
还是不行呀

**Comment by dota2fans** [comment]
<dbname value="/storage/emulated/0/MicroClassVideo/db/class_note_book.db" >
    </dbname>

    <storage value="internal" />
我使用了，测试通过

**Comment by guolindev** [comment]
这个功能从1.6.0版本开始支持，具体可以参考这篇文章 https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650240766&idx=1&sn=096f029aa531d5d99191c3d4c9126fc1&chksm=88638791bf140e87721abb26b32b68233153ccff50f2940d173cd5108bff42287d42db9304d9#rd
