### ISSUE TITLE
怎么读取主键是"ID"而不是"id"的表(怎么用LitePal读写外部已有的DB文件)

### ISSUE THREAD

**Issue by hope711** [LitePalFramework/LitePal#268]
DB文件 是整个从后台拉下来的.
app只负责增删改查(之前一直是调用原生API),更新表的操作全由后台负责
现在想使用litePal代替原有的"数据库框架",但是研究一段时间后 感觉一点都不能使用LitePal了?
求助 难道真的一丢丢都不能使用LitePal?

设置storage value="internal"已经可以定位到外部的数据库文件
问题
1.所有表中的主键是"ID" 而不是"id", 
执行代码时报错
  org.litepal.exceptions.DataSupportException: column 'id' does not exist
2.如果后台更新了表, app这边是否需要升级version

**Comment by guolindev** [comment]
litepal不兼容遗留数据库的，也就是说这个数据库必须是由litepal创建的，从别的程序拿来的数据库，litepal无法读取的。

**Comment by hope711** [comment]
已经使用GreenDao代替了,可以很好的处理 表|字段大小写,设置主键非自增,使用非TEXT类型等需求,,
