### ISSUE TITLE
数据库数据量大，怎么实现分页模式加载数据呢

### ISSUE THREAD

**Issue by guominfang** [LitePalFramework/LitePal#269]

**Comment by ixjhuang** [comment]
说不定可以用id来选择范围呢O(∩_∩)O~
.where.find("id > ? and id < ?");
或者别的什么字段


路过。。

**Comment by guolindev** [comment]
分页加载LitePal有API支持的，使用limit()和offset()方法配合，就可以实现分页功能了。具体可以参考这篇文章 http://blog.csdn.net/guolin_blog/article/details/40153833
