### ISSUE TITLE
实体类中定义的Boolean字段，在存入boolean值以后，查看数据库显示的是1或0

### ISSUE THREAD

**Issue by lu-xu** [LitePalFramework/LitePal#271]
是直接在内部将boolean字段转成int类型了吗

**Comment by Li-Yuwei** [comment]
这个boolean类型的很坑，改为true之后不能在改为false，我现在都不用boolean类型用string代替了

**Comment by lu-xu** [comment]
我这边是，定义的对象属性是boolean，赋值也是true/false，但是实际到数据库查看，发现变成了int类型的1/0

**Comment by ixjhuang** [comment]
并没有改为true之后不能改为false吧，如果是的话那也应该是自己保存的逻辑出问题了;
真的确认过是LitePal的问题了？
（因为我也遇到了类似的问题，但是排查之后发现是自己的逻辑的问题，所以还是不要轻易甩锅）

我打开数据库看也确实是0/1可能只是在数据库里被显示成是0/1吧，
也不是个issue吧，毕竟读取修改并没有问题

**Comment by lu-xu** [comment]
好吧，孤陋寡闻了，之前还真没留意到这回事，以为定义的是什么类型就存什么类型。感谢

**Comment by Duxina** [comment]
请问各位，我如果不给boolean属性一个默认值，这个是直接显示null还是false？
