### ISSUE TITLE
多数据库问题

### ISSUE THREAD

**Issue by Destiny-wzz** [LitePalFramework/LitePal#273]
@guolindev @sinyu890807 两位大神，1.6.0版的似乎不能创建多个数据库，1.5.1的可以，不知道我的使用方式是否错误
![default](https://user-images.githubusercontent.com/31026903/29702608-924a6402-89a4-11e7-9768-d259055f7a95.png)

还有能否提供一个设置字段名是否保持大/小写的方法呢？

**Comment by Destiny-wzz** [comment]
使用1.5.1发现这个问题：先切换为其它数据库，操作完后调用LitePal.useDefault()，再进行操作时出现     java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /storage/emulated/0/Android/data/...    这个错误，1.6.0又不能创建其它库，求教

**Comment by guolindev** [comment]
看上去你的用法并不正确，创建多数据库至少需要去use的，你都没有使用这个方法。看下这篇文章讲解的用法吧 https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650237709&idx=1&sn=1e9ee99617b2cb8f00af9b35eb83a637&chksm=88639a62bf14137450f5c98ec245362a0fef36e1bae1eaf12081d52d8b0e60a2c299e1699593#rd
