### ISSUE TITLE
保存数据有问题

### ISSUE THREAD

**Issue by zuoanguo** [LitePalFramework/LitePal#274]
当首先保存一个数据默认我0  然后修改为9 可以保存，再修改为0就不能保存（修改任意值都可以保存，0就是不行）

**Comment by ixjhuang** [comment]
这个可以看这里
http://blog.csdn.net/guolin_blog/article/details/40083685，
这里也讲到了https://github.com/LitePalFramework/LitePal/issues/32 ，
为了让update的时候不需要把所有的值都set上去，
所以当实例对象的成员没有赋值--也就是是默认值的时候，update会选择不更新，
因为你原本默认是0，当再修改为0的时候，update是不知道这个0是默认的还是你修改的，所以当做是默认值来处理，也就是不更新，
所以你用setToDefault()方法就可以保存为默认值，也就是你的0了。

我猜应该是这样的O(∩_∩)O~
