### ISSUE TITLE
实现clone模式的情况时，生成的id总为0

### ISSUE THREAD

**Issue by ZhouKanZ** [LitePalFramework/LitePal#276]
public class IAction extends DataSupport{
}

public class PointBean extends IAction implements Cloneable{
           .......
           xxxx
}

// 只在这一个地方用到克隆模式
public void addItem(PointBean point){
        PointBean pointBean = point.clone();
        pointBean.setType(1);

        pointBeanList.add(pointBean);
        notifyDataSetChanged();
}

**Comment by guolindev** [comment]
LitePal的实体类不支持使用clone方法，因为实体类继承的DataSupport里有很多必要的属性，无法被clone过去。所以建议你还是不要使用这种用法了。
