### ISSUE TITLE
 Expression tree is too large (maximum depth 1000) (code 1)

### ISSUE THREAD

**Issue by Li-Yuwei** [LitePalFramework/LitePal#277]
org.litepal.exceptions.DataSupportException: Expression tree is too large (maximum depth 1000) (code 1)
 很尴尬，该下班了老大给提了个bug，同步房产信息的时候，房间太多存到1000时候抛出bug

**Comment by Li-Yuwei** [comment]
我使用litepal得到SqliteDatabase实例，再用sqlite的原生方法保存成功了。需要把外键的id给保存里面

**Comment by guolindev** [comment]
这个错误是你的表达式过长，优化下你的表达语句，你用and或者or这样的语句循环拼接了超过1000次，SQLite处理不了这么长的表达式，所以报错了。

**Comment by Li-Yuwei** [comment]
我保存集合用的saveAll方法。
