### ISSUE TITLE
数据添加问题

### ISSUE THREAD

**Issue by panyingdaoz** [LitePalFramework/LitePal#278]
我的数据添加不是通过按钮添加的，是
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        KLog.e("onCreate被调用");
        setContentView(R.layout.activity_pl_video_view);

        addLitepal();//添加参数表
}
这样添加的，所以我每运行一次，就会添加一次数据，我应该怎么做才不会没运行一次就添加一次重复的数据？

**Comment by guolindev** [comment]
这是你自己程序逻辑控制的，和LitePal无关，你自己通过判断语句来进行控制就行了。
