### ISSUE TITLE
数据保存问题

### ISSUE THREAD

**Issue by grins2193285007** [LitePalFramework/LitePal#279]
我通过Gson 转成bean   然后保存数据库失败。数据库表已建好。请问是什么问题。 

 UserInfoBean bub = new Gson().fromJson(result, UserInfoBean.class);
                    bub.setPassword(mUserPassword);
                    boolean isSave = bub.save(); //返回false

以下是字段
    private String id;

    private String userId;

    private String status;

    private String phoneType;

    private String imei;

    private boolean mobileVerified;

    private boolean isLeader;

    private String department;

    private String position;

    private String passwrd;

**Comment by guolindev** [comment]
这样我也无法分析，你把save()方法替换成saveThrows()方法，看看程序具体报了什么错误，这样才能分析问题。
