### ISSUE TITLE
希望增加安全删除表内数据的功能

### ISSUE THREAD

**Issue by csbz17027** [LitePalFramework/LitePal#281]
DataSupport.deleteAll(XXX.class) 这个方法当表的数据量过大时会发生sql语句过长的错误，希望郭神的新增个安全删除表内数据的功能，比如删除这个表后再新增这个表？

**Comment by guolindev** [comment]
感谢反馈，已确认是个bug，我会在下个版本中修复掉。

**Comment by guolindev** [comment]
此bug已经1.6.1版本中修复。
