### ISSUE TITLE
关联表更新，外键丢失

### ISSUE THREAD

**Issue by ixjhuang** [LitePalFramework/LitePal#282]
表关联的关系是这样的：
table1     1 -> n    table2      分组与联系人是一对多
table2     1 -> n    table3      联系人与个人资料是一对多

现在需要将联系人从一个分组移动到另一个分组，理论上个人资料还是属于该联系人;
不过现在我将联系人对应分组的外键使用set修改（没有动表3）之后，联系人已移动到新的分组，查看数据库发现所有数据都还在，但是表3个人资料中对应联系人的外键变空了。

另外，将联系人设置新分组时，我使用update来修改发现数据并没有更新，使用save就更新了。
(已经注意setToDefault了，没有修改为默认值的操作。

问题1，如何让表3的外键不变？
问题2，为何不能采用update来更新外键？

不是很清楚发生了什么，所以来请教一下郭神，请郭神不吝指教。

环境是Android Studio 2.3.3， LitePal 版本1.6.0

**Comment by ixjhuang** [comment]
忽然想到了什么。。
我先验证一下。。
先谢谢郭神

**Comment by guolindev** [comment]
这个问题是你又重新打开的，之前的问题还存在吗？

**Comment by ixjhuang** [comment]
之前那个问题是因为我添加了一个新的boolean类型字段、然后没有判断是不是默认值。。后面忽然想到了，加上了一个判断之后就好了；
用的还是saveOrUpdate，不过因此也有一些疑惑，update应该是根据数据的id来确定的，不过我上面这个问题就是我没有修改id，但是用update不能set一个新的外键，用save才可以。
用update数据没有发生变化；用save，原本属于该联系人的资料的外键字段就空了。。

**Comment by guolindev** [comment]
update这个方法很多人不会用，可能我的设计思想有点问题吧，update主要是用在静态方法里的，实例调用update方法就要一个个去set值，你set了哪个才会更新哪个。而如果是调用save方法来更新实体的值，那就要看你现在的实例里面有哪些值，比如你说调用了save，该联系人的资料的外键字段就空了，那么你应该检查一下，你调用save的时候，这个实例还有联系人的资料的引用吗？如果没有的话，LitePal就会认为是你想清空它的。

**Comment by ixjhuang** [comment]
嗯嗯、不过我就是update了新的外键，联系人移动到了新的分组，查看数据库发现外键没有被修改。
是不是因为我的实例是从数据库直接findFirst()出来的，所以update没有用呢？但是也不应该啊、顶多是都update了才是。
采用save时，我是从数据库查出来然后set了新外键再save进去的，郭神这么一说，我忽然想起来之前郭神博客里写了litepal采用的是懒查询，也就是不会把资料的引用查出来了。
我再修改看下。

**Comment by guolindev** [comment]
是的，你可以用激进查询再试试，这样查的时候就可以把关联关系也一起查出来了。

**Comment by ixjhuang** [comment]
郭神，是这样，我这几天测试了，使用激进查询将关联关系都查出来，set新的外键然后再save就能够更新，而且资料也都还在、不存在外键丢失的情况，功能实现正常。
但是当想使用update时，set新外键之后update，联系人的外键都没有更新，不管我这个实例是findFirst()出来的，还是new出来一个新的空的实例。我只set了联系人的外键为新的分组，别的都没有set。

**Comment by ixjhuang** [comment]
今天我又尝试了一下，我发现使用saveOrUpdate、且明知会是update情形时，与直接使用update是不一样的。。
一步一步debug，具体表现是这样的：
仅修改联系人的某一属性（不是资料表中的），使用saveOrUpdate之后，对应分组的外键就空了，然后需要对分组进行一次saveOrUpdate，联系人表中对应分组的外键才又回来了。原因我分析是因为没有将联系人添加入分组中的list里。
但是，当我直接使用update时，我发现对应分组的外键并没有影响，没有变空。也就不需要对分组再进行一次saveOrUpdate。
所以我的疑惑是，saveOrUpdate中的update的实现方式和update不一样吗？不然为什么debug时候会有这种情况呢？

**Comment by guolindev** [comment]
是这样的，update()方法是不能用来更新外键的。

实际上绝大多数人update()方法的使用都搞错了，可能这也是我设计思想的问题，大家的用法和我设计的想法不一致。

建议你不要纠结于update()方法了，你甚至可以完全不使用它，当更新find出来的对象时，就用save()方法，其他情况可以直接用DataSupport.updateAll()或DataSupport.update()方法。实例的update()方法就别用了，我设计的不好，让太多人在这方面使用有误区。这个问题我就关了，别钻这一个牛角尖。
