### ISSUE TITLE
deleteAll  针对 julianday 时间比较 相关的  删除无效

### ISSUE THREAD

**Issue by louisgeek** [LitePalFramework/LitePal#287]
int deCount = DataSupport.deleteAll(Cache.class, "julianday(datetime('now','localtime'))*24*60-julianday(saveTime)*24*60 >= 30");

**Comment by guolindev** [comment]
你这个表达式有点复杂了，里面还用了很多SQL的函数，我估计应该支持不了。你可以试下用SQLiteDatabase的delete方法支不支持你的这种语句，如果SQLiteDatabase也不支持的话，那LitePal也支持不了。
