### ISSUE TITLE
update

### ISSUE THREAD

**Issue by fuliteng** [LitePalFramework/LitePal#288]
类里面的属性一样的时候，updateAll，两张表数据都更改了

**Comment by guolindev** [comment]
你这个问题描述的不清楚，我没有办法解答。updateAll需要传入表名的，你传入哪个表名就只会更新哪张表，不存在什么两张表数据都更改的情况。

**Comment by fuliteng** [comment]
@guolindev 就是两个类，里面属性一样。然后更改一张表数据，另一张表数据也发送改变了

**Comment by guolindev** [comment]
据我所知这是不可能的，能把你的类、字段，还有操作的代码贴一下吗？
