### ISSUE TITLE
请问多对多的两张表互相删除某一条数据怎么操作?

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#289]
如题, 可能标题表达得有点绕口, 情况是这样的: 我有个用户表和一个文件表, 他们的关系是多对多的, 主要是用来为用户做索引, 主要功能是防止不同用户下载相同的文件而造成空间浪费,,现在就是要删除的时候感觉使用起来不太好, 就是当某个用户删除这个文件的时候, 需要把当前用户和文件解绑, 也就是说两个表要互相删除他们的指向关系,我是通过直接操作中间表来实现的, 不知道有没有其他简便的方法?
try {
     DataSupport.deleteAll(MIDDLE_TABLE_1, "userbean_id=? and filebean_id=?", mUserBean.getId() + "", fileBean.getId() + "");
     } catch (DataSupportException | SQLException e) {
    DataSupport.deleteAll(MIDDLE_TABLE_2, "userbean_id=? and filebean_id=?", mUserBean.getId() + "", fileBean.getId() + "");
      }

这种方法总感觉有点不舒服,感觉有点舍本求末了, 由于创建中间表的表名不固定,可能是userbean_filebean,也可能是filebean_userbean; 所以我定义了两个常量, 当找不到表的时候会捕获异常进行表名切换, 虽然最终效果实现了, 但是感觉有点不舒服;

另外还有一点, 查询列表的时候(用户查找文件List或者文件查找用户List), 按照博客上的操作发现会报找不到列的异常,就是查询的时候调用:
`mUserBean = DataSupport.where(UserBean.F.W_USER_ID, mUserId).findFirst(UserBean.class, true);`
然后在Bean中的getFileList中重写:
`DataSupport.where("userbean_id=?", String.valueOf(id)).find(FileBean.class);`
如果这样调用的话会直接找不到列名, 现在我用的是激进查询法, 博客上说不推荐这种方法,但是现在我只能用这种了;

上面就是我遇到的问题,还请知情人指点迷津...

**Comment by guolindev** [comment]
其实你的用法就是非常正确的，因为你在调用deleteAll这种条件删除语句的时候，LitePal没有办法帮你把中间表的数据都删掉，这些数据如果不删也可以，反正也是废数据了，如果心里觉得不爽一定要删的话，其实就应该用你上面的方法。

只不过有一个规则你可能并不清楚，中间表的命名实际上是固定的，就是按两张表的字母表顺序来组成的，比如一张表叫book，一张表叫car，它们的中间表永远只会叫book_car，而不会出现car_book这种表名。

知道了这个规则，你就可以把代码中的catch部分删除掉了。

**Comment by xiexin52k** [comment]
多谢解惑! 另外, 在这个例子中, 某个用户要获取他的文件列表, 我直接用激进查询暂时没发现什么问题, 但是如果重写了UserBean中的getFileList方法,使用了您博客中说的懒加载方法, 我这里就会包找不到列名的异常,这是为什么呢? 会不会是新版本优化了这个问题,所以取消了懒加载?
您博客上的源代码
`public List<Comment> getComments() {  `
 `       return DataSupport.where("news_id = ?", String.valueOf(id)).find(Comment.class);  `
 `   }  `

**Comment by xiexin52k** [comment]
我在您的gitHub中的sample中发现并没有使用懒加载的方法,而是直接返回了list对象
