### ISSUE TITLE
批量数据插入或更新数据只能调用saveOrUpdate一条条插入吗？

### ISSUE THREAD

**Issue by wilson123** [LitePalFramework/LitePal#290]
批量数据插入或更新数据只能调用saveOrUpdate一条条插入吗？每次调用saveOrUpdate都是开启事务关闭事务，不能批量插入或更新的时候开启一次事务就好吗

**Comment by guolindev** [comment]
没办法，saveOrUpdate的API接口设计原因导致逻辑比较复杂，无法提供像saveAll()那样的批量操作接口，所以如果你有批量需求的话，还是别用saveOrUpdate()方法了，把逻辑分成两步来做，分别去处理save和update的逻辑。目前没有什么更好的方法解决。
