### ISSUE TITLE
save报错，无法新增

### ISSUE THREAD

**Issue by xue12311** [LitePalFramework/LitePal#291]
java.lang.ClassCastException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class
字段是这些，
private long id;
private String name;
private int age;
private boolean isMale;

litepal文件里面也加上了

Singer singer = new Singer(); 
singer.setAge(10);
singer.setName("小明");
singer.setMale(false);
singer.save();

**Comment by xiexin52k** [comment]
逻辑字段名字不对, boolean 的字段是 isMale, 但是你的setter 是setMale, litepal会认为列名是isMale,但是设置到Male字段上了...不单单是这个,所有的bean使用boolean类型的时候, 字段都应该避免用is开头,, 否则某些地方使用getter和setter都会有问题

**Comment by xue12311** [comment]
谢谢了，我先试试

**Comment by guolindev** [comment]
不好意思，java.lang.ClassCastException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class 这句报错和LitePal一点关系也没有吧，说的是你的这个类WildcardTypeImpl无法转换成Class，这也挺神奇的，我也很好奇你是怎么写的，但是这个错和LitePal一点关系也没有。

另外楼上说的，boolean避免用is开头，这个是错的，事实上boolean就应该以is开头。至于LitePal会自动查找的get set方法名，这个和IDE的生成规则是一质的，也就是说只要你用IDE来生成字段的get set方法，LitePal就可以自动识别。千万别手写，一手写就容易写错。
