### ISSUE TITLE
find 查找问题

### ISSUE THREAD

**Issue by zouxianbincc** [LitePalFramework/LitePal#293]
一对一，一对多，关系。永远find 不出来被包含的表内容。
public class A extends DataSupport {
    public long id;
    public String bc;
    public List<B> b;
}
public class B extends DataSupport{
    public long id;
    public String Name;
}

A 里包含了 List<B> 单独进行存：
// B-----------------
        B b = new B();
        b.setId(12);
        b.setName("B");
        List<B> bList = new ArrayList<>();
        bList.add(b);
        DataSupport.saveAll(bList);

 // A-------------------------
        A a = new A();
        a.setId(100);
        a.setBc("A");
        a.setB(bList);
        a.save();
        Log.e("test", a.toString());//log=A{id=1, bc='A', b=[B{id=1, Name='B'}]}
       

然后，进行查询:
List<A> as = DataSupport.findAll(A.class);
Log.e("test", as.toString()); //log=[A{id=1, bc='A', b=null}]

问题是为啥 都查不出B表的内容

**Comment by guolindev** [comment]
考虑到效率原因，关联表的内容要使用激进查询或者懒查询的方式来进行加载，具体可以参考这篇文章 http://blog.csdn.net/guolin_blog/article/details/40153833
