### ISSUE TITLE
偶尔出现ANR

### ISSUE THREAD

**Issue by houjinyun** [LitePalFramework/LitePal#295]
在有些机型使用中会偶发ANR，通过腾讯bugly查看的ANR信息定位到位置如下：
org.litepal.crud.DataSupport.findFirst(DataSupport.java:-1)
特别是第一次安装使用时，或者应用覆盖安装升级时，出现概率比较大。进程杀掉之后，重新打开就没问题。

**Comment by houjinyun** [comment]
通过bugly后台上传的ANR数据分析，发现是出现死锁了。我们的应用里有很多多线程操作数据库的地方，并且看到有其他朋友也反馈过类似问题，希望作者能重视起来。 @guolindev

**Comment by guolindev** [comment]
是bugly检测到的吗，有没有anr的详情日志，可以发给我看一下。
