### ISSUE TITLE
app黑屏问题

### ISSUE THREAD

**Issue by fishboil** [LitePalFramework/LitePal#298]
我在主线程使用拼的sql查询，同时在子线程有一个查询，这时候会主线程和子线程都卡住了，永远都不会继续执行下去了
1. Cursor cursor = UserMessage.findBySQL(“select *from UserMessage where uid = 1000 and messageType in (109,110) and operateResult=0  ”);
2.  List<Phone> list = Phone.where("isDefault=1").find(Phone.class);
使用的版本为最新的版本1.6.0,请问这种问题怎么处理？

**Comment by guolindev** [comment]
有没有日志，可能是发生死锁了。另外你哪个语句是在主线程执行，哪个语句是在子线程执行的，说明一下。

还有一点，不要使用Phone.where或者是UserMessage.findBySQL这样的用法，要用DataSupport.where和DataSupport.findBySQL方法。因为这都是DataSupport中的静态方法，锁是加在DataSupport.class上的，所以这也可能是造成问题的原因。
