### ISSUE TITLE
缺乏必要的Debug调试支持

### ISSUE THREAD

**Issue by ericxu1983** [LitePalFramework/LitePal#30]
虽然库用起来很方便，但是有些实现，例如版本升级到底是如何实现的，如果能把对应的sql语句大致打印出来，用户马上就明白了。

例如你博客上描述的删除一个字段采用将原先的表数据全部都迁移到新表的方式，对于有些应用可能会有性能风险。

如果能打印出来sql语言，如何实现一目了然，用户也可以更方便的使用你的库了。

国产的另外一个ORM库afinal，虽然没有litepal强大，但是他支持debug参数，设计上会更好些。

**Comment by sinyu890807** [comment]
litepal里面有log开关的，LogUtil这个类控制所有日志的打印，你把打印功能打开就能看到日志了。

**Comment by zengcanxiang** [comment]
@sinyu890807 我在Application中将LogUtil.level=LogUtil.DEBUG.但是，在执行方法的时候，没有日志打印.
1.4.1版本。

**Comment by houyidg** [comment]
尼玛的 垃圾啊，连最基本的sql打印都没有，国人的果然是为了功利

**Comment by yuan5632660** [comment]
为什么项目没有调试模式？ BuildConfig中debug=false无法修改
