### ISSUE TITLE
Can not able to pull data from database

### ISSUE THREAD

**Issue by reversecoder** [LitePalFramework/LitePal#300]
Hi,

I'm using below environment -

environment: android studio 3.0.0-beta7
target and compile sdk: 26
build tool: 26.0.2
support library: 26.1.0
runtime permission: WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE

I have successfully created and inserted data into database from my program, but when I am trying to get data from database using "DataSupport.findAll(User.class)" or "DataSupport.where("name = ?", "rashed").find(User.class)", it always crashes. I checked my database using "Sqlite data browser" and my desired data is exist there. Here are crash logs-

> 10-12 20:45:52.009 30763-30763/com.reversecoder.rb E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                      Process: com.reversecoder.rb, PID: 30763
>                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.reversecoder.rb/com.reversecoder.rb.activity.HomeActivity}: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
>                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
>                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516)
>                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:162)
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                          at android.os.Looper.loop(Looper.java:189)
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5528)
>                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
>                                                                       Caused by: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
>                                                                          at org.litepal.crud.DataHandler.query(DataHandler.java:153)
>                                                                          at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123)
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:1028)
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:994)
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedData(HomeActivity.java:334)
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedDataWithAdvertise(HomeActivity.java:378)
>                                                                          at com.reversecoder.rb.activity.HomeActivity.initUI(HomeActivity.java:136)
>                                                                          at com.reversecoder.rb.activity.HomeActivity.onCreate(HomeActivity.java:111)
>                                                                          at android.app.Activity.performCreate(Activity.java:5966)
>                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408)
>                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
>                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:162) 
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:106) 
>                                                                          at android.os.Looper.loop(Looper.java:189) 
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5528) 
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
>                                                                       Caused by: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
>                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:635)
>                                                                          at org.litepal.crud.DataHandler.query(DataHandler.java:138)
>                                                                          at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123) 
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:1028) 
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:994) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedData(HomeActivity.java:334) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedDataWithAdvertise(HomeActivity.java:378) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.initUI(HomeActivity.java:136) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.onCreate(HomeActivity.java:111) 
>                                                                          at android.app.Activity.performCreate(Activity.java:5966) 
>                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
>                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408) 
>                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
>                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:162) 
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:106) 
>                                                                          at android.os.Looper.loop(Looper.java:189) 
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5528) 
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
>                                                                       Caused by: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
>                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:635)
>                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
>                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
>                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
>                                                                          at org.litepal.crud.DataHandler.query(DataHandler.java:138) 
>                                                                          at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123) 
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:1028) 
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:994) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedData(HomeActivity.java:334) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedDataWithAdvertise(HomeActivity.java:378) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.initUI(HomeActivity.java:136) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.onCreate(HomeActivity.java:111) 
>                                                                          at android.app.Activity.performCreate(Activity.java:5966) 
>                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
>                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408) 
>                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
>                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:162) 
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:106) 
>                                                                          at android.os.Looper.loop(Looper.java:189) 
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5528) 
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
>                                                                       Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
>                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:688)
>                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
>                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946) 
>                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691) 
>                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633) 
>                                                                          at org.litepal.crud.DataHandler.query(DataHandler.java:138) 
>                                                                          at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123) 
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:1028) 
>                                                                          at org.litepal.crud.DataSupport.findAll(DataSupport.java:994) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedData(HomeActivity.java:334) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.getAllDeletedDataWithAdvertise(HomeActivity.java:378) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.initUI(HomeActivity.java:136) 
>                                                                          at com.reversecoder.rb.activity.HomeActivity.onCreate(HomeActivity.java:111) 
>                                                                          at android.app.Activity.performCreate(Activity.java:5966) 
>                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
>                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2408) 
>                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2516) 
>                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:162) 
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:106) 
>                                                                          at android.os.Looper.loop(Looper.java:189) 
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:5528) 
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950) 
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745) 
> 

Thanks in advance.

**Comment by guolindev** [comment]
This error log is weird. From the stack trace. I found LitePal can not get the constructor of your model class. Can you paste the codes of your User class? It will be helpful to analyze the problem.

**Comment by guolindev** [comment]
This bug is fixed in version 1.6.1.
