### ISSUE TITLE
重大bug急需

### ISSUE THREAD

**Issue by 179098051** [LitePalFramework/LitePal#302]
根据boolean 类型查询数据 查不到

**Comment by 179098051** [comment]
true 1  这样可以

**Comment by guolindev** [comment]
这个没办法，布尔值的数据，在数据库里面，1就是true，0就是false，只能这样使用。你用true或者false，数据库是不认识这是什么的，只会把它当字符串查。

**Comment by 179098051** [comment]
嗯 后面我明白了  谢谢 大佬细心解答我这菜鸟的问题
