### ISSUE TITLE
一对多怎么在保持“一”不变（id也不变）的情况下修改增加“多”呢？

### ISSUE THREAD

**Issue by qht1003077897** [LitePalFramework/LitePal#303]

**Comment by qht1003077897** [comment]
你好郭神，我现在存在A对B是一对多，B对C是一对多，为了维持A和B的关系在增加一个B时，先saveB，然后调用A的assignBaseObjId方法，然后saveA。这样在处理A、B的关系的时候没问题。但是同样应用在B和C上面时，save完B后导致B中A的外键变成空了。 求解答、

**Comment by qht1003077897** [comment]
调试了一下，发现应该是B和A的关联关系丢失了，是不是还要再重新save一下A呢？

结论就是：增加C，先saveC，再saveB，再saveA。

**Comment by qht1003077897** [comment]
并且建议郭神告知大家可以使用：
https://github.com/amitshekhariitbhu/Android-Debug-Database
去调试数据库，每debug一步，对应的数据就更新了，很方便。

**Comment by guolindev** [comment]
不是很明白你描述的操作，对象之间的关联关系litepal是会自动在数据库建立的，不需要你去调用assignBaseObjId方法。当你去调用C.save，B.save之后，如果B里有A的外键信息，那么不管你save几次都是不会丢失的。除非是你的B对象里没有A的外键信息，那么你再save一次，LitePal会帮你清理掉这个外键的关联。
