### ISSUE TITLE
Date类型字段比较和更新问题

### ISSUE THREAD

**Issue by mozc** [LitePalFramework/LitePal#304]
假如有个A表，有个modified_time的字段，Date类型。我遇到以下问题：
1、我想查询modified_time为指定日期（如：2017-10-20）或者指定时间段（如：2017-10-01至2017-10-20）的数据，应该怎么写查询语句？
2、我想更新modified_time字段，用似以下ContentValues方法更新，会有问题
ContentValues values = new ContentValues();  
values.put("modified_time", new Date().toString());  
DataSupport.update(A.class, values, 2); 

请教一下Litepal查询和修改Date类型字段的正确操作方法是什么？
谢谢！

**Comment by guolindev** [comment]
这个问题得涉及到底层了，我来说明一下。

第一个问题，当你的model里面有Date类型的字段时，LitePal会自动做一个转换，在数据库里面加入一个long型的列，你存储的Date的值到数据库中都会变成一个long型值（1970年1月1日0时起的毫秒数）。所以，如果你想查一个日期的区间，那么就把你的区间都转为long型值，然后再用大小于号查询就行了。

第二个问题，也是一样的道理。如果你是用save的方法来更新数据的，那么LitePal仍然会自动帮你把Date数据转成long型数据，然后存到数据库里。但如果是你用ContentValues的方式来更新数据的，那么只能由你自己来转了，你这样toString是肯定不行的，要用getTime才行。

**Comment by Liuhai123456** [comment]
> 这个问题得涉及到底层了，我来说明一下。
> 
> 第一个问题，当你的model里面有Date类型的字段时，LitePal会自动做一个转换，在数据库里面加入一个long型的列，你存储的Date的值到数据库中都会变成一个long型值（1970年1月1日0时起的毫秒数）。所以，如果你想查一个日期的区间，那么就把你的区间都转为long型值，然后再用大小于号查询就行了。
> 
> 第二个问题，也是一样的道理。如果你是用save的方法来更新数据的，那么LitePal仍然会自动帮你把Date数据转成long型数据，然后存到数据库里。但如果是你用ContentValues的方式来更新数据的，那么只能由你自己来转了，你这样toString是肯定不行的，要用getTime才行。

大佬，那对于创建时间这种推荐是用什么类型保存？
