### ISSUE TITLE
byte类型数据save()后为0

### ISSUE THREAD

**Issue by OumaSyuu** [LitePalFramework/LitePal#307]
您好，我这边用1.6.0有个问题：一个实体类里面有int，byte，String类型的数据，我调用save()更新数据，int跟String类型的可以保存，但是byte类型的数据就是为0（保存后立马find()看看数据库里面的情况）。是不是这个库不支持byte类型的数据？

**Comment by HeJianF** [comment]
LitePal 1.3.1发布了，从此支持图片存储！  http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=402155685&idx=1&sn=91a3223e1678a6962492400386266301&scene=19#wechat_redirect

存储二进制数据：
LitePal之前支持存储的数据类型有：int、long、short、float、double、boolean、char、String、Date九种，1.3.1版本中引入了第十种数据类型：byte[]。

**Comment by OumaSyuu** [comment]
明白了，我把byte类型的数据改为int类型吧。

**Comment by OumaSyuu** [comment]
截至1.6.0，LitePal并未支持Java byte类型。
