### ISSUE TITLE
kotlin 使用liteoal查询数据异常

### ISSUE THREAD

**Issue by Lesincs** [LitePalFramework/LitePal#308]
报错：org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
类是这样的：data class DBSubject(var movieId: String,var movieName: String, var imageUrl: String, var rating: Float) : DataSupport()
然后查询语句: val list = DataSupport.where("movieId= ?", activity.intent.getStringExtra(MOVIE_ID)).find(DBSubject::class.java)
运行就会报上面的错误 有办法解决吗 发现保存和删除数据没问题

**Comment by guolindev** [comment]
kotlin可能暂时还不支持，目前我还没有去研究kotlin，等支持的时候应该会发新版本的。

**Comment by yuewe** [comment]
可能是因为对应的data class没有空构造器，可以通过给对应的成员变量赋默认值就会有空构造器了。
