### ISSUE TITLE
建议添加表格级别的约束

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#309]
如题, 目前LitePal只支持字段约束,例如非空, 唯一约束等等.
但目前我们项目有个需求是需要多列联合约束,例如:
`1    1    ok`
`1    2    ok`
`2    1    ok`
`2    2    ok`
`1    1    no`
这样的效果LitePal好像无法实现;
我放一段我们的建表语句,您可以看一下:
`CREATE TABLE User (`
    `    id       INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,`
    `    userName VARCHAR NOT NULL,`
    `    url      VARCHAR NOT NULL,`
    `    UNIQUE (`
    `        userName,`
    `        url`
    `    )`
`);`
目前用的方法是save之前做一下逻辑判断, 这样数据多的时候影响效率

**Comment by guolindev** [comment]
是的，这个暂时只能用逻辑判断来实现，未来我会考虑加入这样的功能，谢谢建议。
