### ISSUE TITLE
如何支持索引？

### ISSUE THREAD

**Issue by ericxu1983** [LitePalFramework/LitePal#31]
对于有些应用，例如微信，可能数据量比较大，在查询聊天消息时，会用到索引，源代码中全局grep了一把，没有找到create.*index的语句，判断目前是否不支持索引？

**Comment by guolindev** [comment]
SQLite的查询速度是非常快的，而且手机一般不会存储太多的数据，像服务器数据库那样存储上亿数据的时候确实需要索引，但在手机端索引的必要性可能并不大。 我有做过测试，SQLite从100万条数据里面查询指定的内容可以在不到1秒内完成，而手机端一张表不太可能存储超过百万条数据，所以LitePal暂时没有支持索引的计划。
