### ISSUE TITLE
findAll(Class<T> modelClass, long... ids) 无法排序

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#310]
如题, 两张多对多关系表A和B, 通过中间表查询与A相关联的B的ids, 然后通过ids获取B的列表, 项目需求是要对这个B列表再根据某个字段进行排序. 发现LitePal并没有提供相关API. 通过源码知道, 默认根据id排序且无法更改, 郭神可不可以添一个筛选所有ids之后再根据特定字段排序的API呢?

**Comment by guolindev** [comment]
有的，你不要使用finaAll方法就可以了，比如你的model叫News，你就直接这样写：
`List<News> list = News.where("|).order("")` 这样就可以了。
