### ISSUE TITLE
查数据时,数据表内容被异常清空

### ISSUE THREAD

**Issue by zxyaust** [LitePalFramework/LitePal#311]
public class Departments extends DataSupport {
    public long id;
    public String name;
    public long school_id;

    public Departments(long id, String name, long school_id) {
        this.id = id;
        this.name = name;
        this.school_id = school_id;
    }
}
当我调用过下面这个代码之后,我数据表中所有的数据,除了id还在,其他字段全部为空了,不止到为什么
        Departments department = DataSupport.find(Departments.class, 1);

**Comment by zxyaust** [comment]
@sinyu890807 @guolindev

**Comment by zxyaust** [comment]
List<Departments> all = DataSupport.findAll(Departments.class);
执行这句代码也会清空这张表,不知为什么,其他的表都不会出问题,这张表,怎么查都会把数据内容全部置空 @sinyu890807 @guolindev

**Comment by guolindev** [comment]
这个我也不清楚了，没遇到过这种情况，除了清空数据之外有报错吗？
