### ISSUE TITLE
升级studio到3.0后报错

### ISSUE THREAD

**Issue by caizhibiao** [LitePalFramework/LitePal#313]
org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
                                                                    at org.litepal.crud.DataHandler.query(DataHandler.java:153)

**Comment by ximen502** [comment]
我也遇到这个错误。有没有解决方法？

**Comment by caizhibiao** [comment]
@ximen502  build variants里设置为release后编译运行呢？

**Comment by ximen502** [comment]
@caizhibiao 你说的build variants是什么意思？打包最后选择build type为release或debug吗？

**Comment by guolindev** [comment]
我升级了Android Studio 3.0，但是我无法重现这个问题，你们谁可以重现的能把更详细的日志发一下吗？

**Comment by guolindev** [comment]
或者可以加我的QQ 568617646，一起协助解决一下这个问题。

**Comment by caizhibiao** [comment]
11-24 18:29:08.290 19178-19178/com.lqr.wechat W/System.err: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
11-24 18:29:08.300 19178-19178/com.lqr.wechat W/System.err:     at org.litepal.crud.DataHandler.query(DataHandler.java:153)
11-24 18:29:08.300 19178-19178/com.lqr.wechat W/System.err:     at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
11-24 18:29:08.300 19178-19178/com.lqr.wechat W/System.err:     at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
11-24 18:29:08.300 19178-19178/com.lqr.wechat W/System.err:     at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)
11-24 18:29:08.300 19178-19178/com.lqr.wechat W/System.err:     at com.lqr.wechat.db.DBManager.getFriendById(DBManager.java:326)

**Comment by guolindev** [comment]
这段日志看不出来问题，只能知道是在DataHandler.java:153行抛出一个异常，没法定位为什么getParameterTypes()是null，虽然有可能是Android Studio 3.0改了instant run的规则导致的，但是我这边实在重现不了，真不知道要怎么解决，你能加下我QQ吗？协助我解决一下，谢谢了。

**Comment by guolindev** [comment]
此bug已在1.6.1版本中修复。
