### ISSUE TITLE
AS升级到3.0之后报错

### ISSUE THREAD

**Issue by jiang330227** [LitePalFramework/LitePal#314]
debug版本的时候报这个错误：org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
打包正式版本之后不会报错。

**Comment by lifeofwind** [comment]
问题原因找到了，和boolean无关，而是和你的类中有一个3个参数的构造函数有关。这是因为Android Studio的Instant Run会向Model里面注入一个带有2个参数的构建函数，而LitePal在用反射进行对象创建的时候会寻找参数最少的那个构造函数，如果你的Model中是一个3个参数的构造函数，那LitePal就会找错创建对象的方法，从而报出上面的错误。这个bug在1.4.0版本中已修复。

上面方法好像无效，环境是Android studio 3.0 LitePal 是5.0的。

被动解决方案，修改类构造函数，添加了一个默认构造函数就解决了，虽然还指不定会出上什么问题。

**Comment by guolindev** [comment]
我升级了Android Studio 3.0，但是我无法重现这个问题，你们谁可以重现的能把更详细的日志发一下吗？或者可以加我的QQ 568617646，一起协助解决一下这个问题。

**Comment by guolindev** [comment]
此bug已在1.6.1版本中修复。

**Comment by chengamin** [comment]
> 此bug已在1.6.1版本中修复。

但是在3.0这个版本中又有这个问题,如果类没有默认构造函数的话,还是会重复这个问题
