### ISSUE TITLE
能否指定表名去创建表和查询表的数据？

### ISSUE THREAD

**Issue by yaoxin2017** [LitePalFramework/LitePal#315]
目前创建表只能在xml中声明，我目前正在用你的数据库，有一个需求是需要动态创建表名和表字段，不能提前在xml中写好，但是没有找到可以自定义创建表的方法。
希望下个版本能加入该功能。

**Comment by guolindev** [comment]
这个功能支持的，看下这篇文章 https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650237709&idx=1&sn=1e9ee99617b2cb8f00af9b35eb83a637&chksm=88639a62bf14137450f5c98ec245362a0fef36e1bae1eaf12081d52d8b0e60a2c299e1699593#rd
