### ISSUE TITLE
#紧急#批量插入数据是否可以判断数据不存在就插入

### ISSUE THREAD

**Issue by RuanJH** [LitePalFramework/LitePal#319]
如题，因为每次进入APP都会请求接口下载要插入的数据，假如每次插入都会出现相同的数据，如何避免重复数据

**Comment by guolindev** [comment]
DataSupport里有一个saveOrUpdate()方法，你调用一个循环来去遍历你的数据集，每一个数据都去调用saveOrUpdate()方法方法就能判断数据不存在就插入，已存在就更新了。
