### ISSUE TITLE
  DataSupport.saveAllAsync(xzqhlist);保存问题

### ISSUE THREAD

**Issue by douya40** [LitePalFramework/LitePal#321]
在一个页面进行DataSupport.saveAllAsync(xzqhlist);再进入另一个页面，取到的值是空的

**Comment by guolindev** [comment]
在litepal.xml里面把这个配置项打开 <storage value="external" /> ，然后用在sd卡上查看一下数据库，看看数据到底有没有存储进去。如果存储进去了，把你的取值代码发一下，我才能看出来你取值方式有没有问题。

**Comment by KingLiuBin** [comment]
deleteAllAsync（）方法执行后 在 onFinish回调中 再执行存储方法 存不进去   进DB文件看了 确实没有数据

**Comment by guolindev** [comment]
这是两个问题。楼上的这个问题我先回答一下，delete了之后，你的数据model中的存储状态还没有清除，所以再存是存不进去的，调用一下DataSupport.markAsDeleted()方法，再去存储就可以了。

**Comment by guolindev** [comment]
再回答一下楼主的问题，LitePal中所有的Async方法，你如果不后接listen()是不会执行的。
