### ISSUE TITLE
一对多或者多对多的情况下,存入的数据并不是有序的,而是随机存储的?

### ISSUE THREAD

**Issue by tudou152** [LitePalFramework/LitePal#322]
public class News {  
    
    private List<Category> categoryList = new ArrayList<Category>();  
      
    // 自动生成get、set方法  
}  

public class Category {  
    ...  
    private List<News> newsList = new ArrayList<News>();  
      
    // 自动生成get、set方法  
}  

例如上面的例子,在新闻中存储Category的时候,是通过 getCategoryList.add(new Category()),来添加到数组中,这个添加是有顺序的,但是保存到本地数据库的时候,并不是按照这个添加的顺序来保存的,而是随机保存的,请问,这个是bug,还是本身存储的机制就是这样呢? 

因为我的需求是需要取出来的数据的顺序是按照添加的顺序来进行展示的,也是这种多对多的情况,仅仅设置一个用于排序的字段是无法解决需求的,最好的方式就是当存储的时候就是按顺序存储的,但是用这个数据库并没有理想的效果,所以请教一下大神,取出来没有顺序是正常的吗?

**Comment by guolindev** [comment]
把你完整代码发一下吧，没有随机存储这一说，应该还是你的用法有问题。首先上面的那段代码就有点问题，Category 类里面的List没有泛型，我不知道你是少打了，还是代码本身就是这样。但是我希望你提供给列的信息是准确的，这些疏漏都可能会造成我的误判。

**Comment by tudou152** [comment]
// 这就是我使用的两个类
// MediaListItem 代表的是一个媒体文件,可能是音频可能是视频
public class MediaListItem extends DataSupport {

    private long id;

    public long getId() {
        return id;
    }

    private List<PlayListItem> playListItems = new ArrayList<>();
}


//  PlayListItem 是播放列表对象,里面可以存储很多MediaListItem 对象
public class PlayListItem extends DataSupport {
    private long id;

    public long getId() {
        return id;
    }

    private List<MediaListItem> listItems = new ArrayList<>();

    public void setListItems(List<MediaListItem> listItems) {

        this.listItems = listItems;
    }

    public List<MediaListItem> getListItems() {

        return listItems;
    }
}

// 这个就是讲MediaListItem存入到PlayListItem中的方法
    public void saveToPlayList(PlayListItem playListItem, ArrayList<MediaListItem> selectedItems) {
        
        List<MediaListItem> itemToAdd = new ArrayList<>();

        /**
         * ArrayList<MediaListItem> mSelectedItems 里面的值的顺序是正确的
         * */
        for (MediaListItem listItem : selectedItems) {
            // 过滤掉选中的文件夹

            MediaListItem mediaListItem = DataSupport.find(MediaListItem.class, listItem.getId());
            itemToAdd.add(mediaListItem);
        }

        if (itemToAdd.size() > 0) {
            playListItem.getListItems().addAll(itemToAdd);

            for (MediaListItem listItem: itemToAdd) {
                playListItem.getListItems().add(listItem);
                playListItem.save();
            }

        }
        
        // 通过这个方法保存之后,selectedItems 存储的 MediaListItem对象的顺序,跟我在本地数据库表格中查询的顺序并不相同,而且找不出存储的规律
    }

**Comment by guolindev** [comment]
此问题已在LitePal 2.0.0版本中修复。
