### ISSUE TITLE
art问题

### ISSUE THREAD

**Issue by wilson123** [LitePalFramework/LitePal#323]
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=169 for 3.626s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=169 for 3.660s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=170 for 3.678s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=171 for 3.688s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=171 for 3.714s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=172 for 3.733s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=172 for 3.737s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=173 for 3.757s
W/art: Long monitor contention event with owner method=void org.litepal.crud.DataSupport$20.run() from DataSupport.java:1976 waiters=174 for 3.757s

**Comment by wilson123** [comment]
大量数据插入更新时出现

**Comment by guolindev** [comment]
可能要结合具体的用法才能知道什么原因，你能把大量数据插入更新的代码贴一下吗，

**Comment by wilson123** [comment]
floor.saveOrUpdateAsync(Floor.GATEWAY_ADDRESS + " = ? and " + Floor.FLOOR_ID + " = ?",
                gatewayAddress, "" + floor.floor_id).listen(null);

请求到许多数据（包含多个表），然后根据不同的表进行循环插入更新， 可能数据还没更新完又请求到数据来再更新

**Comment by guolindev** [comment]
这个是一个警告，表示线程执行时间过长，并且阻塞其他线程执行了。数据库操作同时只允许一个线程执行的，所以你有任务在执行时，这个时候LitePal会上锁，别的线程就只能等待，就会打印这样的日志了。这个日志不是LitePal的bug，你需要自己去优化代码执行逻辑。
