### ISSUE TITLE
update()巧遇字段被占用？

### ISSUE THREAD

**Issue by AdamHymn** [LitePalFramework/LitePal#324]
使用LitePal时，表字段命名有没有限制？有没有不能用的关键字？详情：我在项目中第一次用LitePal存储数据。在更新数据时发现，表中的11个字段，在update(1)第一条数据时，字段名part的内容没有被修改。debug跟进发现是11个字段的长度，但是却显示了10个字段的值。其中part=“demand”的内容消失了。怀疑表字段名命名有问题，修改为userPart之后，就好了。可以全部修改成功。

**Comment by guolindev** [comment]
据我所知，part并不是sql的关键字，如果是关键字的话，建表的时候就会崩溃了，而不会等到查询的时候。
我感觉应该还是你更新的用法有问题，你如果有兴趣的话，可以把你更新的语句贴出来看看，我再帮你分析分析原因。

**Comment by AdamHymn** [comment]
恩，谢谢了先。
业务介绍：先从接口接收json数据，封装到LoginBean.class。然后调用loginBean.update(1);
因为此表只存这一条数据，所以，第一次update时走else语句去save。以后每次更新第一条数据。
代码如下：
Gson gson = new Gson();
LoginBean loginBean = gson.fromJson(loginMsg, LoginBean.class);
  if (loginBean.update(1) == 1) {
     showToast(response.msg);
  } else {
             if (loginBean.save()) {
                         showToast(response.msg);
               } else {
                          loginBean.saveAsync().listen(new SaveCallback() {
                                    @Override
                                    public void onFinish(boolean success) {
                                        Log.e("loginBean", "saveAsyncOnFinish: " + success);
                                    }
                                });
                            }
                 }
}

**Comment by guolindev** [comment]
你的这个更新的用法是不规范的，不要这样使用，要不然可能会出现更多诡异现象。你可以使用静态的update方法，DataSupport.update()，然后把要更新的值通过ContentValues传进去，这样更新是安全的。

**Comment by AdamHymn** [comment]
恩 谢谢了
