### ISSUE TITLE
可以自定义主键而不是自增主键吗？

### ISSUE THREAD

**Issue by wanglaohushiwo** [LitePalFramework/LitePal#327]
我这边要和电脑端数据表一致，greendao明确指出不可以

**Comment by guolindev** [comment]
不好意思，这个功能不支持的。你可以自己定义一个和电脑端数据表一样的列，但不叫id就可以了。id是litepal内置的组件，这个无法修改。

**Comment by foreverma** [comment]
但是litepal的update方法不是传的id，但是这个id不是我控制的，那我的意思是要更新phonenumber为120的数据的时候怎么传入update（int id）这个id？
