### ISSUE TITLE
deleteAsync无效

### ISSUE THREAD

**Issue by imxy** [LitePalFramework/LitePal#328]
![image](https://user-images.githubusercontent.com/20613737/33871522-cb2e76e2-df4d-11e7-8856-6446591166a2.png)
使用 DataSupport.deleteAsync(Food::class.java, 5)方法不能删除数据，
delete方法可以成功删除
系统 MIUI9 android 7.1.1  和android5.0.2都不行

**Comment by guolindev** [comment]
所以Async方法都要后接listen才会执行，要不然是不会执行的。你可以不做具体的回调处理，但是必须得写。
`DataSupport.deleteAsync(Food::classs.java, 5).listen(null)`
