### ISSUE TITLE
是否可以在打包时将各个模块（组件）的assets中的litepal.xml文件合并为一个，并打包到apk中？

### ISSUE THREAD

**Issue by guiying712** [LitePalFramework/LitePal#333]
是否可以在打包时将各个模块（组件）的assets中的litepal.xml文件合并为一个？例如，A模块中有一个litepal.xml，B模块中也有一个litepal.xml，最后打包的时候将A和B模块的litepal.xml合并到最终的apk中。

**Comment by guolindev** [comment]
不需要配置多个litepal.xml文件，只需要在你的app模块下面配置一份就行了。
