### ISSUE TITLE
如果实体类中有字段为ClassName则无法save，报异常了

### ISSUE THREAD

**Issue by Htryhard** [LitePalFramework/LitePal#334]
private String ClassName;   
 public String getClassName() {
        return ClassName;
    }

    public void setClassName(String className) {
        ClassName = className;
    }

**Comment by guolindev** [comment]
把异常信息贴出来看一下，另外不建议使用这种敏感的字段名，换成点什么都好。还有，字段名尽量用驼峰模式，你这种命名是不规范的。

**Comment by Htryhard** [comment]
嗯嗯，因为用gson解析直接用服务器返回的字段了，现在换了字段名就好了，谢谢您。
