### ISSUE TITLE
bean的属性是中文，1万条数据批量插入，小米5耗时要15秒；

### ISSUE THREAD

**Issue by 5800LDW** [LitePalFramework/LitePal#337]
说明：
1. 用的是最新的库：org.litepal.android:core:1.6.1 ；

2.由于要根据后台返回的数据动态建表， 所以属性可能是中文， 
用litepal测试批量插入（ DataSupport.saveAll(collection) ），速度非常慢；
如果全部是英文的属性就速度正常；

3.用liteOrm这个Orm框架，在同一部小米手机，测试1万条同样的中文字段数据，批量插入， 测试两次，耗时在2s左右；

4.Bean的样式如下：
public class Note {

    private String ID号;
    private String 序号;
    private String 资产大类;
    private String 资产中类;
    private String 资产小类;
  //....省略 get set tostring 方法；

}

问题： 下个版本对中文字段的处理是不是需要优化？

**Comment by xiexin52k** [comment]
我的天... 你这是要生成excel不是生成sqlite吧...

**Comment by guolindev** [comment]
到不是10w条数据的问题，但是这个中文字段也太特殊了吧。我本来还以为是字段里面存了中文数据，结果你直接是把字段命名成了中文。这种需求太特殊了，我这边没有做过这种兼容，也不会考虑做这种兼容，很神奇你运行竟然没有报错。
