### ISSUE TITLE
How to put this into a new thread

### ISSUE THREAD

**Issue by xiaoxiaoyu** [LitePalFramework/LitePal#34]
我想要创建一个线程，然后在线程中批量添加数据。
但是我发现，我怎么做都会阻塞主线程，能帮我解决这个问题么。

**Comment by shugehao** [comment]
这个问题我也发现了，我请求完服务器数据的时候，使用litepal去存储数据，刚开始滑动listview的时候回出现卡顿的情况，定位了好长时间才发现原来是因为数据存储的问题，我是开了一个线程池在非主线程中执行的。但是还是会影响到主线程。而且开两个线程去执行保存操作的时候APP会出现没有响应的情况。数据库连接池抛出异常。

**Comment by zhouzhiqiangzzq** [comment]
楼上能发段代码么？

**Comment by shugehao** [comment]
这个代码：
executor.execute(new Runnable() {

											@Override
											public void run() {
												dao.deleteCloudCookBooks();
												for (CookBook book : list) {
													dao.saveCookBook(book, 1);
												}
											}

										});

/**
	 * 删除云菜谱缓存
	 */
	public void deleteCloudCookBooks(){
		List<CookBook>  list=getCloudCookBooks();
		if(list!=null){
			for(CookBook book:list){
				if(book.isDownload()){
				 long id=book.getId();
				 ContentValues values=new ContentValues();
				 values.put("flag", 0);
				 DataSupport.update(CookBook.class, values, id);
				}else{
					book.delete();
				}
			}
		}
	}


	public void saveCookBook(CookBook cookBook,int flag){
		cookBook.setFlag(flag);
		cookBook.setUserId(userId);
		List<CookBook> list=DataSupport.where("menuId=? and userId=? ",cookBook.getMenuId()+"",userId).find(CookBook.class);
		if(list!=null&&list.size()>0){
			ContentValues values=new ContentValues();
			values.put("flag",flag);
			DataSupport.update(CookBook.class, values, list.get(0).getId());
		}
		
		
		CookBookContent content=cookBook.getContent();
	    List<Ingredient>  mainIngredients= content.getMainIngredients();
	    List<Ingredient>  minorIngredients=content.getMinorIngredients();
	    List<MakeStep> makeSteps=content.getMakeSteps();
	    List<CookStep> cookSteps =content.getCookSteps();
	    if(cookSteps!=null){
	    	DataSupport.saveAll(cookSteps);
	    }
	    if(makeSteps!=null){
	    	
	    	DataSupport.saveAll(makeSteps);
	    }
	    if(mainIngredients!=null){
	    	for(Ingredient ingredient:mainIngredients){
	    		ingredient.setCategory(0);
	    	}
	    	DataSupport.saveAll(mainIngredients);
	    }
	    if(minorIngredients!=null){
	    	for(Ingredient ingredient:minorIngredients){
	    		ingredient.setCategory(1);
	    	}
	    	DataSupport.saveAll(minorIngredients);
	    }
	    content.save();
	    cookBook.save();
	}

**Comment by kingtami** [comment]
@gejiashu 后来怎么解决的?

**Comment by li-yu** [comment]
我也发现这个问题了，请问大家是如何解决的，谢谢！

**Comment by li-yu** [comment]
因为需求对于数据不是很敏感，所以我重写了saveAll方法，去掉了原先大部分的逻辑，只保留了insert部分，这样效率提升非常大，原先3s左右，现在800ms（当然，鬼都知道！），暂时的折中办法。供大家参考。

**Comment by li-yu** [comment]
使用RxJava解决卡顿问题

**Comment by guolindev** [comment]
LitePal 1.5.0版本开始支持多线程操作，到项目主页查看文档用法即可。
