### ISSUE TITLE
发现个bug，随便提交一下

### ISSUE THREAD

**Issue by KDL-in** [LitePalFramework/LitePal#340]
刚刚测试了一下发现，delete(xx.class,id) 就会级联删除外键联系的项
而 持久化对象.delete()或者deleteAll()都不会级联删除外键联系的项

**Comment by KDL-in** [comment]
顺便，错别字，抱歉

**Comment by guolindev** [comment]
设计如此，不是bug。

因为delete(xx.class,id)的时候，只会删掉一条数据，这个时候做级联很容易。
但如果是deleteAll()的时候，可能删掉的数据就是无限多了，如果这种情况下做级联删除，就得先把要删的所有数据全查询出来，然后一个个遍历，一个个删关联项，这个开销太大了，如果设计成这样，用户执行删除操作的时候可能会经常性卡死，从而造成更多bug。

所以这种情况下删除级联数据的工作就还是交还给开发者了，这个成本由开发者自行评估，不删的话也就是保留一些垃圾数据，并不会造成什么影响。
