### ISSUE TITLE
插件开发，插件中使用了LitePal做查询操作，报错getSharedPreferences(java.lang.String, int) on a null object reference

### ISSUE THREAD

**Issue by shuimuqinghua** [LitePalFramework/LitePal#347]
郭神，错误如下图。
采用了360的插件化框架开发（没用插件化框架是不报错的）
使用的LitePal版本是1.5.0
插件application继承了baseApplication,baseApplication继承了LitePalApplication
不知LitePal是否支持插件化开发？
![image](https://user-images.githubusercontent.com/7427087/34978218-766ad8e8-fad8-11e7-9882-a6b3020ff081.png)

**Comment by guolindev** [comment]
这种情况下不要继承LitePalApplication了，插件化的继承关系太危险了，Context能不能准确拿到都不清楚。

这种情况，你确保一个你认为100%安全的Application Context，然后调用LitePal.initialize(context)方法把context传给LitePal使用，只要你的context是没有问题的，那么LitePal就可以正常工作。
