### ISSUE TITLE
好像没有多表联合查询的API?

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#348]
如题, 有两个表, 关系是一对多, 郭神的blog上使用了一种懒加载方法:
`DataSupport.where("news_id = ?", String.valueOf(id)).find(Comment.class)`
但这只是在"一"中查询"多"的数据(即,在News中查询Comments);
现在我有个类似的需求, 有两个表, 一个Test, 一个Content, 它们也是一对多, 一个Test只有一个Content, 一个Content可以有多个Test;
这么说吧, Test是考试信息,存储了考试名字等资料, Content就是试卷文件, 两者合并为一套完整的评测;
第一天, 发布了一个TestA, 使用了ContentA;
第二天, 发布了一个TestB, 但是试卷仍然使用ContentA;
现在我想从TestA查询它的Content, LitePal好像没有这种反查的API,只能先从TestA中拿到Content_id的索引再将这个值传入到Content表中查询结果

**Comment by guolindev** [comment]
因为多表联合查询，最后生成的字段也是多个表的，没办法映射到单个对象当中，所以LitePal没有提供这样的API。

如果想实现多表查询，可以调用DataSupport.findBySQL()方法，然后通过传统SQL语句的方式查询即可。
