### ISSUE TITLE
About the error of the array

### ISSUE THREAD

**Issue by 793383996** [LitePalFramework/LitePal#35]
![qq 20150603162123](https://cloud.githubusercontent.com/assets/9602218/7955693/d8f7113a-0a0c-11e5-9fe1-a8906fe02855.png)
![qq 20150603162134](https://cloud.githubusercontent.com/assets/9602218/7955700/e550572a-0a0c-11e5-970e-640f1f86e422.png)

**Comment by 793383996** [comment]
My Email: 793383996@qq.com

**Comment by sinyu890807** [comment]
Sorry, array is not a supported type in LitePal. So your entity will be regarded as declared with no field. Then the error above will appear.
