### ISSUE TITLE
无法指定数据库存放到SD卡指定目录中。手动加急！！！！

### ISSUE THREAD

**Issue by mtjsoft** [LitePalFramework/LitePal#357]
能不能指定数据库存放的位置。想把数据库存放在SD卡指定的目录中。急需。

**Comment by mtjsoft** [comment]
**已经解决了。将litepal源码中的“Connector”类，修改数据库对应路径就OK了。注意，需要读写SD卡的权限。**
![default](https://user-images.githubusercontent.com/25857540/37402007-f0152310-27c4-11e8-950f-de55e9002dbf.png)

**Comment by topCard** [comment]
litepal有这个功能，看一下说明就知道了

**Comment by guolindev** [comment]
其实你也可以在litepal.xml的<storage>标签里面指定路径。

**Comment by gaoqiu** [comment]
> 其实你也可以在litepal.xml的标签里面指定路径。

怎么在litepal.xml的标签里面指定路径？急需解决
