### ISSUE TITLE
litepal设计有缺陷，麻烦郭神解答下

### ISSUE THREAD

**Issue by willBars** [LitePalFramework/LitePal#359]
例如：我在litepal.xml 开始设置了`` <dbname value= "AAAAA.db"/>
    <version value="4"/> <list>
        <mapping class="android.support.datasave.Category"/>
    </list>``
运行后，我再修改了dbname的值 和version的值如下``<dbname value= "BBBB.db"/>
    <version value="1"/>`` 
然后运行：就会抛出异常如下：
org.litepal.exceptions.InvalidAttributesException: the version in litepal.xml is earlier than the current version

此时，已经是新建一个数据库了，和上一个版本应该是剥离的，没有关系

**Comment by guolindev** [comment]
怎么说呢，你这种操作也算是自焚式的了，强行在升级的时候改成另一个数据库，这样你之前的数据库的数据也就都没了。litepal支持用更好的方式来实现多数据库，具体可以参考这里 https://github.com/LitePalFramework/LitePal#8-multiple-databases
