### ISSUE TITLE
how to use when I have multiple json structure 

### ISSUE THREAD

**Issue by priyanka9879** [LitePalFramework/LitePal#367]
Hi Thanks for awesome library and its working like charm . But I want to edit for multiple json data structure. Json data also continaing json data like.  

  {
                    "id": 14,
                    "user_id": 24,
                    "title": "He moved.",
                    "description": "Dodo said, 'EVERYBODY has won, and all must have been changed several times since then.' 'What do you know I'm mad?' said Alice. 'Nothing WHATEVER?' persisted the King. Here one of the other bit..",
                    "price": "28",
                    "price_type": 3,
                    "status": 1,
                    "is_completed": 0,
                    "completed_by_id": 0,
                    "created_at": "2018-03-11 16:41:48",
                    "updated_at": "2018-03-11 16:41:48",
                    "st_astext": "POINT(28.0599 41.0196)",
                    "distance": "83.77336311072",
                    "favs_count": 0,
                    "is_fav": 0,
                    "user": {
                        "id": 24,
                        "name": "cristopher.armstrong",
                        "email": "dhansen@nader.org",
                        "is_provider": 1,
                        "google_token": null,
                        "fb_token": null,
                        "mobile_no": null,
                        "profile_pic": null,
                        "about": null,
                        "overall_rating": "0",
                        "role_id": 2,
                        "social_token": null,
                        "status": 1,
                        "is_active": 0,
                        "email_verified": false,
                        "current_lang": "en",
                        "deleted_at": null,
                        "created_at": "2018-03-11 16:41:38",
                        "updated_at": "2018-03-11 16:41:38",
                        "address": {
                            "id": 23,
                            "user_id": 24,
                            "address": "987 Freddy Lights",
                            "pin_code": "123456",
                            "location": {
                                "type": "Point",
                                "coordinates": [
                                    29.0585,
                                    42.0187
                                ]
                            },
                            "status": 1,
                            "created_at": "2018-03-11 16:41:38",
                            "updated_at": "2018-03-11 16:41:38",
                            "city_name": "Hirthetown",
                            "state_name": "Connecticut",
                            "country_name": "Equatorial Guinea"
                        }
                    },
                    "address": {
                        "id": 14,
                        "post_id": 14,
                        "address": "abc",
                        "pin_code": "123456",
                        "location": {
                            "type": "Point",
                            "coordinates": [
                                28.0599,
                                41.0196
                            ]
                        },
                        "status": 1,
                        "created_at": "2018-03-10 16:41:52",
                        "updated_at": "2018-03-10 16:41:52",
                        "city_name": "Hirthetown",
                        "state_name": "Connecticut",
                        "country_name": "Equatorial Guinea"
                    },
                    "categories": [
                        {
                            "id": 14,
                            "post_id": 14,
                            "category_id": 2,
                            "status": 1,
                            "created_at": "2018-03-07 16:41:54",
                            "updated_at": "2018-03-07 16:41:54",
                            "category": {
                                "id": 2,
                                "title": "Medical",
                                "image_name": "Icon_Medical.png",
                                "image_path": "Icon_Medical.png",
                                "color": "#F21313",
                                "order": 2,
                                "status": 1,
                                "class": "medical",
                                "created_at": "2018-03-15 16:41:37",
                                "updated_at": "2018-03-15 16:41:37"
                            }
                        }
                    ],
                    "keywords": [],
                    "images": []
                },

They not saving data for categories keywords images. in User class object

**Comment by guolindev** [comment]
You should map your json data into models first. Using GSON or Jackson or FastJson will help you do that. After that, you can save your model into database by LitePal.
