### ISSUE TITLE
how to Upgrade litepal from sqlite,and not lose data

### ISSUE THREAD

**Issue by maliangxue** [LitePalFramework/LitePal#368]
when Upgrade litepal from sqlite,error:has no table_schema table,how to solve？

**Comment by guolindev** [comment]
Sorry. LitePal doesn't support to load data from legacy databases. If you really want to do that. You need to write your own migration logic. Read data from legacy databases by SQLiteDatabase and save all the data by LitePal. After that LitePal can maintain all the later upgrade operation without losing any data.

**Comment by maliangxue** [comment]
I have a question,how to use litePal to create index ,looking forward to your reply
