### ISSUE TITLE
打包混淆配置

### ISSUE THREAD

**Issue by dhcai** [LitePalFramework/LitePal#37]
打包混淆的时候报错，希望能增加一个打包混淆配置说明

**Comment by openproject** [comment]
-dontwarn org.litepal.**
-keep class org.litepal.** { *; }
即可

**Comment by ningxz** [comment]
混淆后，数据库关联表的字段出现错误：

例如两个表news 和 comments关联：

混淆前 comments表会自动生成外键news_id

混淆后外键生成在news表里，comments_id

以下是我在实际项目遇到的错误：
 android.database.sqlite.SQLiteException: table questionreplyinfo has no column named userquestioninfo_id (code 1): , while compiling: INSERT INTO questionreplyinfo(authortype,createtime,updatetime,desc,authortitle,questionreplyid,authornickname,questionid,userquestioninfo_id) VALUES (?,?,?,?,?,?,?,?,?)
原因就是上述混淆前后，外键在不同的表里引起的，不知道郭神能不能帮忙分析改进一下

**Comment by 15189611** [comment]
请帮忙说下打包混淆~~谢谢

**Comment by sinyu890807** [comment]
这样写就可以了：

-keep class org.litepal.** {
*;
}

-keep class * extends org.litepal.crud.DataSupport {
*;
}
