### ISSUE TITLE
LitePal有考虑数据库并发操作的情况吗

### ISSUE THREAD

**Issue by chaychan** [LitePalFramework/LitePal#370]
android.database.sqlite.SQLiteDatabaseLockedException database is locked (code 5): , while compiling: PRAGMA journal_mode 

这是项目报的错，查了一下是由于数据库有并发操作导致的，需要等待前一个完成后再执行下一个操作，请问LitePal有这种处理吗？

**Comment by guolindev** [comment]
SQLite数据库是不支持并发处理的，同时执行多个数据库操作的时候数据库会自动上锁。但是使用LitePal的API操作数据库时，LitePal会自动加上同步锁，等待上一个数据库操作释放了之后再执行下一个数据库操作。

**Comment by ooftf** [comment]
> SQLite数据库是不支持并发处理的，同时执行多个数据库操作的时候数据库会自动上锁。但是使用LitePal的API操作数据库时，LitePal会自动加上同步锁，等待上一个数据库操作释放了之后再执行下一个数据库操作。

你这个同步锁，是不支持多进程的把。
