### ISSUE TITLE
按照书上正常配置后 LitePal.getDatabase(); 闪退

### ISSUE THREAD

**Issue by fhwustc** [LitePalFramework/LitePal#375]
检查过很多遍配置没有问题，别的都注释掉，一写这条语句就闪退，注释掉正常运行，不知道为什么，log日志也没显示问题。
代码如下：
public class MainPage extends AppCompatActivity implements View.OnClickListener{

    private TextView custom_random_btn;
    private TextView default_random_btn;
    private TextView search_around_btn;
    private TextView almanac_btn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        if (Build.VERSION.SDK_INT >= 21) {
            View decorView = getWindow().getDecorView();
            decorView.setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                    | View.SYSTEM_UI_FLAG_LAYOUT_STABLE);
            getWindow().setStatusBarColor(Color.TRANSPARENT);
        }
        setContentView(R.layout.activity_main_page);
        //Toast.makeText(MainPage.this,"test",Toast.LENGTH_LONG).show();
        LitePal.getDatabase();

/*
        ActionBar actionBar = getSupportActionBar();
        if(actionBar != null){
            actionBar.hide();
        }
*/
        custom_random_btn = (TextView)findViewById(R.id.custom_random);
        default_random_btn = (TextView)findViewById(R.id.default_random);
        search_around_btn = (TextView)findViewById(R.id.search_around);
        almanac_btn = (TextView)findViewById(R.id.almanac);

        custom_random_btn.setOnClickListener(this);
        default_random_btn.setOnClickListener(this);
        search_around_btn.setOnClickListener(this);
        almanac_btn.setOnClickListener(this);
        //Log.d("main","done");

    }

    public void onClick(View v){
        switch (v.getId()){
            case R.id.custom_random:
                Intent intent = new Intent(MainPage.this,Custom_random.class);
                startActivity(intent);
        }
    }

}

配置如下：
<application
        android:name="org.litepal.LitePalApplication"
    ……

    <dbname value = "Random_db"/>
    <version value = "3" />
    <list>
        <mapping class="com.test.nick.random.db.N_pick_1_thing"/>
        <mapping class="com.test.nick.random.db.Random_object"/>
        <mapping class="com.test.nick.random.db.N_pick_m_thing"/>
        <mapping class="com.test.nick.random.db.Random_sort_thing"/>
        <mapping class="com.test.nick.random.db.N_give_m_thing"/>
    </list>

compile 'org.litepal.android:core:1.5.1'

每个数据表都extens DataSupport了。
之前写的程序用了都没问题，就这个程序出了问题，并不知道为什么，请求大神解答。

**Comment by guolindev** [comment]
日志放出来看看

**Comment by fhwustc** [comment]
我的错郭神，我光顾着看文件内有没有错误了，结果发现是assets文件夹名打成了assests。重新弄了几十遍也没发现，真的很抱歉带来了麻烦。
