### ISSUE TITLE
save 保存异常

### ISSUE THREAD

**Issue by 986204478** [LitePalFramework/LitePal#379]
场景是这样的。
1、我先查出一个User u1
2、然后删掉了所有User
3、然后调用 u1.save() 返回的是true,但是实际上没有保存成功。

**Comment by guolindev** [comment]
因为没有调用delete()方法删掉的u1，在litepal内部对于u1的保存状态还是true的，如果你没有通过litepal的api进行删除，需要主动通知litepal保存状态已修改才行。调用u1.clearSavedState()方法就可以了。
