### ISSUE TITLE
Why can't this method 'save' to update data?

### ISSUE THREAD

**Issue by 793383996** [LitePalFramework/LitePal#38]
![image](https://cloud.githubusercontent.com/assets/9602218/8470887/8966dfa0-20c4-11e5-8309-b378a93cd874.png)
![image](https://cloud.githubusercontent.com/assets/9602218/8470895/a3ce8cbc-20c4-11e5-9aef-d3a53806ecbf.png)
![image](https://cloud.githubusercontent.com/assets/9602218/8470899/afcfe40c-20c4-11e5-9a7f-2c18e3c0d51e.png)
Why can't this method updates the object "save"?
I can't Understand

**Comment by 793383996** [comment]
793383996@qq.com

**Comment by sinyu890807** [comment]
You don't need the updateAll method, just using save method will be enough.
