### ISSUE TITLE
Mymodelclass.save return false 

### ISSUE THREAD

**Issue by matin441** [LitePalFramework/LitePal#382]
hi and thanks for develping this liberery

I,m use this librery in my project and Observe all works that I just do , then Myclass.save() return false and when I am using Savethrow function and get Exception  in try/catch return Exception  (Java.lang.nullpointer)
please help me

**Comment by guolindev** [comment]
You can paste your stacktrace here so i can help you, or i can't analyze why null pointer exception happens.
