### ISSUE TITLE
数据删除后无法再次保存，调用clearSavedState（）也没用

### ISSUE THREAD

**Issue by luyun181** [LitePalFramework/LitePal#386]
类1

 UserInfo userInfo = DataSupport.find(UserInfo.class, 1);
                if (userInfo!=null){
                    if (userInfo.isSaved()){
                        userInfo.delete();
                        userInfo.clearSavedState();
                    }
                }

类2
   userInfo.clearSavedState();
                            userInfo.save();

但是
UserInfo userInfo = DataSupport.find(UserInfo.class, 1);
查找出来的userino还是null。
是哪里写的不对吗？》

**Comment by guolindev** [comment]
你第二次查询的时候不能再用id 1查询了，删除之后再次save，id肯定会变成2了。所以你这个问题的原因没有搞明白，不是删除之后无法再次保存，是已经保存成功了，只是你没查出来而已。
