### ISSUE TITLE
How can a Blob object be used?

### ISSUE THREAD

**Issue by suarezu** [LitePalFramework/LitePal#39]
Hi,

Thank you for such a great tool but I couldnt use Blob for column type. Am I wrong or you just missed this feature?

Kindest regards,
Nessus.

**Comment by sinyu890807** [comment]
Sorry about this. LitePal doesn't support blob type currently. But gonna support it in the coming versions. For now, you can save binary files at an absolutely path, and save the path in database.

**Comment by suarezu** [comment]
Thank you sincerely for the late reply:p. I just amended it to support blob, and made @Column(nullable/unique) work.Kindest regards, Nessus.

Date: Sat, 15 Aug 2015 03:26:53 -0700

**Comment by sinyu890807** [comment]
Supoorted since 1.3.1 version. you can read docs for more details.
