### ISSUE TITLE
LitePalSupport#setToDefault(String fieldName)的作用是啥?

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#390]
我看这个函数的注释有点奇怪哈,
这个函数就是说在update之前必须调用一下setToDefault吗?
那我用呢那么久错误的方法???😰😰😰😰😰

**Comment by guolindev** [comment]
看一下这个issue你就明白了 https://github.com/LitePalFramework/LitePal/issues/32
