### ISSUE TITLE
id 冲突

### ISSUE THREAD

**Issue by Wkongge** [LitePalFramework/LitePal#392]
LitePal 默认是以“id” 为主键的，但是项目中Model 通常会有自己的id值，这时就没法保存Model的 id值了

**Comment by guolindev** [comment]
id是litepal内部的关键字，把你们项目中model的id改个名字即可，例如serverId, userId, newId, feedId, commentId随便怎么定义都可以。如果是用gson解析之类的功能，加个@SerializeName注解就能转换映射了。
