### ISSUE TITLE
在执行save( )函数时，抛出异常：java.lang.NumberFormatException: s == null

### ISSUE THREAD

**Issue by CodingCattwo** [LitePalFramework/LitePal#394]
>  public static ArrayList<MatchModel> handleDateResponse(String response){
        try {
            ArrayList<MatchModel> tempList = new ArrayList<>();
            JSONObject jsonObject = new JSONObject(response);
            JSONArray jsonArray = jsonObject.getJSONArray("matchData");//获取该日期下的比赛数组
            Log.d("HTTP","array size " + jsonArray.length());
            for(int i = 0; i < jsonArray.length();i++){
                MatchModel tempMatchModel = new MatchModel();
                String matchDateContent = jsonArray.getJSONObject(i).toString();
                Match tempMatch = new Gson().fromJson(matchDateContent, Match.class);
                //复制到MatchModel并且保存到数据库，所有变量均为String类型
                tempMatchModel.setMatchDate(tempMatch.date);
                tempMatchModel.setBetEndTime(tempMatch.betEndTime);
                tempMatchModel.setPrimaryId(tempMatch.id);
                tempMatchModel.setMatchHash(tempMatch.contractHash);
                tempMatchModel.setTeamLeft(tempMatch.teamLeftName);
                tempMatchModel.setTeamLeftLogo(tempMatch.teamLeftLogo);
                tempMatchModel.setTeamRight(tempMatch.teamRightName);
                tempMatchModel.setTeamRightLogo(tempMatch.teamRightLogo);
                tempMatchModel.setMatchBeginTime(tempMatch.matchBeginTime);
                tempList.add(tempMatchModel);//加入到List中
                **tempMatchModel.save();**
            }
            return tempList;
        }catch (Exception e){
            e.printStackTrace();
        }

大致的错误报告为：
>  java.lang.NumberFormatException: s == null
at java.lang.Integer.parseInt(Integer.java:570)
at java.lang.Integer.parseInt(Integer.java:643)
at org.litepal.parser.LitePalParser.usePullParse(LitePalParser.java:160)
 at org.litepal.parser.LitePalParser.parseLitePalConfiguration(LitePalParser.java:102)
...

**Comment by guolindev** [comment]
这个问题应该是因为你的litepal.xml中没有配置<version>版本号，所以解析的时候失败了，按照litepal的要求来配置litepal.xml文件即可解决。
