### ISSUE TITLE
int 数据更新不生效

### ISSUE THREAD

**Issue by yuhanXie** [LitePalFramework/LitePal#397]
使用的2.0版本，在当前页面通过find方法获取list数据，更新第一条数据中的一个int值后，保存，返回保存成功。进入下一个页面后，再返回，重新查询，发现数据没有更新。
  还没找到问题原因。。

**Comment by WANZIzZ** [comment]
用` LitePal.update`试试，我刚才也是`find`以后，用`save`来更新，之前的都没问题，现在有一条数据更新不成功，返回值是true，用`update`之后更新成功了。

**Comment by guolindev** [comment]
https://github.com/LitePalFramework/LitePal/issues/32
