### ISSUE TITLE
java.lang.IllegalArgumentException: Service Intent must be explicit

### ISSUE THREAD

**Issue by xxchenqi** [LitePalFramework/LitePal#399]
compile 'org.litepal.android:core:2.0.0'
依赖之后采用隐式启动服务就报这个错误。
去除依赖后就不会报错。

**Comment by guolindev** [comment]
这是android 5.0系统之后禁止使用隐式service报的错，你应该查的是你的代码里面哪里使用了隐式service，和litepal没有关系，litepal中没有使用任何service，也没有任何Intent。

这个链接可能会帮到你 https://stackoverflow.com/questions/27842430/service-intent-must-be-explicit-intent
