### ISSUE TITLE
可以把里面经常需要继承的类写一个功能一样的接口吗

### ISSUE THREAD

**Issue by HAHH9527** [LitePalFramework/LitePal#401]
因为Java的只能单继承多接口
有时候需要继承其他的东西
导致需要使用像LitePalSupport这一类的功能类的时候
可能会变的异常复杂
如果同时提供接口和可继承的类
这样有就会变的稍简单一些

可能的场景：
    某天气SDK 封装了自己的实体类
    然后我需要储存这些实体类
    本来需要的操作：自己写一个对应的实体类，再把所有的属性再复制进来，再继承LitePalSupport
    如果有接口：自己写一个对应的实体类，继承SDK中的实体类，导入LitePalSupport接口

    这种实体类 通常是因为结构及其复杂 所以在JAR中写好提供给用户使用
    所以自己复制一遍实体类会挺麻烦的

**Comment by guolindev** [comment]
好的，看上去像是一个不错的建议，我会考虑在下个版本中进行类似的实现，感谢反馈。
