### ISSUE TITLE
改了实体类，数据库升级，所有的数据都没有了？

### ISSUE THREAD

**Issue by huangsanm** [LitePalFramework/LitePal#403]
把实体类改了，并且修改了litepal.xml中的version，对数据库做了升级
后面发现之前的数据都没有了？
因为升级了数据库，所以数据都没有了？
刚刚看了源码
所以每次升级都是先把之前的数据库干掉，然后再重新创建：
/**
	 * Upgrade tables to make sure when model classes are changed, the
	 * corresponding tables in the database should be always synchronized with
	 * them.
	 * 
	 * @param db
	 *            Instance of SQLiteDatabase.
	 */
	static void upgrade(SQLiteDatabase db) {
		drop(db);
		create(db, false);
		updateAssociations(db);
		upgradeTables(db);
		addAssociation(db, false);
	}

**Comment by guolindev** [comment]
这是不可能的，你突然丢出个问题出来我也不好解释是什么原因，有可能是你的项目工程逻辑太复杂，哪里出错也查不清楚。你可以尝试建一个空的项目，然后专门来测试升级这个功能，数据是不可能都被干掉的。

至于你发的这段代码，upgrade的第一行虽然是个drop方法，但是你可以点进去这个drop方法看一看

`	
        /**
	 * Drop the tables which are no longer exist in the mapping list but created
	 * before.
	 * 
	 * @param db
	 *            Instance of SQLiteDatabase.
	 */
	private static void drop(SQLiteDatabase db) {
		Dropper dropper = new Dropper();
		dropper.createOrUpgradeTable(db, false);
	}
`

看一下注释，只drop table只是把mapping list中不存在的table drop掉，也就是litepal.xml中没有配置的实体类对应的表。这个功能的意思是如果你升级数据库版本的时候删除了一个实体类，那么litepal会自动帮你删除对应的表。

**Comment by 15863459070** [comment]
请问是什么原因找到了吗
