### ISSUE TITLE
关于继承类的引用问题

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#405]
说一下情景:
    有一个类A, 和一个类B, 他们的关系是一对多, 即A中有一个`List<B>` 的引用,
   由于A有个Type字段区分不同类型, 为了数据清晰, 我又根据type建立了不同的表, 他们都继承了A,
    这样就产生了A1,A2,A3...等等子类. 但是在这些子类中, 我并不能拿到B的数据, 在B中也拿不到A1,A2...等等子类的数据, 碰到这种情况如何解决?

**Comment by guolindev** [comment]
首先，A1，A2，A3中拿不到B的数据这是不可能的，你的A1，A2，A3既然继承自A，A中声明的B的引用，A1，A2，A3为什么会拿不到？除非你声明成了private，如果是这样的话，你只需要把private改成protected即可。

B中无法获取到A1，A2，A3中的数据，这个就是你自己的设计问题了，如果你的B需要引用A1，A2，A3的数据，那么你应该在B类中声明A1，A2，A3，而不应该声明A，你既然声明A，那么就说明你的B里只需要引用父类A中的数据，而不在乎子类中有什么数据。
