### ISSUE TITLE
Managing Multiple Databases

### ISSUE THREAD

**Issue by urieltapiwa** [LitePalFramework/LitePal#407]
Please provide documentation on managing multiple databases.
1. Switching back and forth between the database you create programmatically. Right now you're only providing ways on creating a new database and switching back to the default. What about if i want to switch again to the new database i just created after having gone back to the default.
2. Also how do i change my default database to the newly created database.

**Comment by guolindev** [comment]
The fuctions you mentioned are totally supported and it's all on the doc.

If you want to switch back to the default database, you can use LitePal.useDefault().

If you want to swtich to any database you created, just use LitePal.use(). This method will create a database if it's not exist, or just switch to it if it's already exist.
