### ISSUE TITLE
存储省市区三级列表失败

### ISSUE THREAD

**Issue by 1033938503** [LitePalFramework/LitePal#408]
我想将省市区三级列表存储到数据库，我使用的是同步存储和查询，部分数据会漏掉，保存不完整，我要怎么解决这个问题？

**Comment by guolindev** [comment]
这个问题应该是你具体逻辑该如何控制，和litepal库本身是没有关系的，建议你可以参考《第一行代码 第2版》第14章的解决方案，有存储省市区三级列表的示例。
