### ISSUE TITLE
#1433 android.database.sqlite.SQLiteDatabaseLockedException

### ISSUE THREAD

**Issue by chaimengmeng** [LitePalFramework/LitePal#410]
![default](https://user-images.githubusercontent.com/29972143/43054545-a79f4046-8e64-11e8-9871-be1a3239f510.png)

在application：代码：
   //数据库
   LitePal.initialize(this);
   SQLiteDatabase db = LitePal.getDatabase();  //生成表

**Comment by guolindev** [comment]
由于问题久远没有回复，先将issue关掉了，还有疑问的话请再重新打开。
