### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by yangmao1986** [LitePalFramework/LitePal#411]
你好
代码中执行DataSupport.findBySQL("select * from tabname");
有没有会可能抛出这种java.util.ConcurrentModificationException异常。
我们在跑压力测试时发现了很多这样的异常

**Comment by guolindev** [comment]
这个有可能是同步锁问题导致的，过去的同步锁写法确实有问题，现在LitePal 2.0重写了所有的同步锁功能，你可以升级一下2.0版本再试试，应该不会再出现这个问题了。
