### ISSUE TITLE
B继承A建表  list<String> 无法生成b_string关联表

### ISSUE THREAD

**Issue by DQ2020** [LitePalFramework/LitePal#412]
很喜欢litepal 也一直在用 之前遇到的问题也得到大神的解决
现在出现一个新问题
A继承LitePalSupport
A中一个List<String> str    
protected public都试过
B继承A
A中包含B对象
mapping A
mapping B
重写A的Save方法 在方法中保存B 
开始保存A
save()时会先保存B
保存B返回false 异常：找不到 b_str表

注：如果B中覆盖List<String> str   找不到 b_str表异常会消失 
直接查询B表
但是查出来的B list中数据是重复的 
已确认存数据的时候B的str中只有1条数据 查出来是2条相同的
望提示一下如何解决？ 谢谢

**Comment by DQ2020** [comment]
最后查询B是直接查询的B表  不是A中的B

**Comment by guolindev** [comment]
这确实是个bug，但是我有必要解释一下。

因为从关系型数据库的设计上来讲，对象中的List结构在表中只能被解析成关联表，也就是一多对关系。而关联表都是需要两张表的，所以如果是List<Person>，那么就需要有一张Person表，如果是List<News>，那么就需要有一张News表。

但是List<String>这个时候是特殊的，因为开发者是无法定义一个String实体类的，所以也不会存在String表，这个情况下在数据库里是建立不了一多对关系的，LitePal在过去也就不支持List<String>这种数据结构。

后来也是很多网友提出了这个问题，于是在1.4.0版里面，我想办法加入了这个功能，方式是如果在A类中发现了List<String> strs这样的定义，就自动建立一张a_string表，表中有a_id和strs这两列，strs用于存储List<String> strs里面的具体值，a_id用于记录和哪条A对象之间做关联。

上面的这种方式虽然能实现List<String>、List<Integer>等等之类的包装数据类型值的存储和读取，但其实整体的设计还是很脆弱的，就比如你这种继承的用法，一下子就把整个的设计结构全摧毁了。因为在建表时我是无法检测出来有哪些类是继承了A类的，并且给每一个继承的类再去建一个继承类_string表，这在实际环境中是不可能的。

所以使用这个功能时请慎用，尤其是继承的时候要慎之又慎，我相信你的需求肯定有更好的数据结构方式能实现，在这个点上就不要难为我了。
