### ISSUE TITLE
LitePal.saveAll（集合）保存失败

### ISSUE THREAD

**Issue by JJC319** [LitePalFramework/LitePal#413]
List<MfAzjPlans> l1 =new ArrayList<>();

public class MfAzjPlans extends LitePalSupport implements Serializable {
    private static final long serialVersionUID = 2183936340620843182L;

    @Column(ignore = true)
    private int groupPosition;

    private String plan_id;//计划编号
    private String plan_date;//计划检查时间
    private String created_by;//计划创建人（返回id或name）
    private String created_at;//计划创建时间
    private List<MfAzjTasks> tasks = new ArrayList<MfAzjTasks>();//计划里的任务
}

public class MfAzjTasks extends LitePalSupport implements Serializable {
    private static final long serialVersionUID = -3351544898593250449L;

    private String plan_id;//任务所属计划id
    private String task_id;//任务编号
    private String project_id;//所属工程ID
    private String project_name;//所属工程name
    private String group_id;//执行小组（中文名称）
    private String stages;//检查阶段
    private String plan_date;//计划检查时间
    private String out_of_plan;//是否计划外  1否  0是
    private String remarks;//备注

    private MfAzjPlans mfAzjPlans;
}

 LitePal.saveAll( l1) 出现tasks 无法保存到数据库中

**Comment by guolindev** [comment]
保存具体报的什么错呢？
saveAll()方法其实就是在内部帮你开启允许逐条存储，所以一般saveAll()出错的话，说明你的单条数据存储也是有问题的，可以往这个方向查一下。

**Comment by guolindev** [comment]
长期无回复，已将问题关闭。
