### ISSUE TITLE
数据库初始化和升级

### ISSUE THREAD

**Issue by JakeHao** [LitePalFramework/LitePal#414]
郭神,能否加一个数据库初始化和升级的监听呢

**Comment by guolindev** [comment]
你说一下你具体的需求和目前LitePal为什么无法实现你的需求的原因吧，我根据情况来一下是否需要新增功能来满足你的需求。

**Comment by JakeHao** [comment]
1.在数据库初始化的同时,创建一些数据到表中
2.数据库升级的时候, 对之前的数据执行一些操作

**Comment by guolindev** [comment]
好的，我会在下个版本里面加入监听数据库创建和升级的接口，你关注这个issue就可以了，等新版本发布的时候我会把这个issue关闭。

**Comment by JakeHao** [comment]
ok，感谢

**Comment by YanYanLun** [comment]
@guolindev 感谢

**Comment by guolindev** [comment]
已在3.0.0版本中增加此功能，具体可参考文档，或者这篇文章 https://blog.csdn.net/guolin_blog/article/details/82714414

**Comment by maiglail** [comment]
@JakeHao @guolindev 请问各位大佬，数据库表初始化这个监听具体怎么写，写在哪个地方，我现在也想初始化数据库是往表里面添加一些默认数据。
