### ISSUE TITLE
数据库集合存储类型不支持List<Object>吗？

### ISSUE THREAD

**Issue by a460372011** [LitePalFramework/LitePal#416]
1.4以后支持List<String>集合之外，还有List<Integer>、List<Boolean>、List<Long>、List<Float>、List<Double>、List<Character>等。但是试了下Object类型好像不支持还是什么，看不到关联的表

**Comment by guolindev** [comment]
只支持8种基本数据类型和String，除此之外的类型都不支持，谢谢。
