### ISSUE TITLE
想了解下，LitePalSupport如何才能和BaseObservable（DataBinding）配合使用

### ISSUE THREAD

**Issue by Jossing** [LitePalFramework/LitePal#417]
仿佛有点水土不服啊~

**Comment by Jossing** [comment]
我是不是要强行修改LitePalSupport的爸爸成BaseObservable

**Comment by guolindev** [comment]
这个我没有具体去了解过，LitePal并没有特意去对Rxjava或DataBinding做过优化，如果在继承方面有冲突的话，我后面考虑在Kotlin版上使用接口的方式实现，感谢提出疑问。
