### ISSUE TITLE
能否支持 public 属性？

### ISSUE THREAD

**Issue by drakeet** [LitePalFramework/LitePal#42]
貌似只能是 private，求支持 public 属性，或者告知下怎么修改源码来获得这一支持，非常感谢！

**Comment by sinyu890807** [comment]
先前版本为了让数据库创建最简化，一切都遵循约束好的规则，所以只有private属性才会创建对应的列，下个版本里面会改掉这个属性，允许public字段创建对应的列。

**Comment by mio4kon** [comment]
同希望public属性.习惯bean都是用public写

**Comment by sinyu890807** [comment]
1.3.0版本已修改此功能，现在可以使用任意修饰符来声明字段，如果想忽略该字段使用 ignore=true来设置，详情参数项目主页说明。
