### ISSUE TITLE
Type "byte" is not included in LitePal models

### ISSUE THREAD

**Issue by NeoFantom** [LitePalFramework/LitePal#421]
I have a model like this one:
```java
public class Entry extends LitePalSupport {
    private String word;

    private String def;

    private byte proficiency;
    ...
}
```
But I found that every time I want to save this model, no matter how much I set `proficiency` to, the next time I check, it's still zero. My guess is that byte is not included when LitePal using reflection. I think, however, it should be included because sometimes I have a lot of instances of this model and using byte rather than int can save some memory.

Will you add byte variables into LitePal models in future versions?

**Comment by guolindev** [comment]
Well, you are right. byte is not included in the supported type in LitePal. It only support int, short, long, float, double, boolean, char, byte array, String and java.util.Date. 

Byte might save some memory, but it's not as easy to use as int i guess. Actually memory is not a such big problem, I tried to load 100,00 data from database in one time, and it worked fine even in some old devices. 

Still you can try to use short type in your case, it will cost less memory than int, maybe a better choice.
