### ISSUE TITLE
LitePal.deleteDatabase("mfbimdb");  删除数据库失败

### ISSUE THREAD

**Issue by JJC319** [LitePalFramework/LitePal#422]
当数据的路径配置为value="Android/data/com.bim.gl/database"时（保存在 包名下的database目录下），调用
LitePal.deleteDatabase("mfbimdb");  进行数据库的删除操作，结果是失败的。

**Comment by JJC319** [comment]
public static boolean deleteDatabase(String dbName) {
        synchronized (LitePalSupport.class) {
            if (!TextUtils.isEmpty(dbName)) {
                if (!dbName.endsWith(Const.Config.DB_NAME_SUFFIX)) {
                    dbName = dbName + Const.Config.DB_NAME_SUFFIX;
                }
                File dbFile = LitePalApplication.getContext().getDatabasePath(dbName);
                if (dbFile.exists()) {
                    boolean result = dbFile.delete();
                    if (result) {
                        removeVersionInSharedPreferences(dbName);
                        Connector.clearLitePalOpenHelperInstance();
                    }
                    return result;
                }
                String path = LitePalApplication.getContext().getExternalFilesDir("") + "/databases/";
                dbFile = new File(path + dbName);
                boolean result = dbFile.delete();
                if (result) {
                    removeVersionInSharedPreferences(dbName);
                    Connector.clearLitePalOpenHelperInstance();
                }
                return result;
            }
            return false;
        }
    }
在pad8.0上时当 数据库的路径设置为value="Android/data/com.bim.gl/database"，调用删除数据库的方法失败。

 File dbFile = LitePalApplication.getContext().getDatabasePath(dbName);
String path = LitePalApplication.getContext().getExternalFilesDir("") + "/databases/";
发现这两句代码的返回值不对，导致删除失败。

**Comment by JJC319** [comment]
@guolindev 郭神有空帮看下这个问题

**Comment by SJLBenjamin** [comment]
请问有解决这个问题吗  我也遇见了

**Comment by guolindev** [comment]
我在10.0的手机上试了一下，发现是可以正常删除的，还没有发现你说的这个问题。

不过在接下来的版本当中，我可能很快会禁用将数据库存储到SD卡的功能，到时候删除数据库也只能删除internal空间下的数据库，这个问题应该也就不存在了。

由于问题久远，我先将这个问题关掉了，如果还有疑问的话，请重新打开。
