### ISSUE TITLE
litepal-2.0.0.jar

### ISSUE THREAD

**Issue by weilan09** [LitePalFramework/LitePal#423]
Program type already present: org.litepal.FluentQuery$2$1
Message{kind=ERROR, text=Program type already present: org.litepal.FluentQuery$2$1, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by guolindev** [comment]
I guess you already include litepal by gradle denpendency. So it got conflict with litepal-2.0.0.jar. You don't need this when you use Android Studio.
