### ISSUE TITLE
find(Class clazz)调用崩溃

### ISSUE THREAD

**Issue by LittleLeiLei** [LitePalFramework/LitePal#424]
1.
异常：
`
android.database.sqlite.SQLiteException
near "uid": syntax error (code 1): , while compiling: SELECT * FROM xxxxx WHERE ? and ?uid = ? and name = ?
`

崩溃代码：
`
DataSupport.where("uid = ? and name = ?", uid, name).find(BadgeNodeEntity.class)
`

2.异常：
`org.litepal.exceptions.DataSupportException:near "and_lpcolumn": syntax error (code 1): , while compiling: SELECT * FROM badgenodeentity WHERE uid = ? and_lpcolumn name = ?`

崩溃代码：
`
DataSupport.where("uid = ? and name = ?", uid, name).find(BadgeNodeEntity.class)
`

看起来是sql语句在做列名的关键词检查时产生了错误的替换
litepal版本：v1.6.1

**Comment by guolindev** [comment]
能把你的BadgeNodeEntity完整代码贴出来吗？

**Comment by LittleLeiLei** [comment]
```
public class BadgeNodeEntity extends DataSupport {
    
    private int id;
    private int uid;
    private String name;
    private int count;
    

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }
}
```
不好意思没注意到消息，这个问题并不是必现的。在大部分手机是正常

**Comment by guolindev** [comment]
这个问题我还真是从来没见过，实体类的定义没有任何问题，但是却莫名其妙触发了sql关键字冲突，启用了自动添加_lpcolumn后缀，但是从报错的日志上来看，_lpcolumn前面却没有跟任何字段的名字，这绝对是个灵异事件。

而且你的第一条错误日志，SELECT * FROM xxxxx WHERE ? and ?uid = ? and name = ?  ，where后面竟然跟了个? and ?，这个语法肯定是错误的，而且不可能出现才对。

这个确实如你所说，可能是特定手机的问题，但是我确实从来也没碰到过这个情况，如果你有那台设备的话，可以尝试一下用原生SQLiteDatabase试一试，看看能不能正常执行，因为LitePal的底层也是调用的SQLiteDatabase，发生上述问题的话理论上原生的用法也会出错。
