### ISSUE TITLE
如何使用复合主键

### ISSUE THREAD

**Issue by zhangnanvip** [LitePalFramework/LitePal#425]
如何使用复合主键？

**Comment by guolindev** [comment]
LitePal是不支持复合主键的，且不能自定义主键，主键由LitePal自动生成，并且固定为id。

**Comment by tomake** [comment]
> LitePal是不支持复合主键的，且不能自定义主键，主键由LitePal自动生成，并且固定为id。

多主键的场景很常见哦， 请问有没在后续迭代版本支持的计划
