### ISSUE TITLE
请问LitePal怎么使用代码创建.db的数据库，怎么样去指定实体类对应的表名

### ISSUE THREAD

**Issue by YanYanLun** [LitePalFramework/LitePal#426]
请问LitePal怎么使用代码创建.db的数据库，怎么样去指定实体类对应的表名

**Comment by guolindev** [comment]
数据库是自动创建的，根据你在litepal.xml里面配置的数据库名。实体类对应的表名是Litepal自动决定的，对于开发者来说无须关心表名是什么，直接对类和对象进行操作就可以了。

**Comment by YanYanLun** [comment]
我这边主要是需要动态创建数据库文件，事先是不能够确定数据库名称的
