### ISSUE TITLE
LitePal.saveAll() 如果实体类中有内部类 好像内部类数据没有存进去呀 郭神..

### ISSUE THREAD

**Issue by zhangshaobo87** [LitePalFramework/LitePal#429]

**Comment by guolindev** [comment]
内部类当然是不会存进去的了，内部类本质上是另外一个class了，和你外部class并没有什么关系，字段之间也是独立的，对应的也是不同的表。

**Comment by luochengsc** [comment]
@guolindev 那郭神这种情况需要做关联存储怎么操作呢
现在我这里单条存储内部类可以保存，批量存储的话头几条数据有存储，后面的没有存进去
