### ISSUE TITLE
LitePal如何设置主键id为Unique 或如何设置表中某字段为Unique？

### ISSUE THREAD

**Issue by maobon** [LitePalFramework/LitePal#43]
请问大神LitePal框架如何设置表中的一个字段属性为Unique，当向表中插入相同的字段的时候。请问如何设置呢？

**Comment by sinyu890807** [comment]
下个版本中会支持这个功能，预计下个月更新LitePal版本

**Comment by sinyu890807** [comment]
1.3.0版本已支持此功能，详情参考项目主页说明。
