### ISSUE TITLE
litepal 无法另存已经存在的数据

### ISSUE THREAD

**Issue by LillteZheng** [LitePalFramework/LitePal#430]
如题，有这样的需求，某个已经保存的数据，用户在修改数据之后，可以选择更新或者另存；想另存的时候，因为已经存在了，就变成更新数据了。
还是说有这种另存的方法，我没发现，或者给个思路啊，感觉要写原始的数据库，头皮一片发麻。。

**Comment by LillteZheng** [comment]
目前我的做法是重新 new 一个新的bean，然后再把数据一个个拷到新的 bean 中，郭神有提供其他方法吗o(╥﹏╥)o

**Comment by guolindev** [comment]
文档说明里面有，在这里 https://github.com/LitePalFramework/LitePal#4-update-data
