### ISSUE TITLE
有注解@Column(unique = true, defaultValue = "unknown")时，保存报错

### ISSUE THREAD

**Issue by lanjiessh** [LitePalFramework/LitePal#434]
我需求是这样，有个用户列表需保存到数据库，希望已存在就更新，不存在的就新增（一开始我记得是有个方法是是saveOrUpdate吧？现在好像没找到了？），首次保存没有问题，第二次之后就报错，没有该注解时是没有问题的。
日志打印：未知错误:Save current model failed.

**Comment by guolindev** [comment]
把你的代码还有报错的日志贴出来看看

**Comment by guolindev** [comment]
长期无回复，已将问题关闭。

**Comment by yeshengwu** [comment]
长期无回复？怎么能问题关闭呢
