### ISSUE TITLE
i got an empty songs when i use "LitePal.findAll(Album::class.java)"

### ISSUE THREAD

**Issue by therander-huhu** [LitePalFramework/LitePal#435]
i got an empty songs when i use "LitePal.findAll(Album::class.java)", was it a right response or i used in a unproper way?

**Comment by guolindev** [comment]
If you want to load songs while query from albums, you need to add an eager flag to let LitePal query for associations. Change your code into:
`LitePal.findAll(Album::class.java, true)`
Everything should work find.
