### ISSUE TITLE
数据库升级的数据问题

### ISSUE THREAD

**Issue by sdgSnow** [LitePalFramework/LitePal#436]
郭神，请问下litepal数据库升级的时候，原来的数据会被删除掉吗，然后重新创建个表把数据加进去，比如加了个字段，这样的是怎样进行升级的呢，greendao是要删除原来数据重新创建的，添加辅助类工具可以保存原来数据，但是那样太麻烦了，不知道litepal是怎样的

**Comment by guolindev** [comment]
不会的，litepal升级数据都会保留下来，而且不需要用户做任何额外的处理，都是自动保留的。具体你可以参考下这篇文章 https://blog.csdn.net/guolin_blog/article/details/39151617

**Comment by sdgSnow** [comment]
感谢
