### ISSUE TITLE
表名叫Order ,显示语法错误 如何解决

### ISSUE THREAD

**Issue by ZhouShiNan** [LitePalFramework/LitePal#439]
data class Order(
        var orderId: String = "", //订单ID
        var orderCategory: String = "", //订单分类
        var orderCity: String = "", //订单城市
        var orderMark: String = "", //订单备注 最多180字
        var orderCustomerId: String = "", //发单人ID
        var orderCustomerCondition: String = "", //订单条件JSON 为空时传{}
        var orderStatus: Int = 0, //订单状态值（0=报价中1=已报价2=支付中3=已服务4=已完成5=客户取消6=服务者取消7=超时取消8=系统取消9=延长收货10=已评价）
        var orderServingId: String = "", //订单对应服务关系ID
        var orderPayType: Int = 0, //订单支付方式（1=online2=offline）
        var orderBillsId: String = "", //订单对应账单ID
        var orderCreateLocation: String = "", //下单坐标（lng,lat）
        var orderAssignId: String = "", //指定服务者ID
        var orderCreateAt: Int = 0, //订单创建时间
        var orderUpdateAt: Int = 0, //订单状态更新时间
        var serving: Serving = Serving(),
        var newQuoteCount: Int = 0,
        var newOrder: Boolean = false
) : Serializable, LitePalSupport()

报错：
SQLiteLog: (1) near "order": syntax error
应该是表名和order关键字冲突，但是还没找到解决方案

**Comment by guolindev** [comment]
不要以SQL的关键字来进行类命名，Order很明显是SQL关键字，这个命名在数据库里是行不通的，所以建议你换个另外的类名即可解决。
