### ISSUE TITLE
model中继承来的属性无法存入数据库

### ISSUE THREAD

**Issue by bravoCoder** [LitePalFramework/LitePal#44]
父类继承DataSupport，子类继承父类，但是只有private的属性能存入数据库。
若父类和子类的属性都是private，将子类实例存入数据库后，保存的只有子类自己的private属性；

**Comment by sinyu890807** [comment]
从1.3.2版本中开始支持继承属性。

**Comment by aiguanglin** [comment]
int 型的还是不支持
