### ISSUE TITLE
请问如何才能不以类名为表名

### ISSUE THREAD

**Issue by wangdadao2012** [LitePalFramework/LitePal#440]
因为项目中要求数据库类名统一加xx后缀便于识别，但是存在数据库中是不需要加后缀的，请问大神这种情况该如何自定义表名字

**Comment by guolindev** [comment]
不好意思，litepal暂时还不支持这个功能，这个目前确实是无法实现的。

**Comment by wangdadao2012** [comment]
> 
> 
> 不好意思，litepal暂时还不支持这个功能，这个目前确实是无法实现的。

好的收到，谢谢郭神，希望litepal越来越强大
