### ISSUE TITLE
.Table_Schema not on android p,

### ISSUE THREAD

**Issue by wybzdaq** [LitePalFramework/LitePal#441]
org.litepal.exceptions.DatabaseGenerateException: can not find a class named org.litepal.model.Table_Schema

**Comment by guolindev** [comment]
能具体说下你的使用方法和使用场景吗，Table_Schema这个类是LitePal内部自动添加的，不需要你做任何额外的操作，如果说这个类找不到了，可能是你自己擅自修改了LitePal内部的逻辑导致的。

**Comment by guolindev** [comment]
No more feedback.
