### ISSUE TITLE
关于往表里面写入数据的问题

### ISSUE THREAD

**Issue by IcexTX** [LitePalFramework/LitePal#442]
![tim 20180927224806](https://user-images.githubusercontent.com/14036606/46154317-7dc21b00-c2a7-11e8-9452-dc931339a237.png)
问题是这样的，同一个类保存生成的表，生成字段不同？不明所以求解。以下是同一个实例类
![image](https://user-images.githubusercontent.com/14036606/46154562-0640bb80-c2a8-11e8-91a3-4f35b398ebec.png)

**Comment by IcexTX** [comment]
程序升级时，发现数据写不进去，查看控制台发现提示说少了headc字段，很是奇怪，所用的相关类均未改过。

**Comment by guolindev** [comment]
你在什么情况下会生成headc这个字段，什么情况下不会生成headc这个字段，有总结过吗？

**Comment by guolindev** [comment]
No more feedback.
