### ISSUE TITLE
项目依赖关系优化建议

### ISSUE THREAD

**Issue by dhhAndroid** [LitePalFramework/LitePal#446]
郭神，你好！今天看了公众号文章推送，感觉项目依赖关系，不是很友好。
       整体来看项目是分了三个模块，core，Java，Kotlin；你现在的依赖关系是，Java版本依赖core，Kotlin版本依赖core，导致 Java和Kotlin版本的代码是相互隔离的，写了类似重复的代码，LitePal.java和LitePal.kt的代码是一样的。
      Kotlin版本库里主要是利用了 Kotlin的 可具体化的泛型，优化了CRUD方法，所以没有必要重写LitePal.kt，你的kotlin版本库，实际上是要依赖Java版本库，然后用Kotlin去扩展LitePal.java 类的功能。所以个人认为比较友好的依赖关系，是kotlin版本api方式依赖Java版本，Java版本api依赖core。这样即使在kotlin的项目里，同时依赖Java和Kotlin版本的依赖，也是不会出错的。
     以上建议，来源于RxKotlin的做法，RxKotlin依赖RxJava后，只是做了函数拓展，而不是用Kotlin重写了RxJava。[RxKotlin依赖RxJava](https://github.com/ReactiveX/RxKotlin/blob/32bfc21489b563204a72158ae59dece1943f9d79/build.gradle#L18)

**Comment by guolindev** [comment]
你说的这个设计我都考虑过，我优先的第一选择方案就是保持LitePal.java不变，然后扩展LitePal.java功能。但是当你实体这么去操作的时候，你会发现这个设计是不可行的。

因为LitePal.java里所有的接口全部都是静态方法，而我调查过了，Kotlin至少在1.3版本还无法通过扩展方法向LitePal.java里面添加静态方法，只能添加实例方法，之后会不会在方面做出改变还不知道。

也就是说，如果按你说的这种设计，我向LitePal.java里面添加Kotlin的扩展实例方法，在Koglin上调用就会出现一种很奇怪的用法，LitePal().find<Person>(1)，得这样用才行，每次我要创建一个Litepal的实例，不然我添加的扩展实例方法使用静态调用的方式是根本调用不到的。

所以最终为了保证Kotlin和Java可以保证一样的调用方法，我必须去写一个LitePal.kt类，并且声明成一个成一个单例类，以保证语法和Java端是一致的。

当然也感谢你提出这个建议，说明你在使用的同时也在思考，我也设计的同时也是在思考，都是为了设计出一种更好的架构。
