### ISSUE TITLE
不支持多条件查询？

### ISSUE THREAD

**Issue by YY030913** [LitePalFramework/LitePal#447]
org.litepal.exceptions.LitePalSupportException: near "and": syntax error (code 1): , while compiling: SELECT * FROM friend WHERE userId = ? and groupid = ? @guolindev 我用3.0.0报错了，1.5.0也报错

**Comment by guolindev** [comment]
先把你的查询语句贴出来看看，直接从报错日志上看来，好像你没有指定查询条件，而是直接就用占位符问号去查询了

**Comment by YY030913** [comment]
LitePal.where("userId = ? and groupid = ?", userid, groupid).find(Friend.class); @guolindev 最基本的查询，userid，gourpid都是正常。现在只能使用LitePal.where("userId = ? ", userid).where("groupid = ?", groupid).find(Friend.class); 所有的条件查询都报语法错误。

**Comment by YY030913** [comment]
是的，加and 加or都报语法错误

**Comment by guolindev** [comment]
理论上来说这个情况是不可能的，LitePal的版本发布都是经过全部测试用例通过才会发版本的，and or条件查询都是覆盖在测试用例里面的。由于你总共就提供了这些信息，我努力按照你所提供的信息将整个流程复现了一遍。

首先定义一个Friend实体类，类中的字段是按照你上面提供的信息提练出来的：

```java
public class Friend extends LitePalSupport {

    private String userId;

    private String groupId;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
}

```

然后将这个实体类添加到litepal.xml配置当中：

```xml
<litepal>

    <dbname value="sample" />

    <version value="3" />

    <list>
        <mapping class="org.litepal.litepalsample.model.Friend" />
    </list>

    <storage value="external" />

</litepal>
```

现在使用如下代码添加两条数据：

```java
Friend friend1 = new Friend();
friend1.setUserId("user1");
friend1.setGroupId("group1");
friend1.save();

Friend friend2 = new Friend();
friend2.setUserId("user2");
friend2.setGroupId("group2");
friend2.save();
```

然后通过查询工具验证一下两条数据已经添加成功了：

![20181018161305](https://user-images.githubusercontent.com/20859208/47141029-4e289080-d2f2-11e8-8745-14a6c8114514.png)

接下来使用下面的代码查询和打印结果：

```java
List<Friend> result = LitePal.where("userId = ? and groupId = ?", "user1", "group1").find(Friend.class);
Log.d(TAG, "result size is " + result.size());
for (Friend friend : result) {
    Log.d(TAG, "friend userId is " + friend.getUserId() + " , friend groupId is " + friend.getGroupId());
}
```

注意上述查询中使用了and关键字。

最后打印结果如下：

![qq 20181018163208](https://user-images.githubusercontent.com/20859208/47141551-88def880-d2f3-11e8-80ed-a9e4e6bcdf50.png)

可以看到结果都正常打印出来了，带and关键字的查询是成功的。

所以你这个问题我这边无法复现。
