### ISSUE TITLE
关联查询查不到数据，具体如下

### ISSUE THREAD

**Issue by gaohequan** [LitePalFramework/LitePal#454]
class MessageExtra{
   int type;
}
class Message{
  String content;
  MessageExtra extra;
}
class Conversation{
  List《Message》 list;
  String name;
}

MessageExtra extra = new MessageExtra();
extra.setType(100);
extra.save();

Message message = new Message();
message.setExtra(extra);
message.setContent("targetContent");
message.save();

Conversation conversation = new Conversation();
conversation.getList().add(0,message);
conversation.setName("TargetName");
conversation.save();

List<Conversation> list = LitePal.where("name = ?","TargetName").find(Conversation.class,true);
Conversation conversation = list.get(0);
conversation.getList().get(0).getContent() =  "TargetContent"  正常
conversation.getList().get(0).getExtra().getType()  崩溃 通过Debug知道 getExtra对象为空

**Comment by Theoneee** [comment]
id 是要自己写嘛？

**Comment by guolindev** [comment]
LitePal的eager加载只处理一层数据关联，大于一层的数据关联是不会加载的，考虑到性能的问题，所以这种情况需要开发者自己去手动加载大于一层的关联数据才行。
