### ISSUE TITLE
org.litepal.exceptions.LitePalSupportException: Expression tree is too large (maximum depth 1000)(Sqlite code 1):

### ISSUE THREAD

**Issue by Bravehearthk** [LitePalFramework/LitePal#455]
FATAL EXCEPTION: Thread-61469
 Process: com.bs.aclp, PID: 20226
org.litepal.exceptions.LitePalSupportException: Expression tree is too large (maximum depth 1000)(Sqlite code 1): , while compiling: UPDATE detailbean SET linelistbean_id=? WHERE id = 4099 or id = 5824 or id = 4580 or id = 3340 or id = 4403 or id = 4680 or id = 3279 or id = 3042 or id = 2966 or id = 5792 or id = 4183 or id = 5196 or id = 4147 or id = 3540 or id = 3447 or id = 3919 or id = 4453 or id = 4944 or id = 4086 or id = 4615 or id = 3420 or id = 5593 or id = 4460 or id = 5821 or id = 4174 or id = 4273 or id = 3481 or id = 3832 or id = 4899 or id = 2999 or id = 4078 or id = 3338 or id = 3575 or id = 4505 or id = 3539 or id = 4081 or id = 5528 or id = 4153 or id = 3132 or id = 2986 or id = 5091 or id = 4324 or id = 5245 or id = 3818 or id = 5058 or id = 3531 or id = 3847 or id = 4834 or id = 4510 or id = 4792 or id = 4227 or id = 3840 or id = 5076 or id = 4852 or id = 4791 or id = 3735 or id = 5540 or id = 4942 or id = 4132 or id = 3013 or id = 5323 or id = 2958 or id = 4704 or id = 5387 or id = 4966 or id = 4223 or id = 4598 or id = 3697 or id = 3904 or id = 4769 or id = 3677 or id = 3771 or id = 4184 or id = 5399 or id = 5115 or id = 3068 or id = 4839 or id = 4229 or id = 3015 or id = 5370 or id = 3456 or id = 3370 or id = 5548 or id = 2946 or id = 3607 or id = 3688 or id = 3018 or id = 4898 or id = 5119 or id = 5075 or id = 4676 or id = 4643 or id = 5845 or id = 2954 or id = 5561 or id = 4442 or id = 2931 or id = 4194 or id = 4745 or id = 3940 or id = 3438 or id = 3895 or id = 4949 or id = 4039 or id = 5339 or id = 4774 or id = 3913 or id = 3612 or id = 3494 or id = 3878 or id = 5462 or id = 3248 or id = 5800 or id = 3430 or id = 4190 or id = 3267 or id = 5701 or id = 4658 or id = 4109 or id = 3506 or id = 4381 or id = 4275 or id = 2948 or id = 3382 or id = 4885 or id = 4097 or id = 4795 or id = 3651 or id = 3129 or id = 3742 or id = 5228 or id = 3328 or id = 5469 or id = 3791 or id = 2934 or id = 4145 or id = 3769 or id = 3731 or id = 5436 or id = 5682 or id = 3396 or id = 5221 or id = 4287 or id = 3577 or id = 5101 or id = 4483 or id = 3765 or id = 3425 or id = 4377 or id = 5514 or id = 3783 or id = 3226 or id = 5618 or id = 4476 or id = 5043 or id = 4503 or id = 5495 or id = 3980 or id = 5582 or id = 5193 or id = 5046 or id = 4126 or id = 4554 or id = 4353 or id = 4199 or id = 4989 or id = 4617 or id = 4361 or id = 3816 or id = 5502 or id = 2941 or id = 4781 or id = 5324 or id = 5749 or id = 5000 or id = 4270 or id = 3776 or id = 3295 or id = 3160 or id = 4853 or id = 4780 or id = 3070 or id = 3123 or id = 5063 or id = 4978 or id = 3601 or id = 5448 or id = 4892 or id = 3935 or id = 3363 or id = 4010 or id = 5018 or id = 5234 or id = 5488 or id = 3167 or id = 3301 or id = 5144 or id = 4788 or id = 5601 or id = 5098 or id = 4933 or id = 4654 or id = 3707 or id = 5614 or id = 5441 or id = 5737 or id = 3219 or id = 5810 or id = 5504 or id = 3139 or id = 4150 or id = 3486 or id = 3734 or id = 3464 or id = 4297 or id = 3928 or id = 5732 or id = 5703 or id = 4210 or id = 4536 or id = 4017 or id = 3751 or id = 5439 or id = 3260 or id = 3726 or id = 3348 or id = 3775 or id = 4700 or id = 4188 or id = 5804 or id = 3223 or id = 5513 or id = 4870 or id = 4786 or id = 5048 or id = 5479 or id = 4024 or id = 3573 or id = 4539 or id = 3090 or id = 2944 or id = 3923 or id = 2995 or id = 3147 or id = 5651 or id = 5750 or id = 5207 or id = 3547 or id = 5721 or id = 5559 or id = 4538 or id = 3859 or id = 5410 or id = 3647 or id = 5566 or id = 3406 or id = 5071 or id = 4708 or id = 5426 or id = 3906 or id = 3188 or id = 4830 or id = 3983 or id = 3898 or id = 4992 or id = 4548 or id = 5558 or id = 4662 or id = 5202 or id = 4248 or id = 3792 or id = 4014 or id = 3388 or id = 4919 or id = 3595 or id = 4832 or id = 3300 or id = 3656 or id = 2961 or id = 4119 or id = 4313 or id = 3511 or id = 3062 or id = 5567 or id = 5118 or id = 4930 or id = 4258 or id = 4470 or id = 4408 or id = 4074 or id = 3048 or id = 3971 or id = 5020 or id = 570
如何解除限制？？？

**Comment by xiexin52k** [comment]
使用 in( )? 或者分多次查询?

**Comment by guolindev** [comment]
楼上已经给出答案了，这个是android数据库本身的限制，并不是litepal的限制，你的表达式过长了，sqlite数据库不支持大于1000深度的表达式。
