### ISSUE TITLE
Litepal存储图片问题

### ISSUE THREAD

**Issue by Bravehearthk** [LitePalFramework/LitePal#456]
单张图片可以用byte[]存储成功，但多张图片用List<byte[]>报错了，应该是初始化的问题，请求多张图片正确存储的方式，是否一张表不能存储List<byte[]>

**Comment by guolindev** [comment]
可能确实存在这个问题，但是给你的建议是最好不要这么做，数据库本来就不适合存储图片，虽然当时加了这个功能，但是我自己也从来没用过。推荐的做法是，把图片存储到外置或内置空间里，然后数据库只要保存一下图片的路径地址就可以了。

**Comment by lutao2599** [comment]
如果是存储视频缩略图呢？

**Comment by guolindev** [comment]
一样的道理，你把图片存到专门的存储空间里，然后把图片路径存到数据库里，这才是正确的做法。

**Comment by lutao2599** [comment]
我现在做的是选择视频，用列表展示所选视频
；如果是保存视频路径，在适配器中生成缩略图，就会变得非常卡，请问这该怎么解决？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/LitePal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 上午10:50
收件人:&nbsp;"guolindev/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/LitePal] Litepal存储图片问题 (#456)





 
一样的道理，你把图片存到专门的存储空间里，然后把图片路径存到数据库里，这才是正确的做法。

**Comment by guolindev** [comment]
你把给视频生成缩略图的逻辑放到客户端，而且还是客户端列表里去做，这当然会卡了，你们公司的服务器都不干活的吗，不把缩略图在服务器端生成好了返回给客户端？

**Comment by lutao2599** [comment]
是需要客户端生成的：就是本地选择视频后列表展示，然后再去上传到服务器的；




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/LitePal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 上午10:54
收件人:&nbsp;"guolindev/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/LitePal] Litepal存储图片问题 (#456)





 
你把给视频生成缩略图的逻辑放到客户端，而且还是客户端列表里去做，这当然会卡了，你们公司的服务器都不干活的吗，不把缩略图在服务器端生成好了返回给客户端？

**Comment by guolindev** [comment]
本地视频是吧，如果是本地视频那就没有什么特别好的办法了。只能你在列表里面自己手动做判断，如果有缓存缩略图，那么直接去读取，如果没有缓存缩略图，那么就开一个线程，手动生成缩略图并缓存起来。生成缩略图的这个过程中你只能用占位图显示，然后数据库里面始终还是只存储缩略图的路径。

**Comment by lutao2599** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/LitePal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 中午11:00
收件人:&nbsp;"guolindev/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"追梦赤子"<1336440850@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/LitePal] Litepal存储图片问题 (#456)





 
本地视频是吧，如果是本地视频那就没有什么特别好的办法了。只能你在列表里面自己手动做判断，如果有缓存缩略图，那么直接去读取，如果没有缓存缩略图，那么就开一个线程，手动生成缩略图并缓存起来。生成缩略图的这个过程中你只能用占位图显示，然后数据库里面始终还是只存储缩略图的路径。
