### ISSUE TITLE
可不可以使用注解标记实体类创建表

### ISSUE THREAD

**Issue by halong** [LitePalFramework/LitePal#457]
public class Song extends LitePalSupport   这种方式，万一我想让Song extends其他类怎么办？

**Comment by guolindev** [comment]
不继承LitePalSupport也可以创建数据库表，继承LitePalSupport主要是为了让Song这个类可以拥有save()，delete()，update()等继承而来的方法，简化api的调用。如果你想让Song继承别的类，可以让那个被继承的类来继承LitePalSupport。
