### ISSUE TITLE
有没有可能支持同时两个数据库引用?

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#458]
如题, 我有个这样的需求,. 
首先, 我app是多用户系统的, 就是一个用户使用自己的数据库
然后, 我需要一个公有的数据库来记录他们已经下载的文件信息.
当我登录用户下载文件的时候, 需要先查看其它用户是否已经下载过这个文件
这个时候我就需要到公有文件库中查询这个文件是否已经下载.
但是LitePal只能支持同一时间使用一个数据库, 碰到我上面说的这种需求, 就没法实现了. .

**Comment by kilo-swodh** [comment]
复制个副本，想操作哪个就复制到litepal声明的临时db目录，操作完覆盖回去。

**Comment by guolindev** [comment]
动态切换一下数据库就可以了，你需要用哪个数据库的时候就切换到哪个数据库。
