### ISSUE TITLE
 Could not resolve org.litepal.android:java:3.0.0.

### ISSUE THREAD

**Issue by yewenjunfighting** [LitePalFramework/LitePal#459]
请问下在android中遇到这样的问题该怎么解决

下面是完整的报错信息
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve org.litepal.android:java:3.0.0.
     Required by:
         LitePalTest:app:unspecified
      > Could not resolve org.litepal.android:java:3.0.0.
         > Could not get resource 'https://jcenter.bintray.com/org/litepal/android/java/3.0.0/java-3.0.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/litepal/android/java/3.0.0/java-3.0.0.pom'.
               > android-mirror.bugly.qq.com

**Comment by guolindev** [comment]
应该是网络问题，jcenter在中国的访问并不稳定，你尽量翻下墙再去sync gradle应该就可以了。

**Comment by yewenjunfighting** [comment]
哦哦好的，谢谢郭老师
