### ISSUE TITLE
dbname有数字的时候无法创建

### ISSUE THREAD

**Issue by hfloveyy** [LitePalFramework/LitePal#462]
dbname有数字的时候无法创建，当我试着用face2作为dbname的时候无法创建数据库

**Comment by guolindev** [comment]
我这边试了一下，并没有你说的情况，数据库名后面加上数字也是可以创建的。

因为LitePal没有在这方面做逻辑处理，是直接把数据库名提交给Android底层的，所以也有可能是某些手机在底层做了这方面的限制。

建议如果发现了这种问题，就尽量避免使用带数字的数据库名吧。
