### ISSUE TITLE
泛型强转后保存，提示保存成功，但是事实根本就没有保存数据。

### ISSUE THREAD

**Issue by terryspark** [LitePalFramework/LitePal#464]
请看下面注解出标明的两个问题。

 Observable<List<T>> netWorkData = mUploadRemoteSource.getDataByType(type, clazz, time)
                .doOnNext(new Consumer<List<T>>() {
                    @Override
                    public void accept(List<T> ts) throws Exception {
                    if ("task".equals(type)) {
                       List<Task> tasks = new ArrayList<>();
                        for (T item : ts) {
                            Task taskItem = (Task)item;
                            Task task = new Task();
                            task.setTaskName(taskItem.getTaskName());
                            task.setTaskId(taskItem.getTaskId());
                            List<Expense> expenses = new ArrayList<>();
                            if (taskItem.getExpenses() != null && taskItem.getExpenses().size() > 0) {
                                for (Expense expense : taskItem.getExpenses()) {
                                    Expense expenseData = new Expense();
                                    expenseData.setInvoiceType(expense.getInvoiceType());
                                    expenseData.setPicList(expense.getPicList());
                                    expenseData.setExpenseType(expense.getExpenseType());
                                    expenseData.setLocation(expense.getLocation());
                                    expenseData.setInfo(expense.getInfo());
                                    expenseData.setExpenseAmount(expense.getExpenseAmount());
                                    expenseData.setCreateTime(expense.getCreateTime());
                                    expenseData.setExpenseId(expense.getExpenseId());
                                    expenseData.setPaymentType(expense.getPaymentType());
                                    expenseData.setTaskId(expense.getTaskId());
                                    expenses.add(expenseData);
                                    mLocalSource.save(expenseData);

                                }
//                                mLocalSource.saveAll(expenses);   这个地方批量保存提示此次保存失败，但是单条保存就没有问题，同样的数据

                            }
                            task.setTaskEndTime(taskItem.getTaskEndTime());
                            task.setTaskDesc(taskItem.getTaskDesc());
                            task.setTaskStartTime(taskItem.getTaskStartTime());
                            task.setTaskProject(taskItem.getTaskProject());
                            task.setTaskApplicant(taskItem.getTaskApplicant());
                            task.setTaskState(taskItem.getTaskState());

                            tasks.add(task);

                        }
                        mLocalSource.saveAll(tasks);
//                        mLocalSource.saveAll(((List<Task>) ts));     这样强转提示保存成功，但是根本就没有数据，在数据库里。但是按不注释的方法保存就没有问题。

**Comment by guolindev** [comment]
可能是因为存储数据的时候出现了异常，导致没有存储成功。

saveAll()方法之前并没有设置返回值，所以无法从这个方法中获得存储成功还是失败。

从3.1.0版本开始，LitePal的saveAll()方法已加上返回值，用于标识是否存储成功，如果返回false的话，那么所有的数据都不会出现在数据库里。只有返回true，才表示所有数据都存储到了数据库当中。
