### ISSUE TITLE
提个问题哈，也不知道是不是我不应该这样子操作

### ISSUE THREAD

**Issue by 15863459070** [LitePalFramework/LitePal#465]
Video video = new Video();

我先setToDefault("path");
然后我想再给path复制， video.setPath("....");
然后我就 video.update(id);
重新查找这个id，这个path值还是默认值。
第二个问题，是个疑问 我setToDefault("path");后 需要不要调用update方法来更新，还是直接调用setToDefault，内部就已经更新表了？

**Comment by guolindev** [comment]
要的，setToDefault("path")后不会执行任何操作，必须调用update方法后才会更新，所以你的第一个问题也是因为这个原因。
