### ISSUE TITLE
表关联，查不到数据

### ISSUE THREAD

**Issue by terryspark** [LitePalFramework/LitePal#467]
public class Task extends LitePalSupport{
    @Column(unique = true,nullable = false)
    private String taskId;
    private String taskName;
    private String taskApplicant;
    private String taskDesc;
    private String taskStartTime;
    private String taskEndTime;
    private String taskState;
    private String taskProject;
    private List<Expense> expenses;

如此定义的model，用激进查询根本就关联不到expense表。

**Comment by xiexin52k** [comment]
写了泛型没?

**Comment by guolindev** [comment]
这个是基本用法问题，我也看不到你的代码，不知道问出在哪里，给你几条查询问题的建议吧。

首先看一下这篇文章，确认一下表关联有没有正确建立 https://blog.csdn.net/guolin_blog/article/details/39207945

然后看一下关联表里面的数据是否正确存在，这一点是很重要的，如果关联数据本身就没存进去，自然是查询不到的。

最后查询的话使用激进查询，你既然说使用激进查询了那么我默认你的使用方法是对的，如果想确认下用法是否正确，可以参考下这篇文章 https://blog.csdn.net/guolin_blog/article/details/40153833
