### ISSUE TITLE
save（）保存不了

### ISSUE THREAD

**Issue by ChloeDimen** [LitePalFramework/LitePal#468]
数据库创建，但是表就是不创建？？

**Comment by ChloeDimen** [comment]
如果有字段为string id，导致保存失败。要把id字段替换掉。

**Comment by zhq217217** [comment]
我们后台给返回的数据也是string类型的Id，这里提供一种思路解决这个问题：如果你们解析数据用的gson，那么可以在
bean中不用id字段去接收后台数据，改为任意其他字段，然后上面写上注解@SerializedName("Id") 这样就可以解决了。具体gson的这种用法请搜索：如何使用@SerializedName更改字段命名

**Comment by guolindev** [comment]
楼上是最标准的解决方案，感谢解答。
