### ISSUE TITLE
能否支持自己指定主键呢，比如我设置一个String类型的username为主键？

### ISSUE THREAD

**Issue by caprice** [LitePalFramework/LitePal#47]

**Comment by 328629033** [comment]
我也是纳闷。。。

**Comment by jinjingmail** [comment]
一定要默认有一个自增的主键确实很奇怪；更奇怪的是名字不能变，只能是id。
我能想到的解决办法之一：
*忽略它的id，定义一个新的id（比如id2），跟后台交换数据的时候使用自己的新id

**Comment by sinyu890807** [comment]
主键这种东西你不要赋予他业务逻辑的，用户名作为主键本身就是一种非常差的数据库设计。litepal强制使用id作为主键的，因为内部业务逻辑和id关联的很多，所有名字也不好改，如果非要使用的其它的名字，楼上的方法是一种解决方案。
