### ISSUE TITLE
怎么让主键ID重新计数

### ISSUE THREAD

**Issue by xxzztt** [LitePalFramework/LitePal#470]
数据表经常进行全部删除和重新写入数据的操作。时间长了，ID变得非常大，担心有一天会到极限。

我能在删除的时候复位ID从1开始吗？

**Comment by guolindev** [comment]
这个是做不到的，我做个一个继续，就算你每秒插入一条数据，好像也要10年后id才会超出极限。客户端数据库不用考虑这种问题，即使是服务器的数据库，id也从来没有复位这种说法。
