### ISSUE TITLE
查询是确实慢,还是我代码的问题?

### ISSUE THREAD

**Issue by z2700589** [LitePalFramework/LitePal#475]
我现在做一个页面,打开后从数据库读数据然后绑定recycleview,但每次进到这个页面都会卡顿2s左右.
同步异步方法都用过了,想不明白怎么优化,litepal版本是3.0.0.

**Comment by Chenshuai770** [comment]
解决方案 https://zhuanlan.zhihu.com/p/27662870

**Comment by guolindev** [comment]
你的数据量有多大会卡顿2s？ 一般如果是几千条以内的数据，litepal都可以瞬间读取出来，如果是高于数千条的数据，建议分页读取，不要一次性全读出来。

我觉得你可以打印一下使用LitePal数据读取的时间，看一下读取一共花了多久，这2s不一定是LitePal导致的。
