### ISSUE TITLE
关于数据库升级以后复制原有表默认值不起作用

### ISSUE THREAD

**Issue by weiaiSanli** [LitePalFramework/LitePal#476]
我们的数据库有上传备份功能,目前在表中增加一行新的数据goods_stock_number,给他默认值为 -1,然后换台机器在启动页重新下载上次没有更新过,不带goods_stock_number的库,使用LitePal.useDefault()刷新数据库,但是goods_stock_number却全部默认为int型的0,不是设置的默认值 -1 ,即使我在 @Column(defaultValue = "-1")
    private int goods_stock_number = -1; //商品库存数量,默认为 -1,这行代码不起作用啊,请问应该怎么办,数据库升级代码能指定位置在升级吗,是由于启动页的时候已经升级到最新版本,不能再修改成默认值的原因吗?期待大神给予解答,多谢!

**Comment by guolindev** [comment]
你的问题我看得不是特别明白，但是LitePal本身并不支持上传备份功能，从别处导入数据库会不会产生未知的风险这点我也不能保证，因此请尽量避免做这类操作，如果要备份数据库请尽量从数据备份这个角度上面入手，而不是文件备份。

另外由于这个问题久远，我暂时先关闭掉了，如果还有疑问的话请重新打开。
