### ISSUE TITLE
一个任务Mission类中， 有一个动作Action类的集合。 无法保存。A MissionBean contains a List<ActionBean>, can't save it.

### ISSUE THREAD

**Issue by YistXin** [LitePalFramework/LitePal#477]
一个任务Mission类中， 有一个动作Action类的集合。  无法保存。

**Comment by YistxIn** [comment]
public class User extends LitePalSupport{

    private String name;
    private String password;
    private boolean rememberPassword;
    private boolean isLaserShow;
    private boolean laser1On;
    private boolean laser2On;
    private boolean laser3On;
    private int virtualMapColor;
    private float maxLinearSpeed;
    private float maxAngularSpeed;
    private float maxNavigationSpeed;
    private List<MissionAction> waitingList;
    private List<MissionAction> movingList;
    private List<MissionAction> charingList;

    public User() {

    }

    //.....

}

**Comment by YistxIn** [comment]
这样，list就保存不了，其他的String, boolean, float, int类型都能保存。  list一直是空

**Comment by vast00** [comment]
请问解决了吗

**Comment by Puppy-Love** [comment]
解决了吗？

**Comment by guolindev** [comment]
你这种定义实体类的方式只能定义瞬时数据，是无法定义持久化数据的。

如果你要建立User和MissionAction的关联关系，那么需要将MissionAction也保存到数据库当中，litepal才会建立它们之间的外键关联。另外最重要的是，你另外了3个`List<MissionAction>`的字段，这种反应到数据库当中是根本无法存储的，因为对于MissionAction表来说，没有办法区分你是waitingList还是movingList还是charingList。

建立阅读一下LitePal表关联的这篇文章，对数据库表的关联性有个基础的了解： https://blog.csdn.net/guolin_blog/article/details/39207945
