### ISSUE TITLE
IllegalArgumentException: File null/databases/test.db contains a path separator

### ISSUE THREAD

**Issue by shannonlo** [LitePalFramework/LitePal#478]
Firebase has many these issue. It doesn't occur every time but sometime and I don't know what the scenario.

use version: 2.0.0
litepal.xml: define .db file save in external storage

extra log: 
Caused by java.lang.IllegalArgumentException
File null/databases/test.db contains a path separator
android.app.ContextImpl.makeFilename (ContextImpl.java:2165)
android.app.ContextImpl.getDatabasePath (ContextImpl.java:695)
android.app.ContextImpl.openOrCreateDatabase (ContextImpl.java:644)
android.content.ContextWrapper.openOrCreateDatabase (ContextWrapper.java:289)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:223)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:163)
org.litepal.tablemanager.Connector.getWritableDatabase (Connector.java:64)
org.litepal.tablemanager.Connector.getDatabase (Connector.java:87)
org.litepal.FluentQuery.count (FluentQuery.java:495)
org.litepal.FluentQuery.count (FluentQuery.java:461)

**Comment by guolindev** [comment]
It's really not a good manner to store db file on external storage. If some cellphone doesn't have external storage, it might cause problem.

If the future release, I will abandon to use external storage for db file. So this problem may never happen again.

I will close this issue first. If you still have question, reopen it please.
