### ISSUE TITLE
关于#32的疑问

### ISSUE THREAD

**Issue by choimroc** [LitePalFramework/LitePal#479]
看了作者的解释，是为了让程序员不用每次update都把其他值都set一下，但是update的时候其实可以先Query再更新，这样所有的字段都带有原来的值了。增加了setToDefault()，这样又会出现一个问题，如果我想保存为默认值，我就得每个字段都判断一下是不是update为默认值，然后调用setToDefault()？不知道这样理解对不对。

**Comment by xiexin52k** [comment]
推荐你一个方法,  取出数据之后, 将值设置你任何想要的, 直接调用save就行了, 
```java
	if (!baseObj.isSaved()) {
                analyzeAssociatedModels(baseObj, associationInfos);
		doSaveAction(baseObj, supportedFields, supportedGenericFields);
                analyzeAssociatedModels(baseObj, associationInfos);
	} else {
                analyzeAssociatedModels(baseObj, associationInfos);
		doUpdateAction(baseObj, supportedFields, supportedGenericFields);
	}
```

save的源码表明, 如果对象已经保存, 只会update. 由于你是从数据库取出来的, 如果没有执行删除的话, 那么他一定会走doUpdateAction, 这里的update就是原样保存, 郭神只是在update函数中做了默认值处理, 在其他函数中的update都没处理. 可以还原默认值的

**Comment by guolindev** [comment]
楼上已经解答这个问题了，其实这个问题在主页用法文档上就有写，可以点击链接查看 https://github.com/LitePalFramework/LitePal#4-update-data
