### ISSUE TITLE
怎么创建数据库到指定的目录？

### ISSUE THREAD

**Issue by gaoqiu** [LitePalFramework/LitePal#480]
litepal.xml的标签里面指定数据库路径，怎么做？

**Comment by mtjsoft** [comment]
在litepal.xml里添加<storage value="dbpath/a/b/c"></storage> 
源码中可以看到。使用之前要申请内存卡读写权限。

**Comment by mtjsoft** [comment]
在litepal.xml里添加
`<storage value="a/b/c"></storage>标签`
源码中可以看到。
使用之前要申请内存卡读写权限。
这是源码
` String dbPath = Environment.getExternalStorageDirectory().getPath() + "/" + litePalAttr.getStorage();
  dbPath = dbPath.replace("//", "/");
`

**Comment by gaoqiu** [comment]
可以了，谢谢大神
