### ISSUE TITLE
数据库存储在外部文件夹，删除数据库文件后，重启app出现崩溃

### ISSUE THREAD

**Issue by gaoqiu** [LitePalFramework/LitePal#481]
数据库没有创建成功，导致
Failed to open database '/storage/emulated/0/Supoin/database/Supoin.db'.
                                                                        android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database

请问如何解决？

**Comment by mtjsoft** [comment]
为啥要删掉？有修改的话，直接升级版本就好了啊。

你把生成的“.db-journal”文件也删掉。然后把版本号改成“1”，再重新安装一下APP试试。

**Comment by gaoqiu** [comment]
用户可能会删除。有没有办法不用改代码解决崩溃的问题？

**Comment by guolindev** [comment]
这也是我不建议把数据库放在sd卡的原因，你无法预知用户会有什么样的行为。既然做这种操作，基本的异常捕获是要做的，不修改代码这个问题可能是无法解决的。

**Comment by gaoqiu** [comment]
数据库放在SD卡是需求来的。
重启应用程序出现崩溃，我查找了原因大概是无法创建出新的数据库文件，具体的底层代码还没看得太明白。
如果重启设备后，再打开应用程序，这样的步骤就能创建出新的数据库文件，程序能正常运行，没有出现崩溃。
