### ISSUE TITLE
Debug版本可以创建数据库，但是生成apk后就出了问题

### ISSUE THREAD

**Issue by SailFlorve** [LitePalFramework/LitePal#485]
Debug版本正常，生成apk后，查看数据库表项只有一个android_metadata，映射的表不见了。

**Comment by guolindev** [comment]
应该是实体类都被混淆了，参考一下主页文档中配置混淆的规则 https://github.com/LitePalFramework/LitePal/#proguard ，加入到你的proguard文件当中，然后再打realease版的apk应该就正常了。
