### ISSUE TITLE
卡顿问题

### ISSUE THREAD

**Issue by ToastYang** [LitePalFramework/LitePal#487]
当手机存储内存低于10G的时候  频繁操作数据库会出现卡段现象(异步存储 耗时问题)

**Comment by guolindev** [comment]
这个问题看上去不像是LitePal的问题，因为LitePal只是在原生数据库API上进行了简化使用的封装，是不涉及手机存储空间的。如果手机存储空间过低导致操作数据库时会变卡，那么原生数据库操作应该也会变得很卡。

由于问题久远我就先将问题关闭了，假如还有疑问的话请再重新打开。
