### ISSUE TITLE
类型转换问题

### ISSUE THREAD

**Issue by GEN-LD** [LitePalFramework/LitePal#488]
1、报错
java.lang.ClassCastException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class

2、报错代码
List<ProjectTreeDataBean> projectTreeDataBeans = LitePal.findAll(ProjectTreeDataBean.class);

3、实体类
public class ProjectTreeDataBean extends LitePalSupport {

    @JSONField(name = "id")
    private int mid;
    private int courseId;
    private String name;
    private int order;
    private int parentChapterId;
    private boolean userControlSetTop;
    private int visible;

    public int getCourseId() {
        return courseId;
    }

    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }

    public int getMid() {
        return mid;
    }

    public void setMid(int id) {
        this.mid = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    public int getParentChapterId() {
        return parentChapterId;
    }

    public void setParentChapterId(int parentChapterId) {
        this.parentChapterId = parentChapterId;
    }

    public boolean isUserControlSetTop() {
        return userControlSetTop;
    }

    public void setUserControlSetTop(boolean userControlSetTop) {
        this.userControlSetTop = userControlSetTop;
    }

    public int getVisible() {
        return visible;
    }

    public void setVisible(int visible) {
        this.visible = visible;
    }

}

**Comment by GEN-LD** [comment]
没有用泛型

**Comment by xiexin52k** [comment]
```java
List<String> balabala....
```

**Comment by guolindev** [comment]
没有足够的信息判断问题。
