### ISSUE TITLE
use encryption annotation

### ISSUE THREAD

**Issue by mosione70** [LitePalFramework/LitePal#489]
how can i use encryption annotation in litepal orm?
Should this be used?
@Encrypt(algorithm = "aes")

**Comment by guolindev** [comment]
Right. Both @Encrypt(algorithm = MD5) and @Encrypt(algorithm = AES) are valid based on your encryption decision.

**Comment by mosione70** [comment]
> Right. Both @Encrypt(algorithm = MD5) and @Encrypt(algorithm = AES) are valid based on your encryption decision.

I meant initializing
I found it after searching:
LitePal.aesKey(LITEPAL_AESKEY);

Thanks
