### ISSUE TITLE
提一个saveOrUpdate函数的建议

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#490]
1. saveOrUpdate 条件符合就更新, 否则执行保存.
2. update 根据id去更新. 但是不会更新字段为默认值的列.

现在有一个问题. 
执行saveOrUpdate, 如果条件符合, 执行更新.但是他没有update 的特性. 如果对象中有个 String 的字段为空, 执行这个函数之后, 会将表中对应的这个字段值清空了. 那么这个函数给人的感觉并不是saveOrUpdate, 反而更加像 "replace". 
现在出现了鱼与熊掌不可兼得的问题. 就是我想要saveOrUpdate 功能, 同时又保留update 的特性. 目前的方案好像实现不了, 只能自己重写逻辑; 
例如:
```java
public boolean saveOrUpdate() {
        if (TextUtils.isEmpty(activityId) || TextUtils.isEmpty(contentId)) return false;
        ActivityContentInfo dbInfo = LitePal.select("id")
                .where("activityId=? AND contentId=?", activityId, contentId).findFirst(ActivityContentInfo.class);
        return dbInfo == null ? super.save() : super.update(dbInfo.id) > 0;
    }
```
郭神有没有考虑添加类似于这种逻辑?

**Comment by xiexin52k** [comment]
我提这个问题的初衷是有一个场景：

数据实体有一些boolean类型的逻辑字段，比如用来决定是否已下载的字段isDownload，默认值是false没错吧，然后下载之后，这个值变为true，这个没问题。

接着，我去请求API，根据json得到实体，这个实体部分字段有更新，由于isDownload这个字段是我另外加的逻辑字段，json肯定解析不出来，那么这个对象自然而然他的isDownload是false了， 肯定不想把这个isDownload还原啊，因为这个我已经下载了，如果用update就没问题，用saveOrUpdate就会将这个字段还原，变成了未下载，然后下载那边根据isDownload标记取值的时候又会取到这个对象进行下载，虽然下载工具做了处理不会重复下载，但是需要更新一下字段值，平白无故多了一些操作

**Comment by guolindev** [comment]
确实存在你说的这个问题，但是我之所以这么设计，是认为你既然要save一条数据，那么对象中的数据应该是set全的，没设置的数据那么在数据库中就是没有这个数据的。

save中既然是这个逻辑，那么update中也是适用的，所以save和update要一致。如果实现你想所想要的功能，并不是不行，只是恐怕也会给一些人造成困扰，就是如果我就是想把对象中的某个数据清空怎么办？这个就很难处理了。

所以对于你的这种需求，可能先查再更新是一种更好的选择，而不应该优先使用saveOrUpdate这个API。
