### ISSUE TITLE
数据修改的bug

### ISSUE THREAD

**Issue by 328629033** [LitePalFramework/LitePal#50]
News news = new News();
news.setReadCount(0);
news.update(1);
这种方式是更新不了readCount的
ContentValue value = new ContentValue();
value.put("readCount", 0);
DataSupport.update(News.class, 1);
这种是可以更新的，看了下源码没发现什么问题，求解

**Comment by sinyu890807** [comment]
0是默认值，请使用setToDefault，具体原因参考 https://github.com/LitePalFramework/LitePal/issues/32
