### ISSUE TITLE
提问：多对多的表如何添加数据

### ISSUE THREAD

**Issue by NARUTONBM** [LitePalFramework/LitePal#502]
我有一个Movie表
`
public class Movie extends LitePalSupport {
    ···
    private List<Genre> mGenreList;
    ···
}
`
一个Genre表
`
public class Genre extends LitePalSupport {
    ···
    private List<Movie> mMovieList;
    ···
}
`
这两个表是多对多关联，并且Genre表会在应用第一次启动创建并写入数据后基本保持不动，Movie则要频繁的CRUD，假设我在新增一条movie数据时，如何操作，才能确保Litepal生成的中间表genre_movie.db会加上相关的数据。

**Comment by shuhaoLIN** [comment]
同问！求有解决方案告知一声！谢谢

**Comment by Angelhand** [comment]
> 同问！求有解决方案告知一声！谢谢

https://blog.csdn.net/guolin_blog/article/category/2522725

**Comment by guolindev** [comment]
首先find出你的Genre，然后new Movie的时候往mGenreList里面去添加你刚才find出来的Genre，然后保存movie，这样genre_movie.db就会加上相关的数据了。
