### ISSUE TITLE
数据库创建和升级监听没有回调

### ISSUE THREAD

**Issue by archerLj** [LitePalFramework/LitePal#503]
LitePal Version: 3.0.0

在自己的MyApplication onCreate()方法里添加了下面的监听：
```
        LitePal.registerDatabaseListener(object : DatabaseListener {
            override fun onCreate() {
                print("DB created.")
            }

            override fun onUpgrade(oldVersion: Int, newVersion: Int) {
                print("DB upgrade from version $oldVersion to $newVersion")
            }
        })
```

然后，添加了表里的字段，也修改了`litepal.xml`里的`<version value="2" />`，重新运行，还是不走`onUpgrade(...)`回调。

不知道是用的姿势不对，还是其他原因？

**Comment by guolindev** [comment]
需要注意的是，registerDatabaseListener()方法一定要确保在任何其他数据库操作之前注册，注册完之后你要操作一下数据库才会执行升级，不进行任何数据库操作是不会升级的，就比如说你save一条数据的时候，LitePal会发现versoin现在增加了，这个时候会先升级数据库，然后再去执行save数据。
