### ISSUE TITLE
当在for循环内进行数据插入的时候，出现了一堆如下日志 是什么问题？

### ISSUE THREAD

**Issue by azhon** [LitePalFramework/LitePal#504]
```
PkgTable table = new PkgTable();
table.setPkgNo("34");
table.setPkgData("AF5F");
table.setType("2");
table.save();
```
<img width="812" alt="qq20190222-095058 2x" src="https://user-images.githubusercontent.com/20559556/53214452-96cccd80-3687-11e9-9c7e-1fc40095a45d.png">

**Comment by guolindev** [comment]
因为每次save都会执行一次transaction，而如果在循环中大量执行save就会频繁执行事务，从而降低存储效率，如果是要存储集合数据的话可以考虑使用LitePal.saveAll()方法。
