### ISSUE TITLE
程序使用一段时间后（大概一个月）有概率会出现保存数据异常，只能卸载重装软件才能解决问题

### ISSUE THREAD

**Issue by LuffYH** [LitePalFramework/LitePal#506]
ExceptionName:org.litepal.exceptions.LitePalSupportException,
ClassName:org.litepal.crud.SaveHandler,
MethodName:throwIfSaveFailed,LineNumber:337

**Comment by guolindev** [comment]
仅从日志上看，是因为保存失败所抛出的异常。但是我也无法定位出来保存失败的原因。

因为这个问题太久了，我就先关掉了，如果还有再关注这个问题的人，可以重新打开。
