### ISSUE TITLE
查询结果多出baseObjId这个字段的问题

### ISSUE THREAD

**Issue by yunyoulangji** [LitePalFramework/LitePal#507]
查询结果多出baseObjId这个字段、怎么剔除？
另外用.select条件只查两列的数据、但是返回的结果会自动多带出一列的结果、有人遇到过这个问题吗？
求大神帮忙解惑下

**Comment by guolindev** [comment]
baseObjId是LitePalSupport类里的字段，这个字段是LitePal内部使用的，开发者用不着，而且也访问不到，我不知道你是怎么样写的代码导致结果里多带出一列结果，这个字段你除非用反射，要不然是无法获取到的。
