### ISSUE TITLE
数据库更新问题

### ISSUE THREAD

**Issue by wscgithub** [LitePalFramework/LitePal#510]
一开始我从网络中获取到50条数据导入数据库中，隔十分钟之后，我再重新获取，得到49条，再导入到数据库，可是数据库还是 显示50条，这个问题改怎么处理呢，我现在的解决办法是先deleteAll(),然后在导入数据库，这样的话，主键id会从51开始增加

**Comment by guolindev** [comment]
你的做法就是对的，id从多少开始都无所谓，因为id和业务逻辑无关。
