### ISSUE TITLE
org.litepal.exceptions.LitePalSupportException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by sdgSnow** [LitePalFramework/LitePal#511]
List<PccBaseQuota> pccBaseQuotas = LitePal.where("project_code = ?", project_code).find(PccBaseQuota.class);
存储几十条上百条数据没问题，数据量达到几百条后，再去查询就会报错Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
请问下这个是什么问题呢

**Comment by sdgSnow** [comment]
` List<PccBaseQuota> pccBaseQuotas = LitePal.where("project_code = ?", project_code).find(PccBaseQuota.class);
            if (pccBaseQuotas.size() > 0) {
                baseQuota.updateAll("project_code = ?", project_code);
                Log.i("test_quota", "更新指标数据成功");
                saveTaskData(project_code);
                startTaskActivity();
            } else {
                boolean save = baseQuota.save();
                if (save) {
                    startTaskActivity();
                    Log.i("test_quota", "保存指标数据成功");
                    saveTaskData(project_code);
                } else {
                    Log.i("test_quota", "保存指标数据失败");
                }
            }`

这个是我保存更新的代码

**Comment by yunyoulangji** [comment]
我今天也遇到了、老哥解决了吗

**Comment by sdgSnow** [comment]
没有，原因查询好像是因为单个字段里面数据过大，sqlite不支持，你可以看看你要查询的那个字段内容数据是不是很大

**Comment by guolindev** [comment]
确实和字段数据过大有关，这里附上一篇介绍这个问题的链接 https://stackoverflow.com/questions/21432556/android-java-lang-illegalstateexception-couldnt-read-row-0-col-0-from-cursorw
