### ISSUE TITLE
org.litepal.exceptions.InvalidAttributesException: the version in litepal.xml is earlier than the current version

### ISSUE THREAD

**Issue by zhangchun123** [LitePalFramework/LitePal#514]
![image](https://user-images.githubusercontent.com/13727654/55376472-18dfca00-5543-11e9-8f26-d3ca92766915.png)

目前版本是  compile 'org.litepal.android:core:1.5.1'

需要升级到：  compile 'org.litepal.android:java:3.0.0'版本可以解决吗？

**Comment by yzp-linkfuture** [comment]
3.0.0也存在这个问题

**Comment by guolindev** [comment]
这个问题是你手机当前数据库的版本号比你当前项目工程里的版本号低，数据库是不能降级的。将litepal.xml中的版本号提升即可。
