### ISSUE TITLE
DataSupport.where 多个条件+条件多个值 查询

### ISSUE THREAD

**Issue by zouxianbincc** [LitePalFramework/LitePal#515]
DataSupport.where("cityId = ? and longStoreCode = ?", "289","101232712,310031008")
.find(ShopInfo.class)

查询条件是 城市ID  这个城市ID 下 longStoreCode字符等于 101232712或310031008 

按我上面写的，查不出结果

**Comment by 505541778** [comment]
or

**Comment by kystudio** [comment]
DataSupport.where("cityId = ? and (longStoreCode = ? or longStoreCode = ?)", "289","101232712","310031008")
.find(ShopInfo.class)

**Comment by guolindev** [comment]
谢谢楼上提供的正确答案。
