### ISSUE TITLE
升级表导致数据清空

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#518]
我项目从以前版本升级到最新版, 测试老是报部分表数据被清空的情况, 我百思不得其解. 今天发现了一篇博客:
https://blog.csdn.net/klylove/article/details/81011823
里面有这么一段话:
```
以下一些升级情况LitePal无法处理并且被升级表格里的所有数据将被清空：

添加了一个标注为 unique = true 的属性；
修改某个属性的标注为 unique = true；
修改某个属性的标注为 nullable = false；
以上情况会导致数据丢失，要格外注意。
```
我再对比一下我的提交记录. 刚好发现我代码做了如下变更
```java
 /** 文件的存放路径不能为空 */
    @Column(nullable = false)
    public String filePath;
```
这个字段以前没注解的, 后来升级添加了一个注解. 由于我将这个封装了一下, 导致我所有继承这个类的表信息全部被清空, 我修复了四个版本还没修复彻底.
今天一个会数据库的大佬听说了这个问题, 就提了一下是不是既定属性升级是不能变更导致这个BUG的, 因为用SQL语句执行升级会报错, 大家都能明显知道. 可能LitePal做了一些处理, 会忽略错误自动强制升级导致数据丢失.

**Comment by guolindev** [comment]
这个问题在LitePal首页的说明文档里就有描述：

But there are some upgrading conditions that LitePal can't handle and all data in the upgrading table will be cleaned:

Add a field which annotated as unique = true.
Change a field's annotation into unique = true.
Change a field's annotation into nullable = false.
Be careful of the above conditions which will cause losing data.

之所以会这样，是因为你新增了一个要求不能为null的字段，但是LitePal帮你加上了这个字段之后，它的默认值必然是null，这和你所做的字段声明是不符的。

这种情况下，LitePal只能做两种处理，要么把表中所有的字段清空，要么就程序报错，升级失败。

我选择了用前者是因为我认为这种字段声明并不是一个错误的声明，因为单纯从代码层面来讲这种声明完全没有问题。只是当你的表中原来有数据时，这种做法一定要非常谨慎。
