### ISSUE TITLE
郭神下个版本可不可以考虑加密功能，顺便讲讲sqlite加密感谢郭神

### ISSUE THREAD

**Issue by coderloveryan** [LitePalFramework/LitePal#52]

**Comment by androidxiaobai** [comment]
或者在博客上讲一下数据库加密吧郭神

**Comment by guolindev** [comment]
LitePal 从1.6.0版本开始支持加密功能了，具体用法可以参考这篇文章 https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650240766&idx=1&sn=096f029aa531d5d99191c3d4c9126fc1&chksm=88638791bf140e87721abb26b32b68233153ccff50f2940d173cd5108bff42287d42db9304d9#rd

谢谢支持。
