### ISSUE TITLE
异步查询耗时异常

### ISSUE THREAD

**Issue by zzh3321** [LitePalFramework/LitePal#523]
只有一条数据的情况，异步查询耗时要300毫秒，非异步只要5毫秒，是否正常？
`loge("time : "+System.currentTimeMillis())`
`LitePal.findAllAsync(AppConfigBean::class.java).listen {`
`loge("time : "+System.currentTimeMillis())`
`}`

**Comment by guolindev** [comment]
线程调度也是要时间的啊，这和LitePal的查询时间无关，你这样测试肯定是不准确的。
