### ISSUE TITLE
LitePalApplication这个为什么不做成一个 init(Context context ) 传参传进去啊.这样继承有点不妥

### ISSUE THREAD

**Issue by wutong751** [LitePalFramework/LitePal#524]

**Comment by sdwfqin** [comment]
![image](https://user-images.githubusercontent.com/13191807/56861222-7f84c600-69d1-11e9-84b7-7dcedaa73831.png)

**Comment by guolindev** [comment]
楼上正解，而且文档里也写的很清楚了。
