### ISSUE TITLE
org.litepal.exceptions.DataSupportException

### ISSUE THREAD

**Issue by androidVHappy** [LitePalFramework/LitePal#526]
版本1.6  现在经常偶发性出现这个bug
org.litepal.exceptions.DataSupportException

Cursor window allocation of 2048 kb failed.

org.litepal.crud.DataHandler.query(DataHandler.java:141)

郭神  要怎么解决呢？谢谢

**Comment by guolindev** [comment]
https://github.com/LitePalFramework/LitePal/issues/576
