### ISSUE TITLE
org.litepal.exceptions.DataSupportException  unable to open database file (code 14)  org.litepal.crud.DataHandler.query(DataHandler.java:141)

### ISSUE THREAD

**Issue by androidVHappy** [LitePalFramework/LitePal#527]
DataSupport.findAll(IotLogRecord_info.class); 
报下面的问题
org.litepal.exceptions.DataSupportException

unable to open database file (code 14)

org.litepal.crud.DataHandler.query(DataHandler.java:141)

为什么会经常发生这个问题呢？  我表在  可能表没有数据

**Comment by guolindev** [comment]
如果是偶发性出现的话可能和具体的设备相关。

如果是经常发生的话，感觉会不会是和死锁有关系。我找了一篇这个错误的链接，可以参考一下 https://stackoverflow.com/questions/34488306/unable-to-open-database-file-code-14-while-compiling-pragma-journal-mode

另外这个问题过于久远，我先close掉，如果还有疑问请重新打开。
