### ISSUE TITLE
在升级监听onUpgrade中findAll报错java.lang.IllegalStateException: getDatabase called recursively

### ISSUE THREAD

**Issue by biyeshengplay** [LitePalFramework/LitePal#528]
LitePal.registerDatabaseListener(new DatabaseListener() {
            @Override
            public void onCreate() {
                // fill some initial data
                Log.d(TAG, "DatabaseListener.onCreate");
            }

            @Override
            public void onUpgrade(int oldVersion, int newVersion) {
                // upgrade data in db
                Log.d(TAG, "DatabaseListener.onUpgrade oldVersion: " + oldVersion + " newVersion: " + newVersion);
                if (oldVersion <= 12) {
                    List<StorageModel> localData = null;
                    try {
                        localData = LitePal.findAll(StorageModel.class);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        });

05-08 17:22:40.061  6038  6038 W System.err: java.lang.IllegalStateException: getDatabase called recursively
05-08 17:22:40.062  6038  6038 W System.err: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:215)
            05-08 17:22:40.062  6038  6038 W System.err: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:175)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:63)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.tablemanager.Connector.getDatabase(Connector.java:75)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.Operator.findAll(Operator.java:1116)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.Operator.findAll(Operator.java:1082)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.LitePal.findAll(LitePal.java:798)
            05-08 17:22:40.062  6038  6038 W System.err: 	at com.lay.storage.Storage.onUpgrade(DKStorage.java:62)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.tablemanager.LitePalOpenHelper.onUpgrade(LitePalOpenHelper.java:98)
            05-08 17:22:40.062  6038  6038 W System.err: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:272)
            05-08 17:22:40.062  6038  6038 W System.err: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:175)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:63)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.tablemanager.Connector.getDatabase(Connector.java:75)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.Operator.getDatabase(Operator.java:96)
            05-08 17:22:40.062  6038  6038 W System.err: 	at org.litepal.LitePal.getDatabase(LitePal.java:65)
            05-08 17:22:40.062  6038  6038 W System.err: 	at com.lay.storage.Storage.init(DKStorage.java:85)

**Comment by guolindev** [comment]
此问题已修复，对应提交 https://github.com/LitePalFramework/LitePal/commit/cf57c6481f707a25fbd7bf222fa6c1589a6da582

LitePal的下个版本中将会包含修复后的内容。
