### ISSUE TITLE
数据库升级后,改变表字段，所有数据丢失。

### ISSUE THREAD

**Issue by MartinMu2016** [LitePalFramework/LitePal#532]
版本:3.0.0
类:
public class MediaFile extends LitePalSupport {
    @Column(unique = true)
    private int id;
    @Column(unique = true)
    private String  msgSvrId;
    private String test1;
   ...
}
我给MediaFile添加了一个字符test1字段,修改litepal.xml的配置文件升级数据库后，数据全部消失，不知道原因。我看简介中提示添加会导致数据清零
But there are some upgrading conditions that LitePal can't handle and all data in the upgrading table will be cleaned:

Add a field which annotated as unique = true.
Change a field's annotation into unique = true.
Change a field's annotation into nullable = false.

但是，我只是添加一个字符字段，不知道为啥会出现此情况。

**Comment by po1xiao** [comment]
我也遇到这个问题

**Comment by guolindev** [comment]
因为你给id声明了@Column(unique = true)，实际上id是不需要声明unique的，声明了也不会起作用，因为主键本身就已经具备唯一性了，所以只要你把id上的注解去掉就能正常了。

不过这个确实是也LitePal的bug，我已经修复了这个问题，新版的LitePal当中将不会再有这个情况，谢谢指出。
