### ISSUE TITLE
标签不能被识别 (Tag cannot be determined)

### ISSUE THREAD

**Issue by oscarrr112** [LitePalFramework/LitePal#535]
我在写编译程序的时候突然编译失败，错误提示如下：
/Users/pengao/Desktop/toDo/app/src/main/res/assets/litepal.xml: Error: Can't determine type for tag '<dbname value="checklist"/>'

求大神解答

**Comment by guolindev** [comment]
感觉这个可能是特定版本as的问题，参考这篇文章看一下吧 https://stackoverflow.com/questions/54915733/android-studio-3-3-1-color-xml-error-cant-determine-type-for-tag-selector-x
