### ISSUE TITLE
新增表中有unique 注解字段也会导致表数据清空丢失

### ISSUE THREAD

**Issue by ihewro** [LitePalFramework/LitePal#537]
在首页看到了这些情况：
```
Add a field which annotated as unique = true.
Change a field's annotation into unique = true.
Change a field's annotation into nullable = false.
Be careful of the above conditions which will cause losing data.
```

但是我新增了一个新的表，表中有unique字段也会导致数据库数据全部丢失。新的表和之前表没有任何关联，这个地方可以优化的吗

**Comment by guolindev** [comment]
我完全按照你说的流程操作了一遍，但是无法重现这个问题。

1. 首次创建一张Album表，里面有unique字段，然后存储了几条数据。
2. 创建一张新的News表，里面也有unique字段。
3. 将litepal.xml版本加1。
4. 执行升级操作。

结果是Album中的数据都正常保存下来了，并没有出现数据丢失的情况。

由于我这边在几台设备上都无法复现，现在只能怀疑可能是和特定设备相关。

我先将这个问题关闭，如果你还在继续关注这个问题，请再重新打开，并帮助复现这个情况。
