### ISSUE TITLE
多张表同时更改和新增，统一加事物

### ISSUE THREAD

**Issue by wangqiaozhang** [LitePalFramework/LitePal#538]
同时要保存或者修改几张表的数据例如：     
            sign.save();
            userBase.update(userBase.getId());
            DataSupport.saveAll(lstOld);
这种情况下，可以加事物吗

**Comment by wangqiaozhang** [comment]
通过阅读代码，save()和saveAll()方法开启了事物，而update()方法没有开启事物，所以对增加了两个方法
 
  /**
     * 不开启事务
     */
    public synchronized void saveNoTransaction() {
        SQLiteDatabase db = Connector.getDatabase();
        try {
            SaveHandler saveHandler = new SaveHandler(db);
            saveHandler.onSave(this);
            clearAssociatedData();
        } catch (Exception e) {
            throw new DataSupportException(e.getMessage(), e);
        }
    }

    public static synchronized <T extends DataSupport> void saveAllNoTransaction(Collection<T> collection) {
        if (collection == null || collection.size() == 0) {
            return;
        }
        SQLiteDatabase db = Connector.getDatabase();
        try {
            SaveHandler saveHandler = new SaveHandler(db);
            saveHandler.onSaveAllSmt(db, collection);
        } catch (Exception e) {
            throw new DataSupportException(e.getMessage(), e);
        }
    }

然后使用的时候：   SQLiteDatabase db = Connector.getDatabase();
            db.beginTransaction();
            try {
                sign.saveNoTransaction();
                userBase.update(userBase.getId());
                DataSupport.saveAllNoTransaction(lstOld);
                db.setTransactionSuccessful();
            }catch (Exception e){

            }finally {
                db.endTransaction();
            }

不知道这种做法有什么潜在的风险？希望大神指导一下

**Comment by guolindev** [comment]
LitePal目前确实没有跨多个数据库操作添加事务的方法，这块api设计得确实不好，之后的版本我可能会对事务这块重新设计，谢谢建议。
