### ISSUE TITLE
默认值设置存在不合适的地方

### ISSUE THREAD

**Issue by fzn0268** [LitePalFramework/LitePal#54]
模型中的原始类型成员通过反射产生新对象后，对象中的那些成员都被初始化成0，而更新数据时用来比较默认值的空模型就是反射出来的。这样造成未设置默认值的原始类型成员无法更新回0，只有通过setToDefault方法，或者说未设置默认值的原始类型成员隐含了0默认值。
另外，新条目保存时除了引用类型成员能被赋默认值（因为操作数据库前产生的ConstantValues没有对应键，数据库使用建表时的默认值参数），原始类型成员都不能被赋上默认值。
现已知用save方法更新数据可以使原始类型更新回默认值，而update方法会检查新值和默认值。但是在博客里没发现save也能更新……可以强调一下。
还有setToDefault方法只对原始类型有效，对引用类型无效，问题也是在空模型上。

**Comment by sinyu890807** [comment]
设计如此，原因我以前在博客上也解释过，如果有更好的办法欢迎建议。我把博客上解释的贴过来一下。
比如News类里面有title，message和commentcount这样几个字段，那么现在写了下面这样一段代码来更新：
News n = new News();
n.setTitle("aaa");
n.update(id);
那么请问，这里我想更新的是哪个信息？肯定是title吧。OK，那么这个时候message的值是什么呢？是null，commentcount是什么呢？是0。也就是说如果这里不加判断的话，那么就会把message和commentcount的值都清空了，不可能要求开发者，想更新一个title的值，然后要把message，commentcount等其它字段每个值都set一遍吧？所以我设计的时候就是判断如果调用update这个方法更新的时候字段的值是默认值，那就不更新。想要更新成默认值，调用setToDefault()方法。

**Comment by fzn0268** [comment]
嗯，当时领会错了，以为默认值只是在插入新条目时对没有set过的属性有用，以后直接set完再update可以随便改，set回默认值也行，用的时候发现不是这意思，就不知道怎么办了，又来翻代码。后来才发现对已有的对象用save方法能达成我的目的，但是博客和readme里面都没见过这种例子。
不过如果能像这样：
1，加入新条目，如果某个字段有默认值注解，加入时没有set过，就set默认值。
2，还是News类里面有title，message和commentcount这样几个字段，message和commentcount都分别注解了默认值“empty”和0，数据库里面已有条目[id:3,title:"abc",message:"hello",commentcount:5]，那么现在写了下面这样一段代码来更新：
News n = new News();
int id = 3;
n.setTitle("aaa");
n.setMessage("empty");
n. setCommentCount(0);
n.update(id);
按现在，title是变成aaa了，但是message和commentcount都没变成“empty”和0，因为它们和默认值相同，所以仍然是“hello"和5。如果能提供另一个update方法，使得即便set值与默认的相同，字段也能set过来，而且不会清空已有值的字段，不需要重新set其他的值。因为有些时候，特别是数字字段，记录的是一个连续区间的值，而且默认值又处于这个区间内，如果set回默认值要另一个方法，那么我必须为了set回默认值加入一个判断，就不太方便。要是用save，也必须先find出来那个id的对象才行，不能直接save某个id。

2016年2月19日 09:57，Tony Green <notifications@github.com>写道：设计如此，原因我以前在博客上也解释过，如果有更好的办法欢迎建议。我把博客上解释的贴过来一下。
比如News类里面有title，message和commentcount这样几个字段，那么现在写了下面这样一段代码来更新：
News n = new News();
n.setTitle("aaa");
n.update(id);
那么请问，这里我想更新的是哪个信息？肯定是title吧。OK，那么这个时候message的值是什么呢？是null，commentcount是什么呢？是0。也就是说如果这里不加判断的话，那么就会把message和commentcount的值都清空了，不可能要求开发者，想更新一个title的值，然后要把message，commentcount等其它字段每个值都set一遍吧？所以我设计的时候就是判断如果调用update这个方法更新的时候字段的值是默认值，那就不更新。想要更新成默认值，调用setToDefault()方法。
