### ISSUE TITLE
如何将lib module的assets/litepal.xml与app module的assets/litepal.xml合并

### ISSUE THREAD

**Issue by jiejingzhiguo** [LitePalFramework/LitePal#540]
lib模块中有一张表，这张表会被多个应用模块使用，所以希望能在lib模块的assets/litepal.xml中注册这张表，而不是每个应用模块都在assets/litepal.xml中注册这张表。目前发现的问题是在lib中定义的assets/litepal.xml打包成apk后仍然报找不到表的异常。不知道这种情况有没有什么办法解决呢？

**Comment by guolindev** [comment]
lib的模块中不需要定义litepal.xml，这个文件是在运行时才会去读取的，开发时并不需要，所以只需要在你的主模块中放一份就可以了。
