### ISSUE TITLE
升级数据库，字段类型修改后如何升级

### ISSUE THREAD

**Issue by HahalongGit** [LitePalFramework/LitePal#541]
需求：旧版的数据类中有一个int类型的字段，新版半中字段类型需要修改位long类型。
按照sqlite中sql的操作方式，应该可以删除这个表重新生成，这就新的表对应的int字段就可以修改位long类型了。使用litePal似乎没有相应的直接删除表的操作，或者其他办法。代码会在调用查询的时候报错ClasscastException，类型int不能转换为long.(如这个操作：DataSupport.findFirst(UserInfo.class);)

**Comment by guolindev** [comment]
LitePal是有升级字段的功能，只是升级的字段数据会全部丢失，表中的其他数字不会丢失。

升级方式是在model当中修改好数据类型，然后在litepal.xml里面把版本号加1就可以了。
