### ISSUE TITLE
关于query在android9.0上面报空指针问题

### ISSUE THREAD

**Issue by DaveBoy** [LitePalFramework/LitePal#546]
错误信息：java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
错误原因：实体如果实现了Parcelable，在某些版本就会导致
在发现构造参数类型为android.os.Parcel无法匹配屏蔽规则

if (parameterType == modelClass) {<br>
       key = key + 10000; // plus the key for not using this constructor<br>
} else if (parameterType.getName().startsWith("com.android") &&parameterType.getName().endsWith("InstantReloadException")) {<br>
      key = key + 10000; // plus the key for not using this constructor<br>
}

就会导致getInitParamValue方法中无法匹配具体的参数类型，会递归调用createInstanceFromClass这时候就报错了，因为Parcel在android9.0上面获取到的构造方法为null（在7.0不闪退是因为能获取到一个long类型的构造，实际上9.0上面也有这个构造方法，怀疑是跟高版本系统api的反射限制有关）然后就出现了上面的错误提示
处理方式：
1.不要实现Parcelable（从使用者上解决问题）
2.从源码解决，在屏蔽规则上面加上android.os.Parcel

**Comment by DaveBoy** [comment]
targetSdkVersion 28

**Comment by guolindev** [comment]
LitePal的查找构造方法的机制是这样子的，优先使用参数最少的构造函数。

也就是如果你的类中有无参数的构造函数，LitePal一定会最先使用这个，没有的话就会依次找一个、两个参数的构造函数。

而找到了有一个参数的构造函数，比如你说的Parcel对象，LitePal并不会自动创建一个Parcel对象传给你，而是会直接传null作为默认值，所以你在构造方法里一定要做非空判断。

至于你说的屏蔽android.os.Parcel，我认为有点难，因为如果一个类当中就有只带Parcel参数的这一个构造方法，再把它屏蔽的话，那就更没有构造方法可用了。

所以我认为这个问题还是应该在使用层面解决，其实只你要再定义一个无参的构造方法就可以了，LitePal会优先用它来创建实例的。

**Comment by MacroShaw** [comment]
直接在实现Parcelable类的里加了个无参方法解决了
