### ISSUE TITLE
加密的字段不能用于where查询吗

### ISSUE THREAD

**Issue by BibuYing** [LitePalFramework/LitePal#547]
@Encrypt(algorithm = AES)  
val phone: String,
val uid: Int

加密后的phone字段就不能查询到，请问是我还少加了哪些配置吗

**Comment by guolindev** [comment]
是的，加密后的字段是不可以用来当作查询条件的，具体可以参考这篇文章 https://mp.weixin.qq.com/s/TSp36cnKLxUmAHjT86UCrQ
