### ISSUE TITLE
多层数据保存失败问题

### ISSUE THREAD

**Issue by 229222025** [LitePalFramework/LitePal#549]
当用litepal时，当对象A中包含List<B>  在A调用save()方法后List<B>中的数据没有被保存到数据库中，版本是kotlin:3.0.0，麻烦郭神帮忙看下是什么问题呢

**Comment by Dobiy** [comment]
我也出现这个问题，好像是save()的时候，list列表里的数据是空的话，数据会自动覆盖为空。

**Comment by 229222025** [comment]
> 我也出现这个问题，好像是save()的时候，list列表里的数据是空的话，数据会自动覆盖为空。

List中是有数据的，但就是保存不了，后面我把List中的数据转成json来保存的了

**Comment by Dobiy** [comment]
> > 我也出现这个问题，好像是save()的时候，list列表里的数据是空的话，数据会自动覆盖为空。
> 
> List中是有数据的，但就是保存不了，后面我把List中的数据转成json来保存的了

我直接改字段，存储表ID，然后连缀查询就好，保存json就没太大必要了。表关联都自己设计，不用他这种多表查询了。

**Comment by guolindev** [comment]
要看你的List中包含的是什么数据，如果List中包含的是基本数据类型或者是String，LitePal会自动帮忙保存。如果你的List中包含的是你自己定义的数据类型，这相当于是在做多对一或多对多的关系，这种情况下LitePal不会做自动级联存储，你要保存哪些数据需要自己手动存储，存储完成之后LitePal会自动帮忙建立它们之间的外键关联。
