### ISSUE TITLE
Android9.0不能操作数据库

### ISSUE THREAD

**Issue by tinger-mefus** [LitePalFramework/LitePal#550]
写入的话只能创建出库，但是没有表；读取就什么都读不到，报空指针错误。
百度、谷歌查了下，好像说是9.0使用了新的SQL读写方法。。。也没搞懂。
不管是LitePal还是原生操作，都这样。
同样的代码8.1没问题。

**Comment by tinger-mefus** [comment]
不是#546那样的问题。

**Comment by fuliteng** [comment]
我这边啥错误都没报，但有解决方法  LitePal.getDatabase().disableWriteAheadLogging();

**Comment by guolindev** [comment]
同样没遇到过这种问题，在10.0系统上也一切正常。

我先把issue关闭掉，如果题主这个问题还没解决的话，可以再重新打开。
