### ISSUE TITLE
请问Litepal支持IN操作符查询吗？

### ISSUE THREAD

**Issue by ICLzhang** [LitePalFramework/LitePal#551]
如题

**Comment by ZmjDns** [comment]
我试了一下，好像不支持in
报了如下错误：
syntax error (code 1): , while compiling: SELECT * FROM rid WHERE rid in ?

**Comment by ZmjDns** [comment]
支持的
kt：
LitePal.useDefault()
 val index = LitePal.where("rid in (\"1\",\"2\",\"3\")").find<Rid>()

**Comment by ICLzhang** [comment]
好的，谢谢我试过用LitePal.select().where("id in (?)",StringObject) 或者 LitePal.select("id").where(String.format("idin (%s)",StringObject ))  可行

**Comment by 18300072348** [comment]
@ICLzhang @ZmjDns  我用你们的这种方式，当in 的参数只有一个时，可以正常查询，多个时查不出来了

**Comment by ICLzhang** [comment]
> @ICLzhang @ZmjDns 我用你们的这种方式，当in 的参数只有一个时，可以正常查询，多个时查不出来了
你的问题解决了吗？

**Comment by onlycyndi** [comment]
我试了几次，开始的时候按照LitePal.select().where("id in (?)",StringObject) 是可行的，因为查询参数是一串数字吧，存的String,后来莫名其妙不行了，我就反复尝试，最后把查询的参数全部加上 "para1","para2","para3"这样来尝试，结果就可以了，我在MYSQL数据库反复试验了下，字符串的参数确实需要加引号，希望对你有用。顺带我的语句是：
`LitePal
                .where("memberId IN (${memberId})")
                .find(MemberListInfo::class.java)`

**Comment by guolindev** [comment]
不管是用in查询还是等号查询，当涉及到动态参数时，都应该使用占位符来进行替代，而不是手动进行字符串拼接。手动字符串拼接，不会因为你写了一个"rid in (abc, xyz)"就认为abc或xyz是字符串。你必须要给abc和xyz都加上引号数据库才会认为它们是字符串。而使用占位符就可以很好地解决这个问题。
