### ISSUE TITLE
是否可以通过Column注解，在删除时保留指定字段的关联表数据，测试发现delete和deleteAll 将关联表的数据都删了

### ISSUE THREAD

**Issue by steven-yan** [LitePalFramework/LitePal#552]

**Comment by guolindev** [comment]
这个是外键特性，关联表中持有关联数据的外键，如果不先将关联表中的数据删除，你想删除的数据也是删不掉的。

至于你说的这个功能，如果非要实现的话，可以先清除这些数据之间的关联关系，然后就再删除指定数据就不会互相影响了。
