### ISSUE TITLE
频繁切换数据库导致卡顿

### ISSUE THREAD

**Issue by ZmjDns** [LitePalFramework/LitePal#553]
我在进行数据查询操作的时候，因为有多数据库，来回切换查询的时候非常慢（用的是三星SM-TCAndroid系统4.4.2），希望大佬优化一下

**Comment by ZmjDns** [comment]
是不是可提供一个获取当前数据库名称的方法，用来判断是否为目的数据库，从而减少数据库来回切换的次数？

**Comment by guolindev** [comment]
因为LitePal也是不保存当前数据库的名字的，是你在调用LitePal.use()方法时传入的LitePalDB对象中数据库叫什么名字，LitePal就会去操作哪个数据库。所以如果你想获取的话，可以调用LitePalDB的getDbName()方法获取。但是这个方法获取的值其实也是你传进来的，所以到底目前用的哪个数据库，你比LitePal更清楚。你可以持久化保存一下正在使用的数据库名，如果和即将切换的数据库名一样的话，那么就不要再调用LitePal.use()方法了。
