### ISSUE TITLE
当保存的对象是static的时候，调用saveOrUpdate时返回true,但是查询的时候查不到数据

### ISSUE THREAD

**Issue by JJC319** [LitePalFramework/LitePal#555]
public static Student stu= new Student ();
stu.saveOrUpdate()

**Comment by guolindev** [comment]
能不能贴一下你是怎么查询数据的？

**Comment by guolindev** [comment]
实测static并不会对保存和查询造成什么影响，如果你那边还没有解决这个问题的话可以重新打开此issue。
