### ISSUE TITLE
初次建表时关于ClassCastException异常问题

### ISSUE THREAD

**Issue by VIPyinzhiwei** [LitePalFramework/LitePal#556]
环境
1、org.litepal.android:kotlin:3.0.0 版本
2、ext.kotlin_version = '1.3.11'

场景：
在创建完相关数据库表、并在配置文件里面声明后，首次进入app，调用 LitePal.count(WxUser::class.java) 后，
报错 Caused by: java.lang.ClassCastException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class

查找问题原因
1、通过异常堆栈信息，找到报错点，在 LitePalBase 类的 getGenericTypeClass 函数中，
(Class<?>) parameterizedType.getActualTypeArguments()[0]

2、根据提示，通过一些测试排除各种原因后，在我声明的某个数据库类表中，声明了这样一个类的集合，var wxRedEnvelopeMembers: List<WxRedEnvelopeMember> = ArrayList()，而在 WxRedEnvelopeMember  类里面使用了一个 open 的修饰符。

解决办法
在声明类集合对象字段时，一定要去掉在这个类里面 open 的修饰符，如果只是声明一个对象字段，则可以忽略。

**Comment by guolindev** [comment]
问题如果已解决我就先把这个issue close掉了。

**Comment by LJFDBXJ** [comment]
去掉 open 就是私有的，不可以继承了，该怎么解决呢

**Comment by LJFDBXJ** [comment]
@sinyu890807  我的问题 #610
