### ISSUE TITLE
后台返回给我这样的json，我该怎么存储查询？

### ISSUE THREAD

**Issue by SuperZiLu** [LitePalFramework/LitePal#560]
{
  "data": {
    "numberId": 101103001,
    "current": {
      "Order": 3408273
    }
  }
}

**Comment by queqianxi** [comment]
String a = "{
"data": {
"numberId": 101103001,
"current": {
"Order": 3408273
}
}
}";
        String data = JSON.parseObject(a).getString("data");
        int numberId = JSON.parseObject(data).getInteger("numberId");
        String current = JSON.parseObject(data).getString("current");
        int order = JSON.parseObject(current).getInteger("Order");
使用fastJson解析

**Comment by SuperZiLu** [comment]
@queqianxi 我知道怎么解析 我是问解析完了怎么用litepal把他存到数据库然后还能查询出来，我现在就是对象里面的current对象死活存不进去 怎么都是null，第二个就是激进查询不能按照数据库表里面的某个值进行查询嘛？因为我看郭神写的那个列子是用id去查的 但是实际项目里面根据id去查 没有意义啊 因为你不知道查出来的第一条或者第二条 是不是你需要的数据。

**Comment by queqianxi** [comment]
String data = JSON.parseObject(a).getString("data");
 int numberId = JSON.parseObject(data).getInteger("numberId");
 String current = JSON.parseObject(data).getString("current");
 int order = JSON.parseObject(current).getInteger("Order");
 DataBean dataBean = JSON.parseObject(data,DataBean.class);
 Current current1 = JSON.parseObject(current,Current.class);
 current1.save();
 dataBean.setCurrent(current1);
 dataBean.save();
DataBean dataBean = LitePal.where("numberId = ?","101103002")
                .findFirst(DataBean.class,true);

**Comment by SuperZiLu** [comment]
@queqianxi 多谢大佬 中午解决了 我是setCurrent 然后保存current 再存dataBean 也没有问题 感谢感谢 查询我也会了 先把数据库的数据全取出来 然后循环找到跟条件字段相符的对象 然后再得到这个对象数据库自动生成的id 就能根据激进查询吧数据跟关联表的数据查出来了。
