### ISSUE TITLE
是否有考虑支持INNER JOIN等语句？

### ISSUE THREAD

**Issue by xiazunyang** [LitePalFramework/LitePal#563]
因为我这边的离线使用情况较多，使用数据库的频率较高，其中INNER JOIN语句要经常使用，但是LitePal并不支持这个，只能使用findBySQL方法来实现，然后从Cursor获取结果。
有时候只有取一个数字，就很好办，但是有时候需要的是对象，就比较麻烦了。
所以要是LitePal能支持这个语法就好了。

**Comment by guolindev** [comment]
并不是我不想支持，而是无法支持。

只要涉及到关联表的查询，就会出现超出你实体类定义的列的情况，你inner join了另外一张表，那么获取到的数据就是关联到两个类当中的，这对于LitePal来说是无法处理的。

所以这种情况下，用findBySQL是我能想到的最好方式。或者你可以尝试一下Room，Room是针对你写的查询语句自己重新定义实体类的，可以把查询到的结果重新封装成一个新的实体类作为结果。
