### ISSUE TITLE
'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()'

### ISSUE THREAD

**Issue by GitHubWison** [LitePalFramework/LitePal#564]
版本：  implementation 'org.litepal.android:kotlin:3.0.0'
使用的是android x
kotlin环境
beans:
----------------------------------------------------
data class Child(var name:String?,
                 var age:String?,
                 var parent:List<Parent>):LitePalSupport()
data class Parent(var name:String?,
                  var age:String?):LitePalSupport()
----------------------------------------------------

save 方法:
---------------------------------------------------
  val father = Parent("pp","45")
        father.save()
        val mother = Parent("mm","45")
        mother.save()
        val list = ArrayList<Parent>()
        list.add(father)
        list.add(mother)
        LitePal.saveAll(list)
        val c = Child("aa","11",list)
        c.save()
---------------------------------------------------

find方法：
---------------------------------------------------
   val a = LitePal.findAll(Child::class.java)
---------------------------------------------------
执行find方法后报错信息如下:
---------------------------------------------------
org.litepal.exceptions.LitePalSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
        at org.litepal.crud.DataHandler.query(DataHandler.java:154)
        at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123)
        at org.litepal.Operator.findAll(Operator.java:1117)
        at org.litepal.Operator.findAll(Operator.java:1082)
        at org.litepal.LitePal.findAll(LitePal.kt:711)
        at com.example.xmsyapp.Repository.findCureDataByBodyIdAndCureMethod(Repository.kt:341)
        at com.example.xmsyapp.fragments.PatientEvaluateFragment$initView$2.onClick(PatientEvaluateFragment.kt:36)
---------------------------------------------------

以上是报错问题，后来经我测试发现，只要是在bean中带有list<XXX>的成员变量时就会产生上面的错误

**Comment by GitHubWison** [comment]
解决了，只要用class就行

**Comment by LJFDBXJ** [comment]
@guolindev  @sinyu890807 @GitHubWison  我 的问题#610  可以半我看看么大神

**Comment by LJFDBXJ** [comment]
@sinyu890807 我的没解决，可以帮帮我吗？我的问题是#610
