### ISSUE TITLE
【Bug反馈】Date数据的读取问题

### ISSUE THREAD

**Issue by TinyHai** [LitePalFramework/LitePal#565]
问题描述: 时间在1970年之前的Date数据存入数据库后, 读出来为null

经过阅读源码, 发现LitePal对Date数据的处理是将Date.getTime获取的时间戳存入数据库, 读取的时候将时间戳读出来通过Date(long)构造出Date, 但是, `在源码中读取Date数据时有如下一段代码
```Java
} else if (field.getType() == Date.class) {
    long date = (Long) value;
    if (date <= 0) {
        value = null;
    } else {
        value = new Date(date);
    }
}
```
分析源码可知, 当读出来的时间戳为负数时, 会直接把value赋值为null, 导致读取的Date值为null. 经过测试发现Date保存的时间在1970之前(TimeZone="GMT+0"时), 则getTIme获取的时间戳为负数, 所以LitePal的无法正确读取

**Comment by guolindev** [comment]
这个问题确实是LitePal的bug，我会在新版当中解决这个问题，到时候会更新这个issue。

**Comment by guolindev** [comment]
这个问题已经修复。

但是有一点需要注意的是，当实体类中的date字段没有赋值时，存储到数据库会以0的形式存储。在查询的时候由于取消了<=0的判断条件，这个时候date字段就会被默认赋值成1970年1月1号。

当然总体上逻辑比之前还是要合理的，只是这点变动可能会对一些程序的现有逻辑产生影响，所以可能需要注意一下。

**Comment by 025nju** [comment]
用的3.2.2，Date字段为null时保存，库里的值会存成long的最大值9223372036854775807。
