### ISSUE TITLE
切换设置语言异常

### ISSUE THREAD

**Issue by snpmyn** [LitePalFramework/LitePal#567]
android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.lalala.lalala/databases/LaLaLa.db' to 'zh_CN'.

**Comment by guolindev** [comment]
无具体操作过程描述，问题无法定位。

贴一个stackoverflow上的相关问题，希望有所帮助 https://stackoverflow.com/questions/19491675/failed-to-change-locale-for-db-data-data-my-easymedi-controller-databases-easy
