### ISSUE TITLE
来把native anr异常 

### ISSUE THREAD

**Issue by houyidg** [LitePalFramework/LitePal#568]
1 android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
--
2 android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:562)
3 android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
4 android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
5 android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:542)
6 org.litepal.crud.LitePalSupport.void saveThrows()(LitePalSupport.java:420)
7 org.litepal.crud.LitePalSupport.boolean save()(LitePalSupport.java:349)
8 com.dmall.dms.service.DMSService$5.void onResult(double,double,java.lang.String,com.amap.api.location.AMapLocation)(DMSService.java:388)
9 com.dmall.dms.utils.LocUtil.void onLocationChanged(com.amap.api.location.AMapLocation)(LocUtil.java:163)
10 com.loc.d.void a(int,java.lang.Object,long)(AmapLocationManager.java)
11 ##_parent_##16##_parent_##
12 ##_child_## void a(int)##_child_##
13 ##_child_## com.loc.d$a a(android.os.Looper)##_child_##
14 ##_child_## void a(int,android.os.Bundle)##_child_##
15 ##_child_## void a(com.amap.api.location.AMapLocation)##_child_##
16 ##_child_## void a(com.amap.api.location.AMapLocation,java.lang.Throwable,long)##_child_##
17 ##_child_## void a()##_child_##
18 ##_child_## com.autonavi.aps.amapapi.model.AMapLocationServer a(com.loc.co)##_child_##
19 ##_child_## void a(com.loc.co,com.autonavi.aps.amapapi.model.AMapLocationServer)##_child_##
20 ##_child_## void a(android.content.Intent,boolean)##_child_##
21 ##_child_## boolean a(com.loc.d,boolean)##_child_##
22 ##_child_## void a(com.loc.d,android.os.Bundle)##_child_##
23 ##_child_## void a(com.loc.d,android.os.Message)##_child_##
24 ##_child_## boolean a(boolean)##_child_##
25 ##_child_## void a(com.loc.d)##_child_##
26 ##_child_## void a(com.loc.d,com.amap.api.location.AMapLocationListener)##_child_##
27 ##_child_## void a(com.loc.d,int,long)##_child_##
28 com.loc.d.void a(int,java.lang.Object,long)(AmapLocationManager.java)
29 ##_parent_##16##_parent_##
30 ##_child_## void a(int)##_child_##
31 ##_child_## com.loc.d$a a(android.os.Looper)##_child_##
32 ##_child_## void a(int,android.os.Bundle)##_child_##
33 ##_child_## void a(com.amap.api.location.AMapLocation)##_child_##
34 ##_child_## void a(com.amap.api.location.AMapLocation,java.lang.Throwable,long)##_child_##
35 ##_child_## void a()##_child_##
36 ##_child_## com.autonavi.aps.amapapi.model.AMapLocationServer a(com.loc.co)##_child_##
37 ##_child_## void a(com.loc.co,com.autonavi.aps.amapapi.model.AMapLocationServer)##_child_##
38 ##_child_## void a(android.content.Intent,boolean)##_child_##
39 ##_child_## boolean a(com.loc.d,boolean)##_child_##
40 ##_child_## void a(com.loc.d,android.os.Bundle)##_child_##
41 ##_child_## void a(com.loc.d,android.os.Message)##_child_##
42 ##_child_## boolean a(boolean)##_child_##
43 ##_child_## void a(com.loc.d)##_child_##
44 ##_child_## void a(com.loc.d,com.amap.api.location.AMapLocationListener)##_child_##
45 ##_child_## void a(com.loc.d,int,long)##_child_##
46 com.loc.d.void a(int,java.lang.Object,long)(AmapLocationManager.java)
47 ##_parent_##16##_parent_##
48 ##_child_## void a(int)##_child_##
49 ##_child_## com.loc.d$a a(android.os.Looper)##_child_##
50 ##_child_## void a(int,android.os.Bundle)##_child_##
51 ##_child_## void a(com.amap.api.location.AMapLocation)##_child_##
52 ##_child_## void a(com.amap.api.location.AMapLocation,java.lang.Throwable,long)##_child_##
53 ##_child_## void a()##_child_##
54 ##_child_## com.autonavi.aps.amapapi.model.AMapLocationServer a(com.loc.co)##_child_##
55 ##_child_## void a(com.loc.co,com.autonavi.aps.amapapi.model.AMapLocationServer)##_child_##
56 ##_child_## void a(android.content.Intent,boolean)##_child_##
57 ##_child_## boolean a(com.loc.d,boolean)##_child_##
58 ##_child_## void a(com.loc.d,android.os.Bundle)##_child_##
59 ##_child_## void a(com.loc.d,android.os.Message)##_child_##
60 ##_child_## boolean a(boolean)##_child_##
61 ##_child_## void a(com.loc.d)##_child_##
62 ##_child_## void a(com.loc.d,com.amap.api.location.AMapLocationListener)##_child_##
63 ##_child_## void a(com.loc.d,int,long)##_child_##
64 com.loc.d$c.void handleMessage(android.os.Message)(AmapLocationManager.java)
65 android.os.Handler.dispatchMessage(Handler.java:111)
66 android.os.Looper.loop(Looper.java:207)
67 android.app.ActivityThread.main(ActivityThread.java:5845)
68 java.lang.reflect.Method.invoke(Native Method)
69 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
70 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)

**Comment by guolindev** [comment]
这种问题可能是手机底层数据库的问题，抛出层面也不是在LitePal这里，所以我也无法定位。
