### ISSUE TITLE
混淆之后的出现DatabaseGenerateException，找不到实体类

### ISSUE THREAD

**Issue by LymanHuang** [LitePalFramework/LitePal#57]
混淆之后出现异常：
Caused by: org.litepal.exceptions.DatabaseGenerateException: can not find a class named com.xxx.yyy.bean.MyMessage

不混淆可以正常运行，混淆之后出现异常，
甚至直接拿源代码过来也还是出现这个异常。
求大神解决！

**Comment by sinyu890807** [comment]
你不要混淆你的实体类，把com.xxx.yyy.bean这个包下的所有类都声明成不要混淆。

**Comment by LymanHuang** [comment]
先谢谢 sinyu890807 的回复
昨天晚上看源码看到了，第三方库使用反射获取litepal中配置的实体对象路径，混淆之后自然找不到。
解决方法：不混淆类，且不混淆其成员变量
-keep class com.xxx.yyy.bean.dbbean.** {*;}

**Comment by humanheima** [comment]
good
