### ISSUE TITLE
timeout 

### ISSUE THREAD

**Issue by houyidg** [LitePalFramework/LitePal#571]
1 android.content.res.AssetManager.list(Native Method)
--
2 org.litepal.util.BaseUtility.boolean isLitePalXMLExists()(BaseUtility.java:236)
3 org.litepal.parser.LitePalAttr.void loadLitePalXMLConfiguration()(LitePalAttr.java:98)
4 org.litepal.parser.LitePalAttr.org.litepal.parser.LitePalAttr getInstance()(LitePalAttr.java:90)
5 org.litepal.tablemanager.Connector.org.litepal.tablemanager.LitePalOpenHelper buildConnection()(Connector.java:92)
6 org.litepal.tablemanager.Connector.android.database.sqlite.SQLiteDatabase getWritableDatabase()(Connector.java:62)
7 org.litepal.tablemanager.Connector.android.database.sqlite.SQLiteDatabase getDatabase()(Connector.java:75)
8 org.litepal.Operator.java.lang.Object findFirst(java.lang.Class,boolean)(Operator.java:934)
9 org.litepal.Operator.java.lang.Object findFirst(java.lang.Class)(Operator.java:905)
10 org.litepal.LitePal.java.lang.Object findFirst(java.lang.Class)(LitePal.java:663)

**Comment by guolindev** [comment]
这是AssetManager底层API的错误，应该和LitePal无关，可能是手机问题。
