### ISSUE TITLE
LitePal 3.0.0 依赖下载后缺失文件严重

### ISSUE THREAD

**Issue by Gary0933** [LitePalFramework/LitePal#573]
缺失很多文件 用不了. 2.0.0就好用

**Comment by guolindev** [comment]
请确认3.0.0你使用的是
implementation 'org.litepal.android:java:3.0.0'
或
implementation 'org.litepal.android:kotlin:3.0.0'
而不是
implementation 'org.litepal.android:core:3.0.0'
