### ISSUE TITLE
LitePalParser.useSAXParser() 此处存在外部实体注入风险

### ISSUE THREAD

**Issue by 18702953620** [LitePalFramework/LitePal#575]
SAXParserFactory对象需设置参数防止外部实体注入

private void useSAXParser() {
        try {
            SAXParserFactory factory = SAXParserFactory.newInstance();
            XMLReader xmlReader = factory.newSAXParser().getXMLReader();
            LitePalContentHandler handler = new LitePalContentHandler();
            xmlReader.setContentHandler(handler);
            xmlReader.parse(new InputSource(this.getConfigInputStream()));
        } catch (NotFoundException var4) {
            throw new ParseConfigurationFileException("litepal.xml file is missing. Please ensure it under assets folder.");
        } catch (SAXException var5) {
            throw new ParseConfigurationFileException("can not parse the litepal.xml, check if it's in correct format");
        } catch (ParserConfigurationException var6) {
            throw new ParseConfigurationFileException("parse configuration is failed");
        } catch (IOException var7) {
            throw new ParseConfigurationFileException("IO exception happened");
        }
    }

**Comment by guolindev** [comment]
没太研究过这方面的知识，但是useSAXParser()方法在LitePal中是一个未使用的方法，只是一直没有删除而已。LitePal的解析XML一直使用的是usePullParse()方法。
