### ISSUE TITLE
org.litepal.exceptions.LitePalSupportException: Cursor window allocation of  kb failed.'__

### ISSUE THREAD

**Issue by CandiceYT** [LitePalFramework/LitePal#576]
b'10-12 12:48:05.788 E/AndroidRuntime(14662): org.litepal.exceptions.LitePalSupportException: Cursor window allocation of 2048 kb failed.'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat org.litepal.crud.DataHandler.query(DataHandler.java:154)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat org.litepal.FluentQuery.find(FluentQuery.java:234)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat org.litepal.FluentQuery.find(FluentQuery.java:195)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat com.fuxi.rsel.map.adapters.PoiSection.onBindItemViewHolder(PoiSection.java:241)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat com.fuxi.rsel.map.common.sectioned.Section.onBindContentViewHolder(Section.java:309)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat com.fuxi.rsel.map.common.sectioned.SectionedRecyclerViewAdapter.onBindViewHolder(SectionedRecyclerViewAdapter.java:320)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1077)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1815)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:3076)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.view.View.dispatchTouchEvent(View.java:11777)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SmartRefreshLayout.java:929)'
b'10-12 12:48:05.788 E/AndroidRuntime(14662): \tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)'

**Comment by jiangkaifang** [comment]
这个问题我也碰到了，不知道郭神什么时候修复

**Comment by guolindev** [comment]
这个问题我确实无能为力，Google了一大通没找到一个可行的解决方案。

从错误信息上看，是CursorWindow分配内存失败，但是正常情况下按理应该不会。

我找到了一篇文章，说这个错误基本是在一些老版本设备上由于设备内存不足而产生了，链接在这里：http://vjson.com/wordpress/cursor-window-allocation-of-2048-kb-failed.html
