### ISSUE TITLE
org.litepal.exceptions.LitePalSupportException: Row too big to fit into CursorWindow requiredPos=1, totalRows=2

### ISSUE THREAD

**Issue by Wrste** [LitePalFramework/LitePal#577]
主要发生在安卓p设备上面，当我获取所有数据时就会在安卓p设备出现这个

**Comment by Wrste** [comment]
参考：https://stackoverflow.com/questions/51959944/sqliteblobtoobigexception-row-too-big-to-fit-into-cursorwindow-requiredpos-0-t

**Comment by guolindev** [comment]
我从你给的链接上看，这好像是个SQLiteBlobTooBigException，也就是加载的二进制数据过大。实际上数据库中是不适合存储二进制数据的，更不适合存储过大的二进制数据因为很容易内存溢出。更好的做法是将二进制数据以文件的形式保存，然后在数据库中存储相应文件的链接。

我在之后的版本中会移除LitePal存储二进制数据的功能，因为它确实不适合做这件事。
