### ISSUE TITLE
使用Group作表名，创建数据库报错

### ISSUE THREAD

**Issue by xinlan26** [LitePalFramework/LitePal#579]
E/SQLiteLog: (1) near "group": syntax error
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 23345
    org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. create table group (id integer primary key autoincrement,createat integer, description text, name text, uid text, updateat integer)
应该是关键字冲突吧，是不是Group没作转义的原因

**Comment by guolindev** [comment]
Group是数据库中的关键字，不能在这个为表名。LitePal中是有一些转义机制，但是目前只能对字段转义，是不能对类名转义的，建议还是不要起这种容易造成冲突的命名。
