### ISSUE TITLE
LitePal.findAll报错

### ISSUE THREAD

**Issue by neabea** [LitePalFramework/LitePal#580]
可以确认表已经生成没问题，但是findall方法爆出异常了，为啥啊
org.litepal.exceptions.LitePalSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference

**Comment by TinyHai** [comment]
你好，今天我用LitePal访问数据库的时候也报了同样的错， 经过调试代码，发现了报错的原因。
不能说一定和你的问题是同一个，但就报错信息来看应该是类似的问题。

我跟踪源码发现，当LitePal尝试查询数据时， 如果Model类中的数据类型为集合类的接口定义时会抛异常。我用的是List接口声明的，其他集合接口类未测试，不过就代码分析也会抛异常，因为LitePal会根是构造器参数类型来创建对应示例并赋予初值或者默认值，因此尝试获取这些接口类的构造器，显然，接口是没有构造器的，返回null,后来才有的org.litepal.exceptions.LitePalSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference

目前简单的解决方法就是把所有集合类声明为其对应的子类型就行了

**Comment by guolindev** [comment]
拜托你们至少把实体类的定义也贴出来一下吧。。。

这个issue时间有点久了，不知道还有没有人关注，我先close掉，如果还需要继续解决的话再reopen吧。

**Comment by lucers** [comment]
data class CountryInfo(
    val id: Int,
    val iso2Code: String,
    val countryName: String,
    var firstLetter: String = "",
    var hasProvince: Boolean = true,
    var province: List<ProvinceInfo>?,
) : LitePalSupport(), Serializable

报错 java.util.List has no constructor. LitePal could not handle it
场景：国家和省份是分开的接口获取，我在本地没有表的时候，从接口获取国家数据，选择国家后，再获取对应国家的省份数据保存到对应国家下，在没有省份数据的情况下，FindAll 直接报错

**Comment by lucers** [comment]
根据文档改成了
data class CountryInfo(
    val id: Int,
    val iso2Code: String,
    val countryName: String,
    var firstLetter: String = "",
    var hasProvince: Boolean = true,
) : LitePalSupport(), Serializable {

    var province: List<ProvinceInfo> = listOf()
        set(value) {
            if (value.isEmpty().not()) {
                LitePal.saveAll(value)
            }
            field = value
        }
        get() {
            val linkId = this.javaClass.simpleName.toLowerCase(Locale.ENGLISH)
            return LitePal.where("${linkId}_id", id.toString()).find(ProvinceInfo::class.java)
        }
}
