### ISSUE TITLE
在Android8.1-DataSupport.saveAll(list);报错

### ISSUE THREAD

**Issue by jachary** [LitePalFramework/LitePal#584]
### **我用的是litepal-1.4.1.jar 在源码环境下Android.mk编译apk. 在安卓7.1系统正常使用，在安卓8.1系统调用DataSupport.saveAll(list)报错：**

>  **AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.shutdown/com.example.shutdown.MainActivity}: org.litepal.exceptions.DatabaseGenerateException: can not find a class named org.litepal.model.Table_Schema
>  AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
>  AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
>  AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
>  AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
>  AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
>  AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
>  AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6494)
>  AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
>  AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>  AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:808)
>  AndroidRuntime: Caused by: org.litepal.exceptions.DatabaseGenerateException: can not find a class named org.litepal.model.Table_Schema
>  AndroidRuntime:        at org.litepal.LitePalBase.getSupportedFields(LitePalBase.java:196)
>  AndroidRuntime:        at org.litepal.LitePalBase.getTableModel(LitePalBase.java:123)
>  AndroidRuntime:        at org.litepal.tablemanager.Generator.getAllTableModels(Generator.java:72)
>  AndroidRuntime:        at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:45)
>  AndroidRuntime:        at org.litepal.tablemanager.Generator.create(Generator.java:167)
>  AndroidRuntime:        at org.litepal.tablemanager.Generator.create(Generator.java:205)
>  AndroidRuntime:        at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)
>  AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:333)
>  AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
>  AndroidRuntime:        at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:58)
>  AndroidRuntime:        at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)
>  AndroidRuntime:        at org.litepal.crud.DataSupport.saveAll(DataSupport.java:881)
>  AndroidRuntime:        at com.example.shutdown.MainActivity.initView(MainActivity.java:120)
>  AndroidRuntime:        at com.example.shutdown.MainActivity.onCreate(MainActivity.java:109)
>  AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7036)
>  AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7027)
>  AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
>  AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)**

**Comment by guolindev** [comment]
Table_Schema是LitePal库中内置的一个类，不可能不存在。

请检查一下是不是因为你的项目开启了混淆之类的功能导致类名改变了。

另外你自己也可以尝试通过反射来加载一下这个类，检查一下这个类到底存不存在。
