### ISSUE TITLE
字段名为“end”的时候存储的数据字段出错

### ISSUE THREAD

**Issue by Black-Knights** [LitePalFramework/LitePal#588]
字段名为“end”的时候存储的数据字段不为end，变成了“end_......”具体是变成什么忘了。改成endStr存储的字段就一样了。

**Comment by guolindev** [comment]
因为end是SQL语句中的关键字，实体类里定义了关键字，如果不进行转义的话就会崩溃。

具体可以参考这篇文章：https://mp.weixin.qq.com/s/C7nbJXOS9lYPgOda-8Pw0A
