### ISSUE TITLE
关于多表关联的问题

### ISSUE THREAD

**Issue by DaveBoy** [LitePalFramework/LitePal#589]
### 问题描述：
歌曲：名字，所属专辑
专辑：名字
以此模型进行存储，结果数据库里面只存了专辑与最后一条歌曲的关联关系。
从以下代码日志截图和数据库可视化截图可以看到，**album表多了一个song_id字段，但是只关联了我最后保存的song的id，前两条数据的关联关系被覆盖了**。
### 代码：
![image](https://user-images.githubusercontent.com/16101638/70960320-a6efe680-20b9-11ea-96e4-93ba5fc0a641.png)
![image](https://user-images.githubusercontent.com/16101638/70960425-f2a29000-20b9-11ea-93d6-bf88f76fa784.png)
![image](https://user-images.githubusercontent.com/16101638/70960437-f9310780-20b9-11ea-8eb4-b0cde764ef58.png)

### 数据库数据：
![image](https://user-images.githubusercontent.com/16101638/70960373-d6065800-20b9-11ea-9b6a-b5f6d1ef27b8.png)
![image](https://user-images.githubusercontent.com/16101638/70960399-e3bbdd80-20b9-11ea-9146-5c7e8787e7d7.png)

**Comment by guolindev** [comment]
你建立的这是一对一的关联，当然前两条数据的关联关系都会被覆盖了。

Album和Song应该建立的多对一的关联关系，具体教程可以参考这篇文章： https://blog.csdn.net/guolin_blog/article/details/39207945
