### ISSUE TITLE
litepal.xml is missing!?

### ISSUE THREAD

**Issue by Zane96** [LitePalFramework/LitePal#59]
Hello!
I use the litepal first time. and I meet with a problem
![2016-02-18 2 04 50](https://cloud.githubusercontent.com/assets/12124524/13135170/404394f4-d649-11e5-934c-b1fe197d98a4.png)
![2016-02-18 2 04 59](https://cloud.githubusercontent.com/assets/12124524/13135201/76a43738-d649-11e5-95db-67558c0eae78.png)
![2016-02-18 2 05 21](https://cloud.githubusercontent.com/assets/12124524/13135203/7cb240f2-d649-11e5-9e88-7f88ffdaad3e.png)
![2016-02-18 2 05 32](https://cloud.githubusercontent.com/assets/12124524/13135204/7ef0f6d8-d649-11e5-8ec2-33814bc5a8a3.png)

can u resolve my problem? Thanks!

**Comment by sinyu890807** [comment]
I guess you didn't append **.xml** to litepal configuration file. Internal it will find the file which named **litepal.xml**, but it seems you named it as just **litepal** without suffix.

**Comment by Zane96** [comment]
Thank u very much!But I have meet anthor problem..
If I query date by order("name asc").find(xxxx), and name is chinese.I will get wrong date which not order by name asc.

**Comment by sinyu890807** [comment]
This is not a LitePal bug. SQLite won't handle chinese order either.
