### ISSUE TITLE
使用LitePal.where查询数据得到的结果列表不为空，但数据项为空

### ISSUE THREAD

**Issue by laoxiao79** [LitePalFramework/LitePal#590]
如：List <MailSyncList> mailSyncLists = LitePal.where("OAId = ? and FolderId = ?", RequestMailData.OaName, mailQueryData.folderid).order("DateTimeReceived desc").offset(offset).limit(iPageSize).find(MailSyncList.class);
mailSyncLists打到的log 为：

**2019-12-19 20:38:53.351 26662-2343/? I/AndServerSample: ----readMailDataFromFolderid----mailSyncLists=[{UserId='null', FolderType=0, FolderId='null', FolderName='null', IsStar=false, IsDraft=false, IsRms=false, IsToMe=false, IsCcMe=false, Importance=0, FromAddress='null', FromName='null', DisplayTo='null', Subject='null', HasAttachments=false, PreviewText='null', DateTimeSent=0, Size=0, BodyText='null', Meeting='null', LastVerb=0, LastVerbTime=0, ChangeType=0, ItemId='null', DateTimeReceived=0, IsRead=false, OAId='null', isSave=0}, {UserId='null', FolderType=0, FolderId='null', FolderName='null', IsStar=false, IsDraft=false, IsRms=false, IsToMe=false, IsCcMe=false, Importance=0, FromAddress='null', FromName='null', DisplayTo='null', Subject='null', HasAttachments=false, PreviewText='null', DateTimeSent=0, Size=0, BodyText='null', Meeting='null', LastVerb=0, LastVerbTime=0, ChangeType=0, ItemId='null', DateTimeReceived=0, IsRead=false, OAId='null', isSave=0}, {UserId='null', FolderType=0, FolderId='null', FolderName='null', IsStar=false, IsDraft=false, IsRms=false, IsToMe=false, IsCcMe=false, Importance=0, FromAddress='null', FromName='null', DisplayTo='null', Subject='null', HasAttachments=false, PreviewText='null', DateTimeSent=0, Size=0, BodyText='null', Meeting='null', LastVerb=0, LastVerbTime=0, ChangeType=0, ItemId='null', DateTimeReceived=0, IsRead=false, OAId='null', isSave=0}, {UserId='null', FolderType=0, FolderId='null', FolderName='null', IsStar=false, IsDraft=false, IsRms=false, IsToMe=false, IsCcMe=false, Importance=0, FromAddress='null', FromName='null', DisplayTo='null', Subject='null', HasAttachments=false, PreviewText='null', DateTimeSent=0, Size=0, BodyText='null', Meeting='null', LastVerb=0, LastVerbTime=0, ChangeType=0, ItemId='null', DateTimeReceived=0, IsRead=false, OAId='null', isSave=0}, {UserId='null', FolderType=0, FolderId='null', FolderName='null', IsStar=false, IsDraft=false, IsRms=false, IsToMe=false, IsCcMe=false, Importance=0, FromAddress='null', FromName='null', DisplayTo='null', Subject='null', HasAttachments=false, PreviewText='null', DateTimeSent=0, Size=0, BodyText='null', Meeting='null', LastVerb=0, LastVerbTime=0, ChangeType=0, ItemId='null', DateTimeReceived=0, IsRead=false, OAId='null', isSave=0}, {UserId='null', FolderType=0, FolderId='null', FolderName='null', IsStar=false, IsDraft=false, IsRms=false, IsToMe=false, IsCcMe=false, Importance=0, FromAddress='null', FromName='null', DisplayTo='null', Subject='null', HasAttachments=false, PreviewText='null', DateTimeSent=0, Size=0, BodyText='null', Meeting='null', LastVerb=0, LastVerbTime=0, ChangeType=0, ItemId='null', DateTimeReceived=0, IsRead=false, OAId='null', isSave=0}]
*
而数据库中通过手动查询可以查到数据
![image](https://user-images.githubusercontent.com/9912188/71175928-a450e500-22a3-11ea-8cd3-c1a9ff75e1d9.png)

**Comment by laoxiao79** [comment]
这是什么情况，项目着急请帮忙看下，多谢🙏

**Comment by guolindev** [comment]
仅从你给的日志和截图上来看，确实无法定位出问题原因，日志上的结果和图中的结果对应不上。

为了防止是你操作失误引起的问题，能不能尝试不用LitePal，使用原生的数据库查询方式将数据查询出来，看看结果是和LitePal一样，还是可以查询出数据？

**Comment by guolindev** [comment]
由于问题已经过于久远，或许你自己已经解决掉了，我这里先将这个问题关闭。如果你后续还在继续关注这个问题的话，请再重新打开。
