### ISSUE TITLE
创建多个数据库

### ISSUE THREAD

**Issue by liwei49699** [LitePalFramework/LitePal#591]
郭神 因为app需求 需要创建多个本地数据库 litepal支持吗

**Comment by SJLBenjamin** [comment]
litepal有动态建库的api,但是不知道为什么我在做删除库的时候会删除失败,
动态建库的链接如下
https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&amp;mid=2650237709&amp;idx=1&amp;sn=1e9ee99617b2cb8f00af9b35eb83a637&amp;chksm=88639a62bf14137450f5c98ec245362a0fef36e1bae1eaf12081d52d8b0e60a2c299e1699593#rd

**Comment by liwei49699** [comment]
好的 谢谢了
