### ISSUE TITLE
华为 LIO AN00在查询表数据的时候报no such column

### ISSUE THREAD

**Issue by lishiyu1810** [LitePalFramework/LitePal#593]
其他的手机型号没问题，第一次安装APK ，也不是数据库没有升级的问题
List<ChatMsgBean> list = LitePal.where("tagId = ? or tagId = ?", mFromId + mToId, mToId + mFromId).find(ChatMsgBean.class);
litepal.xml里面也有定义
ChatMsgBean类里有有这个字段
请问是出了什么问题？

1 java.lang.RuntimeException:Unable to start activity ComponentInfo{com.huabang.social/com.huabang.social.msg.ChatActivity}: org.litepal.exceptions.LitePalSupportException: no such column: tagId (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT * FROM chatmsgbean WHERE tagId = ? or tagId = ?, (OS error - 2:No such file or directory)
--
2 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3760)
3 ......
4 Caused by:
5 android.database.sqlite.SQLiteException:no such column: tagId (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT * FROM chatmsgbean WHERE tagId = ? or tagId = ?, (OS error - 2:No such file or directory)
6 android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
7 android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1032)
8 android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:639)
9 android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:610)
10 android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:66)
11 android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
12 android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
13 android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1483)
14 android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1325)
15 android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1196)
16 android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1402)
17 org.litepal.crud.DataHandler.query(DataHandler.java:133)
18 org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
19 org.litepal.FluentQuery.find(FluentQuery.java:234)
20 org.litepal.FluentQuery.find(FluentQuery.java:195)
21 com.huabang.social.msg.ChatActivity.setHistoryMsg(ChatActivity.java:194)
22 com.huabang.social.msg.ChatActivity.initMsgList(ChatActivity.java:172)
23 com.huabang.social.msg.ChatActivity.initView(ChatActivity.java:132)
24 com.huabang.social.msg.ChatActivity.onCreate(Native Method)
25 android.app.Activity.performCreate(Activity.java:8066)
26 android.app.Activity.performCreate(Activity.java:8054)
27 android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
28 android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
29 android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
30 android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
31 android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
32 android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
33 android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
34 android.os.Handler.dispatchMessage(Handler.java:107)
35 android.os.Looper.loop(Looper.java:213)
36 android.app.ActivityThread.main(ActivityThread.java:8147)
37 java.lang.reflect.Method.invoke(Native Method)
38 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
39 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by guolindev** [comment]
我这边没有华为手机，可能没办法复现你说的问题，可以在你的华为手机上查询一下数据库表，看一看具体有没有tagId这个列吗？

**Comment by guolindev** [comment]
由于问题久远且没有回复，我暂时先将这个问题关闭了，如果后续还有人继续关注这个问题，请再重新打开。
