### ISSUE TITLE
数据库升级，旧的数据表中的数据某些字段会被清空

### ISSUE THREAD

**Issue by veicn** [LitePalFramework/LitePal#599]
数据库升级，增加了 version 版本号，新增了一张表，旧的数据表中的数据，某些字段的值会被清空，我观察被清空的字段在实体中类的类型是 long型和int型

**Comment by guolindev** [comment]
能描述的再详细些吗？ 比如你的实体类是什么样子的，里面有哪些字段，升级的时候哪个字段的值被清空了？

**Comment by guolindev** [comment]
因为你这里没有提供具体的实体类定义，所以我很难检查问题所在。

不过我刚才处理了另外一个数据被清空的issue，因为他提供的描述信息非常完整，所以很快就定位出来了原因。或许你们可能是同一个问题，可以参考一下。

https://github.com/LitePalFramework/LitePal/issues/532
