### ISSUE TITLE
problem of DataSupport.deleteAll()

### ISSUE THREAD

**Issue by mapsh** [LitePalFramework/LitePal#6]
it doesn't delete associated tables of current model's table.

**Comment by sinyu890807** [comment]
Fixed in 1.2.0

**Comment by jackL-e-e** [comment]
Hi,i met a problem using the deleteAll() method.
My requirement is delete top 20 records in the table, but the LitePal 's default primary key  `id`  is not updated,i.e. if i deleted `record 0,1,2,` then the first record in the table is `record 4`,So i can not delete the top 20 records using 

    for(int i=0;i<20;i++){ delete(MyBean,class,i);}
Hope for your reply : ),Thx.

**Comment by sinyu890807** [comment]
I guess in this situation you need two steps to finish the work. First you need to find out the top 20 records with `DataSupport.select("id").limit(20)`, then delete these records with ids.

**Comment by jackL-e-e** [comment]
How can i get the __ids__ with  `DataSupport.select("id").limit(20)`? This expression just returns the List of my beanObject.

**Comment by sinyu890807** [comment]
Here's one internal mechanism. Sorry I didn't mentioned in the doc. If your bean object named Album, declare your bean object with an id field, like:
```java
public class Album extends DataSupport {
    private int id;
    ...
    public int getId() {
        return id;
    }
}
```
Then use the codes above to query the top 20 records:
```java
List<Album> albums = DataSupport.select("id").limit(20).find(Album.class);
```
OK. Now you can get all the ids by a loop with `album.getId()` method.
But actually there's one easier way to delete these records:
```java
for (Album album : albums) {
    album.delete();
}
```
I am considering to make this happen much easier in the next release.

**Comment by jackL-e-e** [comment]
Many thanks ,that's the very thing i need to get the work done.
>List<Album> albums = DataSupport.select("id").limit(20).find(Album.class);

: )
