### ISSUE TITLE
链式查询支持吗？比如group,这个有吗？

### ISSUE THREAD

**Issue by 1510766316** [LitePalFramework/LitePal#601]
现在需要group分组查询，不知道怎么办？库什么能实现该功能？

**Comment by creativityingenuity** [comment]
兄弟 你找到了吗 我也遇到了

**Comment by guolindev** [comment]
要用group语句的话，调用LitePal.findBySQL，然后写原生sql语句就行了。LitePal的链式查询里不能用group语言，因为加了group之后生成的列在你定义的实体类当中不存在。而LitePal.findBySQL返回的并不是实体类，是cursor，你再用相应的get方法去获取值就行了。
