### ISSUE TITLE
saveAll方法不能将成员属性列表保存。findAll 不能获取成员属性列表

### ISSUE THREAD

**Issue by longqiankun** [LitePalFramework/LitePal#609]
List<Singer> singers=new ArrayList<>();
				for (int i=0;i<5;i++) {
					Singer singer = new Singer();
					singer.setName(mSingerNameEdit.getText().toString());
					singer.setAge(Integer.parseInt(mSingerAgeEdit.getText().toString()));
					singer.setMale(Boolean.parseBoolean(mSingerGenderEdit.getText().toString()));

					List<Album> albums=new ArrayList<>();
					for (int j=0;j<2;j++) {
						Album album=new Album();
						album.setName(mSingerNameEdit.getText().toString()+"i"+j);
						albums.add(album);
					}
					singer.setAlbums(albums);
					singers.add(singer);

					refreshListView(singer.getId(), singer.getName(), singer.getAge(),
							singer.isMale() ? 1 : 0);
				}
				LitePal.saveAll(singers);

**Comment by guolindev** [comment]
LitePal.saveAll(singers)这里只会存储所有的Singers，Albums是不会一起保存的，因为LitePal中没有级联存储的功能。如果这就是你指的不能将成员属性列表保存，其实你只要将每一个new出来的Album也save一下就行了。
