### ISSUE TITLE
为什么两个对象，即使设置相同id，调用save方法后会生成2条数据？

### ISSUE THREAD

**Issue by zhouzhuo810** [LitePalFramework/LitePal#616]
```java
AccountType type1 = new AccountType();
type1.setId(type.getId());
//type1.setXxx...
type1.save();
```

```java
public class AccountType extends LitePalSupport {
    private long id;
   // getter and setter
}
```

**Comment by guolindev** [comment]
因为你设的id LitePal是不认的，id应该由对象存储之后自动生成，而不是手动赋值。

不过如果你有这样的特殊需求，可以调用assignBaseObjId()方法，LitePal内部是根据这个方法赋值的字段来判断两个对象是否相等的。

**Comment by zhouzhuo810** [comment]
> 因为你设的id LitePal是不认的，id应该由对象存储之后自动生成，而不是手动赋值。
> 
> 不过如果你有这样的特殊需求，可以调用assignBaseObjId()方法，LitePal内部是根据这个方法赋值的字段来判断两个对象是否相等的。

那是否可以提供一个baseObjId的getter方法呢，我要导出和还原用。
