### ISSUE TITLE
加密数据库功能，不影响where语句查询的那种

### ISSUE THREAD

**Issue by 2372281891** [LitePalFramework/LitePal#617]
不论对哪一列进行加密，都不影响where语句查询

**Comment by guolindev** [comment]
因为加密功能本来就是用的比较少的一个功能，对加密数据进行where查询这个用的就更少了，如果为了这个比较少用的场景，在每次查询的时候都遍历一遍当前类里面的所有字段是否有@Encrypt注解，这无疑会为大部分并不需要加密的查询场景增加负担，效率会变低。

哪些字段是加密的使用者更加清楚，你在进行where查询的时候先调用LitePal提供的加密算法对数据进行加密，然后用加密后的数据再进行where查询，这可能是更加高效的做法。

**Comment by 2372281891** [comment]
感谢郭神。
“你在进行where查询的时候先调用LitePal提供的加密算法对数据进行加密”


这句话中的“先利用加密算法对数据进行加密”，指的是将我要查询的key先进行加密吗，具体的方法是啥，我找了一圈没找到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"郭霖"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 中午11:52
收件人:&nbsp;"LitePalFramework/LitePal"<LitePal@noreply.github.com&gt;;
抄送:&nbsp;"2372281891"<2372281891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LitePalFramework/LitePal] 加密数据库功能，不影响where语句查询的那种 (#617)





 
因为加密功能本来就是用的比较少的一个功能，对加密数据进行where查询这个用的就更少了，如果为了这个比较少用的场景，在每次查询的时候都遍历一遍当前类里面的所有字段是否有@Encrypt注解，这无疑会为大部分并不需要加密的查询场景增加负担，效率会变低。
 
哪些字段是加密的使用者更加清楚，你在进行where查询的时候先调用LitePal提供的加密算法对数据进行加密，然后用加密后的数据再进行where查询，这可能是更加高效的做法。
