### ISSUE TITLE
查询和保存能不能不要加synchronized关键词

### ISSUE THREAD

**Issue by Moster1h** [LitePalFramework/LitePal#619]
在一个线程中执行查询和保存操作的时候，线程内部可能有多个查询或保存操作，这样就有了很多synchronized，去掉这个synchronized让我们自己控制。

**Comment by Moster1h** [comment]
我自己Fork一个

**Comment by guolindev** [comment]
不加的话容易引起databaseislocked的异常，这样之前close的很多issue就得被重新打开了，或许你自己那边能做好控制，那么你自己fork一个可能是更好的选择。
