### ISSUE TITLE
boolean 更新为 true 失败

### ISSUE THREAD

**Issue by jiuxin** [LitePalFramework/LitePal#62]
数据库中boolean 类型的字段，使用 setToDefault 更新为 false 后，再无法更新为 true。

**Comment by sinyu890807** [comment]
有具体的代码吗，贴出来看一下

**Comment by KeithLanding** [comment]
相同问题，我的是这样的，实际测试发现：将整型的字段的值 从0 update 到1之后，将1再改成0就不成功。
