### ISSUE TITLE
assignBaseObjId的参数应该传long类型，现在传的int类型

### ISSUE THREAD

**Issue by zhouzhuo810** [LitePalFramework/LitePal#621]
```java
    /**
     * Assigns value to baseObjId. This will override the original value. <b>Never call this method
     * unless you know exactly what you are doing.</b>
     * @param baseObjId
     */
    public void assignBaseObjId(int baseObjId) {
        this.baseObjId = baseObjId;
    }
```

@guolindev 希望郭神改改，需要用到这个功能。

**Comment by guolindev** [comment]
奇怪，我还真一直没留意到这个细节，等我check一下代码。

**Comment by zhouzhuo810** [comment]
> 奇怪，我还真一直没留意到这个细节，等我check一下代码。

哈哈，我也觉得奇怪，可能是之前baseObjId是int，改成long之后忘了改这个吧

**Comment by guolindev** [comment]
原来是我漏掉了，baseObjId 是long类型的，只是这个assignBaseObjId功能不常用，没注意到它接收的参数竟然是int类型的，下个版本中会改掉，多谢指出。

已在源码中修正，会随下个版本发布的时候改掉这个bug。

https://github.com/LitePalFramework/LitePal/commit/3f1e35c9c912d3fc4e5e909e99efb9e5658e0f51
