### ISSUE TITLE
查询数据库报错,求解决

### ISSUE THREAD

**Issue by jiangzhengyan** [LitePalFramework/LitePal#622]
错误日志 : Row too big to fit into CursorWindow requiredPos=0, totalRows=55

**Comment by ccc920123** [comment]
我也遇见了这问题，我存入一张base64 的图片 报了这个错，不过查看google文档说底层用CursorWindow 能解决不知是不是

**Comment by guolindev** [comment]
你查询的数据量过大，超出CursorWindows能承受的范围了。从信息上来看，totalsRows只有55行，理论上数据量并不大，不太可能会超出CursorWindows的承受范围，除非你和楼上这位朋友一样，把图片的base64往数据库里存，这就真是自己给自己找麻烦了。

这个问题的解法方法就是减少单次查询的数据量，不要让系统超出自己的负荷，LitePal在这一方面做不了什么。
