### ISSUE TITLE
希望添加分组查询的api 

### ISSUE THREAD

**Issue by keaitao0321** [LitePalFramework/LitePal#623]
如 SELECT * from (SELECT * FROM signfacemodel ORDER BY signtime) a GROUP BY a.userid;
很多时候查询的时候希望针对重复字段去重查询

**Comment by guolindev** [comment]
分组查询功能现在就可以使用，将你的上述语句放到 LitePal.findBySQL 方法中就可以了，返回的是一个Cursor对象，然后从Cursor中取出你要的字段即可。
