### ISSUE TITLE
org.litepal.exceptions.LitePalSupportException: Cursor window allocation of 2048 kb failed. # Open Cursors=895 (# cursors opened by this proc=895)

### ISSUE THREAD

**Issue by wwddd66** [LitePalFramework/LitePal#630]
` List<User> users = LitePal.findAll(User.class);`
我在执行这条语句的时候报错：
org.litepal.exceptions.LitePalSupportException: Cursor window allocation of 2048 kb failed. # Open Cursors=895 (# cursors opened by this proc=895)

User表是这样的：
`    private int id;`
`    private String username;//用户名，unique`
`    private String nickname;//昵称，默认为用户名`
`    private String password;//密码，NOT NULL`
`    private String email;//邮箱，NOT NULL`
`    private List<Post> postList = new ArrayList<>();//一对多`
`    private List<User> userList = new ArrayList<>();//自身多对多`

百度说是要 `cursor.close();` ，但是Litepal没用直接使用Cursor啊，所以没有解决问题。
这应该怎么办呢？

**Comment by guolindev** [comment]
一般出现这种错误的时候，都是你的查询数据量过大了，超出了CursorWindow允许的最大空间，从上面的提示看，也就是2M。

因为你调用的是findAll方法，会一次性把User表中的所有数据全部读取出来，所以会不会出现上面的错误，要看你的User表中有多少数据。

建议可以用limit方法和offset方法进行分页加载，控制单次查询的数据量，比如：

`LitePal.limit(100).offset(10).find(User.class)`

其中，limit方法用于限制单次加载多少条数据，offset方法用于对查询的数据进行偏移，从而达到分页效果。

**Comment by guolindev** [comment]
https://github.com/LitePalFramework/LitePal/issues/576

**Comment by wwddd66** [comment]
谢谢郭神，我其实是想给用户添加好友的，就是User表自身的多对多，然后就在User表内建了一个List<User> userList属性，可能这样不符合要求才会出现那样的错误。最后我的解决办法是：新建了一个关系表来存储用户id和好友id，去掉了原来的List<User> userList属性

**Comment by guolindev** [comment]
好的，那这个问题我就先关闭了。
