### ISSUE TITLE
如何嵌套查询

### ISSUE THREAD

**Issue by thsai** [LitePalFramework/LitePal#634]
比如类似这样的查询语句如果用litepal怎么写？：
select * from (select * from dbname ORDER by id DESC   LIMIT 100) where id>10

**Comment by guolindev** [comment]
这种因为你要查询的表在实体类当中并不存在，而是根据另一条查询结果映射出来的，所以通用的查询方法肯定是没办法的。这个时候你只能使用LitePal.findBySQL，用原生SQL语句查询。

不过我后面也考虑引入像Room那样的语法机制，直接将SQL语句映射到指定对象上面，需要过段时间，暂时还没调研这方面的技术。
