### ISSUE TITLE
能不能把数据库存储到sd卡

### ISSUE THREAD

**Issue by wnygqg** [LitePalFramework/LitePal#65]

**Comment by sinyu890807** [comment]
1.3.2版本开始支持把数据库存到sd卡上了，具体可以参考一下这篇文章 http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=502752443&idx=1&sn=8bddcf70ac3d40f67fd32e81a87e2bcf#rd

**Comment by jiangyanlily** [comment]
有没有API能支持，我们遇到一个问题，用户的内部存储空间满了，但是sd卡是有空间的，这个时候我们完全可以给他建在sd卡上，总比不能提供服务强
