### ISSUE TITLE
The update function

### ISSUE THREAD

**Issue by Alvie0330** [LitePalFramework/LitePal#66]
Hi friend,

This framework is really very amazing! It helped me a lot. However, is it possible that the update function can allow the DataSupport Object to update itself by just calling the .update() method? It would be hard for me to look for each of these objects' ids from the database in order to just do .update(id). Thanks and look forward for the new version.

**Comment by guolindev** [comment]
Actually you don't need to call update() method, you can just call save() under you situation. See docs for more details.
