### ISSUE TITLE
关于动态创建数据库，数据库表名

### ISSUE THREAD

**Issue by 1181631922** [LitePalFramework/LitePal#69]
1.3.1是否可以动态创建数据库并且设置表名？

**Comment by sinyu890807** [comment]
还不能，这个功能不出意外的话会在1.4.0加入

**Comment by 1181631922** [comment]
恩，谢谢回答

**Comment by guolindev** [comment]
现在已支持动态创建数据库，升级到1.4.0版本即可。

**Comment by sxyaxy** [comment]
> 1.3.1是否可以动态创建数据库并且设置表名？

解决了吗？动态建表，还是通过xml配置？还是可以手动根据类来建表？
