### ISSUE TITLE
当我用order作为变量的时候会报异常

### ISSUE THREAD

**Issue by wblyuyang** [LitePalFramework/LitePal#70]
![image](https://cloud.githubusercontent.com/assets/9973440/14660964/72e99a66-06dc-11e6-81a3-1dd6d36a6e25.png)

全局异常：Unable to start activity ComponentInfo{com....activity.splash.SplashActivity}: org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. alter table Test add column order text

当把order改为其他值后则可以正常建表。
order是LitePal内部使用的变量？还是说是一个bug？

**Comment by sinyu890807** [comment]
order是SQL的关键字呀，你不能以这个名字命名字段的，所有的SQL关键字都不能使用
