### ISSUE TITLE
model.update(id)可是id无从得知。

### ISSUE THREAD

**Issue by hackill** [LitePalFramework/LitePal#72]
从你的demo和github上的介绍说明来看 更新遇到了麻烦，litepal推荐使用 model.update(id)进行更新 ，但是id对我来说拿不到。总不能先去查询一遍然后再得出id吧？ 这样的查询效率和执行效率不好

**Comment by sinyu890807** [comment]
update(id)方法本来就是你知道id的情况下去更新这个id对应记录的内容的，你没得不到id的话调别的接口就是了
