### ISSUE TITLE
deleteAll save不上

### ISSUE THREAD

**Issue by hanguodong** [LitePalFramework/LitePal#73]
有一个house model，我在存houseId 为Xxx的house时先delete all了 已经存在的house id为Xxx的数据，
然后执行save，为什么没有存上呢？

**Comment by sinyu890807** [comment]
因为delete all是直接从数据库里面把数据删掉的，删除状态没有通知到对象上，所以对象那边认为你的model还是save过的，就存不进去了。这种情况你只需要调一下DataSupport.markAsDeleted方法来通知一下对象数据已经被删掉了，就可以存进去了。

**Comment by hanguodong** [comment]
house里的houseid 服务器做了加密会超过64位我加了一个string字段house_id_str，下面是我的代码，执行过下面的代码后我在其他页find 有概率会find不到 
int deleteids = DataSupport.deleteAll(House.class, "house_id_str = ?", String.valueOf(item.getHouse_id()));
            YiYiLogger.d("fangyuan","is save = "+item.isSaved());
            YiYiLogger.d("fangyuan","delete ids = "+deleteids);
            boolean isSave = item.save();
            YiYiLogger.d("fangyuan","is save = "+isSave);

**Comment by sinyu890807** [comment]
不明白你的逻辑，你是要把item对象的数据删掉之后再把item对象存储一遍吗？如果是的话，调用一下markAsDeleted方法把item对象的存储状态清一下，然后再save应该就可以了
