### ISSUE TITLE
性能无法忍受

### ISSUE THREAD

**Issue by meanliang** [LitePalFramework/LitePal#74]
查询速度是原生SQL的1/20

**Comment by sinyu890807** [comment]
现在出了一个snapshot版本，性能提升了很多，你可以试试把gradle里面的版本换成1.3.2-snapshot

**Comment by gengjiawen** [comment]
Readme后面能否有一个benchmark表格之类的，展示下和原生的性能差异，每个版本出来后也好知道性能。
