### ISSUE TITLE
在app使用过程中，删除缓存，表删除了，但是仍可获取得数据，

### ISSUE THREAD

**Issue by mohuancaizi** [LitePalFramework/LitePal#75]
表已经删除了， 但是 通过以下方法仍可获取到值 仍然可以获取到mId 值  这让我很头疼
  UserDataTb userDataTb = DataSupport.findFirst(UserDataTb.class);
        if(userDataTb!=null&&userDataTb.getmId()>0){
            LogCatUtil.d("表中已有ID，不再重复请求！！！");
            return;
        }

**Comment by sinyu890807** [comment]
这不可能吧，如果表已经删除了，findFirst的结果只会是null。

**Comment by mohuancaizi** [comment]
原因是 manifest Apllication 下添加了这个       android:persistent="true"  把这个去掉就可以了
