### ISSUE TITLE
Many to many doubt

### ISSUE THREAD

**Issue by Vareta** [LitePalFramework/LitePal#76]
I finally managed to make a many to many association thanks to [this guide](http://seniorzhai.github.io/2015/02/02/LitePal%E7%9A%84%E4%BD%BF%E7%94%A8/). But now i don't know how to access that data, The models code it's like this:
```
public class News {
	...
	private List<Category> categoryList = new ArrayList<Category>();
	...
}
public class Category {
	...
	private List<News> newsList = new ArrayList<News>();
	...
}
```
I tried to access to categoryList or newsList but they have no items and when i check the association table, this has been created and has the data associated. So i really don't know what to do

Thanks in advance

**Comment by sinyu890807** [comment]
You need to use eager query to get the data of associated table, or you have to get them by yourself which extra query operation.

**Comment by Vareta** [comment]
with the parameter isEager worked well.
Thank you very much!
