### ISSUE TITLE
删除数据后，马上插入失败

### ISSUE THREAD

**Issue by mondongxr** [LitePalFramework/LitePal#77]
1.删除数据
`categoryid = "312317329132";`
`DataSupport.deleteAll(News.class, "categoryid = ?", categoryid);`
2.插入数据
`DataSupport.saveAll(list);//其中list是News对象的集合，里面的categoryid和删除的categoryid是相同的。`
调试上面的程序，执行完第一句后，数据库里面categoryid是312317329132的都被删除了。然后执行完第二句，list的数据并没有插入成功。

**Comment by langxuelang** [comment]
你执行完delete操作后，执行下model的clearSavedState方法，就可以了

**Comment by sinyu890807** [comment]
楼上正解，因为你的model之前被存储过了，再次存储就存不进去了。单个model调用一下clearSavedState方法就可以了，集合的话调用markAsDeleted方法。

**Comment by mondongxr** [comment]
thank you very much
