### ISSUE TITLE
studio里面新建litepal.xml的时候新建不成功怎么回事

### ISSUE THREAD

**Issue by nanian** [LitePalFramework/LitePal#80]
studio里面新建litepal.xml的时候新建不成功怎么回事

**Comment by nanian** [comment]
studio里面新建litepal.xml的时候新建不成功怎么回事

**Comment by luchas** [comment]
我也碰到了，异常信息是：
Error:Error: Unsupported type 'dbname'
:app:mergeDebugResources FAILED
Error:Execution failed for task ':app:mergeDebugResources'.
> C:\Users\Administrator\Desktop\netease\NetEaseNewsTabs-master\Base\app\src\main\res\assets\litepal.xml: Error: Unsupported type 'dbname'

**Comment by sinyu890807** [comment]
你的assets目录建错了，不要建到res里面，和res平级

**Comment by LiHongxiang1993** [comment]
我的assets目录建对了为什么右击assets新建的litepal还在res目录下的value里

**Comment by LiHongxiang1993** [comment]
终于解决了，还是看书不仔细，郭神说的是在assets目录下新建一个litepal.xml文件，所以右击assets点new之后点击File，而不是点击Android resouce file，一个人自学这种蛋疼的问题好多
