### ISSUE TITLE
性能有点慢

### ISSUE THREAD

**Issue by jituijiaqiezi** [LitePalFramework/LitePal#81]
定义两个类Conversation和Msg，使用如下代码测试，得到saveData的时间为8958ms，getData时间为42878ms。这样就有点尴尬了。不知道是不是这样逐条插入和查询，真是这样，性能就有点慢了。

long last= System.currentTimeMillis();
        for(int i=0;i<100;i++) {
            Conversation conversation = new Conversation();
            conversation.setAvatar(url1);
            conversation.setConv_id(i+"");
            conversation.save();
            for (int j = 0; j < 10; j++) {
                Msg msg = new Msg();
                msg.setConv_id(i+"");
                msg.setAuto_id(i*100+j);
                msg.save();
            }
        }
        L.i(" saveData", (System.currentTimeMillis()-last)+"ms");
        last= System.currentTimeMillis();
        List<Conversation> convs= DataSupport.findAll(Conversation.class);
        for(Conversation conversation:convs){
            L.i(" conversation:",conversation.getConv_id());
            List<Msg> msgs=DataSupport.where("conv_id=?",conversation.getConv_id()).order("auto_id").find(Msg.class);
            for(Msg msg:msgs){
                L.i(" msg",msg.getAuto_id());
            }
        }
        L.i(" getData", (System.currentTimeMillis()-last)+"ms");

**Comment by TUBB** [comment]
批量操作可以用transactions，速度大概可以提升100倍

**Comment by jituijiaqiezi** [comment]
ok，我试试 @TUBB

**Comment by sinyu890807** [comment]
试下最新的1.3.2版本，性能有很大提升，具体1.3.2版本的功能讲解看这篇文章 http://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=502752443&idx=1&sn=8bddcf70ac3d40f67fd32e81a87e2bcf
