### ISSUE TITLE
关于List的问题

### ISSUE THREAD

**Issue by likaiyuan559** [LitePalFramework/LitePal#82]
我的对象中有一个List<String>，但是创建后读取出来没有数据，把数据库导出也没有该字段，为何？
List<String> lists = ArrayList<>();
lists.add("aaaaa");
lists.add("bbbbb");
lists.add("ccccc");
item.setList(lists);
item.save();
然后取出item时是没有数据的。

**Comment by sinyu890807** [comment]
这个功能现在还不支持，预计会在1.4.0版本中加入这个功能

**Comment by guolindev** [comment]
1.4.0版本中已经支持这个功能，现在升级litepal即可，代码无须任何改变。
