### ISSUE TITLE
表中如果有boolean类型的字段会查询失败 

### ISSUE THREAD

**Issue by jlertele** [LitePalFramework/LitePal#83]
有boolean参数时，保存是可以成功的，并能查询到正确的数据数量，查询取出数据时会失败，报“Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
                                                                                   org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference”
错误。

**Comment by sinyu890807** [comment]
有具体的代码吗，把你的model结构贴出来看看

**Comment by leoliuzhou** [comment]
public class ProjectType extends DataSupport {
    @SerializedName("id")
    private String typeId;
    private String name;
    private boolean isCheck = false;

    public ProjectType(String typeId, String name, boolean isCheck) {
        this.typeId = typeId;
        this.name = name;
        this.isCheck = isCheck;
    }

    public String getTypeId() {
        return typeId;
    }

    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isCheck() {
        return isCheck;
    }

    public void setCheck(boolean check) {
        isCheck = check;
    }

    @Override
    public String toString() {
        return "ProjectType{" +
                "typeId='" + typeId + '\'' +
                ", name='" + name + '\'' +
                ", isCheck=" + isCheck +
                '}';
    }
}

**Comment by leoliuzhou** [comment]
我这边测试只要把 isCkeck 字段去除，再保存到数据库，就能正常从数据库取出数据

**Comment by sinyu890807** [comment]
我使用的就是你上面贴的数据结构，存储的代码是这样写的：
```java
ProjectType project = new ProjectType("123", "hello", false);
project.save();
```
查询的代码是这样写的：
```java
List<ProjectType> list = DataSupport.findAll(ProjectType.class);
for (ProjectType type: list) {					
	Log.d("TAG", "type id is " + type.getTypeId());
	Log.d("TAG", "type name is " + type.getName());
	Log.d("TAG", "type check is " + type.isCheck());
}
```
最后打印出来的结果是这样的：
06-10 18:22:33.168: D/TAG(32475): type id is 123
06-10 18:22:33.168: D/TAG(32475): type name is hello
06-10 18:22:33.168: D/TAG(32475): type check is true

没发现有什么问题。 你那边有问题的代码是什么样的，能发一下吗？

**Comment by leoliuzhou** [comment]
插入数据的代码和你上面的操作基本没有区别，我尝试直接用你上面的代码进行数据的插入与查询，也会直接报错，还是报'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()'错误，一般报这个错误的原因可能会是什么？

**Comment by leoliuzhou** [comment]
发现一个很奇怪的问题，例如我当前使用litePal库版本为1.3.1，此时我调用你提供的那一段代码进行插入数据与查询操作时，查询数据时程序报错闪退。此时我将库版本直接升级为1.3.2后，再次运行项目，app运行正常，并能打印出查询到的数据。然后将app从手机卸载，再次运行项目到手机，查询数据时又会报错。测试机型系统版本为Android5.0

**Comment by LiChangXing** [comment]
你将 boolean的 变量名  改成小写 就OK了

**Comment by Kinny2014** [comment]
ProjectType project = new ProjectType("123", "hello", false);
project.save();
查询的代码是这样写的：

List<ProjectType> list = DataSupport.findAll(ProjectType.class);
for (ProjectType type: list) {                  
    Log.d("TAG", "type id is " + type.getTypeId());
    Log.d("TAG", "type name is " + type.getName());
    Log.d("TAG", "type check is " + type.isCheck());
}
最后打印出来的结果是这样的：
06-10 18:22:33.168: D/TAG(32475): type id is 123
06-10 18:22:33.168: D/TAG(32475): type name is hello
06-10 18:22:33.168: D/TAG(32475): type check is true


你save的isCheck是false，查询出来的值是true。这还没问题么？@sinyu890807

**Comment by Kinny2014** [comment]
@LiChangXing 改成小写也不行哦，你是怎么解决的？

**Comment by Kinny2014** [comment]
@jlertele 请问你解决了吗，怎么解决的？

**Comment by guolindev** [comment]
问题原因找到了，和boolean无关，而是和你的类中有一个3个参数的构造函数有关。这是因为Android Studio的Instant Run会向Model里面注入一个带有2个参数的构建函数，而LitePal在用反射进行对象创建的时候会寻找参数最少的那个构造函数，如果你的Model中是一个3个参数的构造函数，那LitePal就会找错创建对象的方法，从而报出上面的错误。这个bug在1.4.0版本中已修复。

**Comment by Dkaishu** [comment]
我也遇到这个问题，我的构造函数的参数有一个是List类型，报错，去掉后用set法方赋值没问题，不知道有没有跟好的方式

**Comment by keien411** [comment]
哇  这个boolean类型的变量名为什么不能有大写的啊   找了好久的错啊
