### ISSUE TITLE
自定义Model中含有id字段

### ISSUE THREAD

**Issue by renzhongyiyan** [LitePalFramework/LitePal#84]
请问我在自定义的Model中包含了一个id字段，这个id字段的值是在服务端定义好的，我要取下来保存；网络请求使用的Retrofit，在进行json解析的时候要将Model定义的字段和服务器返回的字段一致；如果直接用Model.save()方法，插入数据库的id值是从1开始递增的，将我之前的id值覆盖掉了。请问怎么解决这个问题？

**Comment by daiji168** [comment]
我也遇到了，请问你解决了吗？

**Comment by renzhongyiyan** [comment]
修改服务器端返回的id属性名是一种方式，但是必须要和服务端协调好，并做修改。如果应用已经有上线的版本，修改完成可能会影响之前的版本使用。服务器端无法修改的话，再用这个库操作数据库模块就有些麻烦了。

**Comment by sinyu890807** [comment]
不需要服务器修改，服务器返回的id客户端这边可以重命名一下，比如命名成server_id，这个id和litepal的id没有关系，只要保证命名不冲突就可以了。
