### ISSUE TITLE
请问常用类型的对象类型支持吗？比如：Integer

### ISSUE THREAD

**Issue by Justin-Xu** [LitePalFramework/LitePal#85]
为了方便json自动的转换，model我们一般使用对象类型，不使用常用类型，因为常用类型会有默认值。请问下：对于这些对象类型，LitePal支持吗？

另外，LitePal是否会有sql注入的安全问题？

**Comment by sinyu890807** [comment]
对象数据类型支持这几种，Integer, Short, Long, Double, Float, Character, Boolean, Byte[], String，其实你自己试一下就知道了。
LitePal不会有sql注入的安全问题，因为不是用拼装sql语句的方法实现的。

**Comment by Justin-Xu** [comment]
感谢。

我又仔细拜读了一下源码，确实不是用拼装实现的，但是很奇怪，有一处却用了拼装，在级联删除的时候：
private String buildConditionString(String... conditions) {
		  int argCount = conditions.length - 1;
          String whereClause = conditions[0];
          for (int i = 0; i < argCount; i++) {
                  whereClause = whereClause.replaceFirst("\\?", "'" + conditions[i+1] + "'");
          }
          return whereClause;
	}

这里有特殊的原因吗？

**Comment by sinyu890807** [comment]
你看得还真仔细，就这一个地方都能让你发现了。这个当时可能是因为级联删除的where语言比较复杂，提取里面占位符有点麻烦，我为了省事就直接字符串拼接了，下个版本里面我会优化下这个问题。
