### ISSUE TITLE
关于数据关联的问题

### ISSUE THREAD

**Issue by Blankeer** [LitePalFramework/LitePal#87]
我现在有3张表，house  room   device, house和room一对多，room和device多对多，当我读取house的时候，会报错，详情：

>  org.litepal.exceptions.DataSupportException: Attempt to invoke interface method 'boolean java.util.Collection.add(java.lang.Object)' on a null object reference
>                                                                       at org.litepal.crud.DataHandler.query(DataHandler.java:142)
>                                                                       at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:122)
>                                                                       at org.litepal.crud.DataSupport.findAll(DataSupport.java:629)
> 

谢谢

**Comment by sinyu890807** [comment]
有具体的代码吗？把你的实体类结构，还有读取的具体代码贴一下

**Comment by Blankeer** [comment]
感谢回答，这个问题已经解决了，但是有新的问题。A和B一对多，B和C多对多，各自持有List<>关联类集合，findall（class,true）读取A，A的List<B>不为空，但是LIst<B>.get(0).getCList()为空。

**Comment by sinyu890807** [comment]
这个我知道的，因为考虑激进查询分析过多关联关系太过于影响性能，所以只做了一级关联查询，像你这种多级的情况还是使用懒加载吧，暂时只能这样，以后我再考虑优化优化。
