### ISSUE TITLE
publish to maven central?

### ISSUE THREAD

**Issue by pedant** [LitePalFramework/LitePal#9]
I can't find LitePal in Maven Central Repositories.Could it be published to maven? it's helpful for gradle  developers.

**Comment by Frank-He** [comment]
Yes, can you publish to maven center?

**Comment by gengjiawen** [comment]
+1

**Comment by Reacoder** [comment]
+1

**Comment by jitpack** [comment]
Btw, it's very easy to publish on https://jitpack.io but you'd need a gradle or maven build file

**Comment by sinyu890807** [comment]
LitePal is available on jcenter since 1.2.0 version. Read more details on project home page.
