### ISSUE TITLE
现在最大的问题是慢，很慢，太慢了

### ISSUE THREAD

**Issue by wjsxsbww** [LitePalFramework/LitePal#91]
这个库真的很方便，超级方便，超级好用，但是！！！太慢了！！！
简单的findfirst就会卡ui！！！！
查询70条数据需要90多ms（小米4c）！！！
用的是1.3.1  1.3.2还没有试

**Comment by wjsxsbww** [comment]
发现1.3.2快了很多，原来90多ms的降到了25ms左右
希望能再快点~~~

**Comment by sinyu890807** [comment]
后面还会继续优化的，谢谢建议
