### ISSUE TITLE
请问，表和表的关联是怎么做的？

### ISSUE THREAD

**Issue by zxc120301945** [LitePalFramework/LitePal#93]
我在一个对象中设置一个集合，这个集合里面保存的是另一个对象，我又在这个对象中设置一个集合，这个集合里面保存的是又一个对象，这种关联，按照litepal的保存规则进行的保存，说是保存成功了，但是拿到的集合都是空的。其他的字段都能获取正确

**Comment by sinyu890807** [comment]
因为litepal默认是不会加载关联表里面的数据的，这样会影响效率。如果你需要关联表中的数据，可以使用激进加载，在find方法里面都有一个isEager参数，指定成true就会加载关联表里面的数据了。

**Comment by zxc120301945** [comment]
好的 感谢指点！

**Comment by zxc120301945** [comment]
只能拿到下一张表的内容，如果保存的对象里面还有一个对象的集合呢？这样能再往下获取吗

**Comment by sinyu890807** [comment]
这个就太影响效率了，litepal的激进查询只读一级，再多的话建议你用懒加载吧

**Comment by zxc120301945** [comment]
好的 谢谢指点
