### ISSUE TITLE
1.3.2还是不支持distinct查询吗？

### ISSUE THREAD

**Issue by IT-Yeung** [LitePalFramework/LitePal#94]
升级到1.3.2发现还是不支持distinct去重复查询，请问有什么办法可以方便解决distinct这个问题，有没有什么好的建议，希望郭神之后能加上这个功能

**Comment by sinyu890807** [comment]
distinct不是我不想加，而是实在加不了，因为LitePal查出来的每条数据都是带id的，这样就导致每条返回的数据必然不相同，distinct也就没有作用了，目前我还没有想到什么好的办法可以解决。
