### ISSUE TITLE
关于每条数据ID的生成问题

### ISSUE THREAD

**Issue by choucai** [LitePalFramework/LitePal#98]
目前，每条数据的ID都动态生成的，为何不能像OrmLite那样支持注解配置ID呢？
使用场景如下：有时候，服务器返数据本身带有ID，这时候我们根据id去查询出指定的唯一一条数据就好了，而不是去根据这个id字段去过滤查询，返回一个集合，再从第一条获取。不能让开发者自己配置ID有点束缚啊

**Comment by 1345g2354** [comment]
有时候，服务器返数据本身带有ID，这是后吧数据存起来，那么服务器返回的ID就会被数据库的ID给冲掉，怎么办

**Comment by laksg2009** [comment]
我现在的项目后台返回来的字段就是叫ID肯爹的现在都不知道怎么搞了晕死了。。技术渣呀。。求解呀。。。

**Comment by laksg2009** [comment]
@1345g2354 我用的是fastjson可以使用这个注解@JSONField(name="id")  private int mid;  这个时候数据库里面就会出现mid这列数据了，对应得就是后台返回来的id字段的数据，如果你是用Gson的话是这个注解@SerializedName("id") private int mid;

**Comment by jjdxmashl** [comment]
@laksg2009  相当于给字段重命名，但是，id的这个字段就不能重新定义了，还是没有用啊，例如：
int id;
@SerializedName("id")
String mid;

如果同时定义了id和重命名的mid字段后，json解析，mid是没有解析不出来的，还好会解析给int i里面。这个是我一直纠结的问题，重命名了id以后，更新就不能使用简洁的方式了

**Comment by guolindev** [comment]
其实你上面那种写法就是最标准的写法了，当然mid的变量命名有待商讨。我这样来解释吧，服务器返回过来的json中可能往往会带有一个id字段，但是litepal是不可能无条件信任服务器发送过来的任何东西的，那个是服务器那边定义的id，而litepal内部自己也会有一个id，这是客户端这种定义的id，两者是没有直接关系的。你可以把服务器那边返回的id命名成serverid这样的字段，然后用@SerializedName这种方式添加一下gson的映射就可以解决了。

**Comment by jjdxmashl** [comment]
铺下路吧，改用fastjson来解决了id冲掉的问题，先来解析下json转bean称为反序列化，bean转json称为序列化

fastjson的反序列化直接修改key名称我没有找到，只找到序列化修改key名称的方法，因此用一个较笨的做法来达到目的，json转bean、bean转json、json转bean，看似有点重复却很有效，

resultJson-->TempBean-->temJson-->ResultBean

像上面的，resultJson为返回的json数据，TempBean为临时转换的Bean，tempJson为临时的json数据，ResultBean为最终解析数据得到的Bean。


TempBean temBean = JSON.parseObject(resultJson, TempBean.class);

String temJson = JSON.toJSONString(temBean , new NameFilter() {
                            @Override
                            public String process(Object object, String propertyName, Object propertyValue) {
                                if ("id".equals(propertyName)) {
                                    \\需要修改字段名称的在这里修改即可，可以修改多个，需要修改的返回修改后的名称，否则返回原名称
                                    return "mId";
                                }
                                return propertyName;
                            }
                        });

ResultBean resultBean = JSON.parseObject(temJson , ResultBean.class);

**Comment by 1345g2354** [comment]
@laksg2009  还真不知道利用三方的解析的时候可以改名字，谢谢啦。我当时就直接把这个裤的主键id自增的写法全部给换了。
