### ISSUE TITLE
Do Better

### ISSUE THREAD

**Issue by weiyitai** [LitePalFramework/LitePal#99]
I want an api like DataSupport.findColumn,but findBySQL,thank you!

**Comment by guolindev** [comment]
You mean find the specific column data?
I guess DataSupport.select().find() will fit you.

**Comment by weiyitai** [comment]
yes!I would like api like DataSupport.findColumn（name）,you return all the data of this column.just like the api rawquery

**Comment by guolindev** [comment]
Well. This function can be handled by LitePal easily. You just use DataSupport.select(name).find(Model.class) ， and specified data will be returned in the model list. You just need to get value from model. That's it.
